#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arhivarius.ObjectModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="lanta")]
	public partial class ArhivDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Partner(tbl_Partner instance);
    partial void Updatetbl_Partner(tbl_Partner instance);
    partial void Deletetbl_Partner(tbl_Partner instance);
    partial void InsertArhiveDocument(ArhiveDocument instance);
    partial void UpdateArhiveDocument(ArhiveDocument instance);
    partial void DeleteArhiveDocument(ArhiveDocument instance);
    partial void Insertdict_Document(dict_Document instance);
    partial void Updatedict_Document(dict_Document instance);
    partial void Deletedict_Document(dict_Document instance);
    partial void InsertDocumentType(DocumentType instance);
    partial void UpdateDocumentType(DocumentType instance);
    partial void DeleteDocumentType(DocumentType instance);
    partial void InsertLTArh_History(LTArh_History instance);
    partial void UpdateLTArh_History(LTArh_History instance);
    partial void DeleteLTArh_History(LTArh_History instance);
    #endregion
		
		public ArhivDataContext() : 
				base(global::Arhivarius.Properties.Settings.Default.lantaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ArhivDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArhivDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArhivDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArhivDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Partner> tbl_Partners
		{
			get
			{
				return this.GetTable<tbl_Partner>();
			}
		}
		
		public System.Data.Linq.Table<ArhiveDocument> ArhiveDocuments
		{
			get
			{
				return this.GetTable<ArhiveDocument>();
			}
		}
		
		public System.Data.Linq.Table<dict_Document> dict_Documents
		{
			get
			{
				return this.GetTable<dict_Document>();
			}
		}
		
		public System.Data.Linq.Table<DocumentType> DocumentTypes
		{
			get
			{
				return this.GetTable<DocumentType>();
			}
		}
		
		public System.Data.Linq.Table<LTArh_History> LTArh_Histories
		{
			get
			{
				return this.GetTable<LTArh_History>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Partners")]
	public partial class tbl_Partner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PR_KEY;
		
		private string _PR_FULLNAME;
		
		private string _PR_NAME;
		
		private string _PR_NAMEENG;
		
		private string _PR_BOSSNAME;
		
		private string _PR_BOSS;
		
		private System.Nullable<short> _PR_MALE;
		
		private string _PR_MAINMEN;
		
		private string _PR_MAINMENPHONE;
		
		private System.Nullable<double> _PR_DISCOUNT;
		
		private string _PR_ACCOUNT;
		
		private string _PR_ADRESS;
		
		private string _PR_PHONES;
		
		private string _PR_FAX;
		
		private string _PR_EMAIL;
		
		private System.Nullable<int> _PR_CTKEY;
		
		private int _PR_CREATOR;
		
		private string _PR_AGENTDOGOVOR;
		
		private System.Nullable<long> _PR_TYPE;
		
		private string _PR_CITY;
		
		private System.Nullable<int> _PR_WEBAGENT;
		
		private System.Nullable<System.DateTime> _PR_AGENTDATE;
		
		private string _PR_AGENTDOGOVOR2;
		
		private System.Nullable<System.DateTime> _PR_AGENTDATE2;
		
		private string _PR_FAX1;
		
		private string _PR_REMARK;
		
		private System.Nullable<System.DateTime> _PR_CREATEDATE;
		
		private System.Nullable<System.DateTime> _PR_UPDATEDATE;
		
		private System.Nullable<int> _PR_ART;
		
		private System.Nullable<int> _PR_USERLAST;
		
		private string _PR_COD;
		
		private System.Data.Linq.Binary _ROWID;
		
		private string _LastUser;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private int _pr_IsActive;
		
		private int _PR_Filial;
		
		private System.Nullable<System.DateTime> _PR_DateLastContact;
		
		private string _PR_ExchangePwd;
		
		private string _PR_GUID;
		
		private System.Data.Linq.Binary _PR_ExchangeData;
		
		private string _MaskedFax;
		
		private short _PR_DOGOVORTYPE;
		
		private string _PR_ICQ;
		
		private string _PR_GDS_PREFIX;
		
		private string _PR_GDS_SUFFIX;
		
		private System.Nullable<int> _PR_OWNER;
		
		private string _PR_IPAddress;
		
		private short _PR_Deleted;
		
		private string _PR_LICENSENUMBER;
		
		private string _PR_ADDITIONALINFO;
		
		private string _PR_LEGALADDRESS;
		
		private string _PR_INN;
		
		private string _PR_FOREIGNACCINFO;
		
		private string _PR_KPP;
		
		private string _PR_CODEOKONH;
		
		private string _PR_CODEOKPO;
		
		private string _PR_HOMEPAGE;
		
		private int _PR_PGKEY;
		
		private short _PR_BLOCKEDFORANNUL;
		
		private string _PR_POSTINDEX;
		
		private string _PR_LEGALPOSTINDEX;
		
		private string _PR_RegisterSeries;
		
		private string _PR_RegisterNumber;
		
		private string _PR_Http;
		
		private string _pr_description;
		
		private string _PR_WebServiceUrl;
		
		private EntitySet<dict_Document> _dict_Documents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPR_KEYChanging(int value);
    partial void OnPR_KEYChanged();
    partial void OnPR_FULLNAMEChanging(string value);
    partial void OnPR_FULLNAMEChanged();
    partial void OnPR_NAMEChanging(string value);
    partial void OnPR_NAMEChanged();
    partial void OnPR_NAMEENGChanging(string value);
    partial void OnPR_NAMEENGChanged();
    partial void OnPR_BOSSNAMEChanging(string value);
    partial void OnPR_BOSSNAMEChanged();
    partial void OnPR_BOSSChanging(string value);
    partial void OnPR_BOSSChanged();
    partial void OnPR_MALEChanging(System.Nullable<short> value);
    partial void OnPR_MALEChanged();
    partial void OnPR_MAINMENChanging(string value);
    partial void OnPR_MAINMENChanged();
    partial void OnPR_MAINMENPHONEChanging(string value);
    partial void OnPR_MAINMENPHONEChanged();
    partial void OnPR_DISCOUNTChanging(System.Nullable<double> value);
    partial void OnPR_DISCOUNTChanged();
    partial void OnPR_ACCOUNTChanging(string value);
    partial void OnPR_ACCOUNTChanged();
    partial void OnPR_ADRESSChanging(string value);
    partial void OnPR_ADRESSChanged();
    partial void OnPR_PHONESChanging(string value);
    partial void OnPR_PHONESChanged();
    partial void OnPR_FAXChanging(string value);
    partial void OnPR_FAXChanged();
    partial void OnPR_EMAILChanging(string value);
    partial void OnPR_EMAILChanged();
    partial void OnPR_CTKEYChanging(System.Nullable<int> value);
    partial void OnPR_CTKEYChanged();
    partial void OnPR_CREATORChanging(int value);
    partial void OnPR_CREATORChanged();
    partial void OnPR_AGENTDOGOVORChanging(string value);
    partial void OnPR_AGENTDOGOVORChanged();
    partial void OnPR_TYPEChanging(System.Nullable<long> value);
    partial void OnPR_TYPEChanged();
    partial void OnPR_CITYChanging(string value);
    partial void OnPR_CITYChanged();
    partial void OnPR_WEBAGENTChanging(System.Nullable<int> value);
    partial void OnPR_WEBAGENTChanged();
    partial void OnPR_AGENTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPR_AGENTDATEChanged();
    partial void OnPR_AGENTDOGOVOR2Changing(string value);
    partial void OnPR_AGENTDOGOVOR2Changed();
    partial void OnPR_AGENTDATE2Changing(System.Nullable<System.DateTime> value);
    partial void OnPR_AGENTDATE2Changed();
    partial void OnPR_FAX1Changing(string value);
    partial void OnPR_FAX1Changed();
    partial void OnPR_REMARKChanging(string value);
    partial void OnPR_REMARKChanged();
    partial void OnPR_CREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPR_CREATEDATEChanged();
    partial void OnPR_UPDATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPR_UPDATEDATEChanged();
    partial void OnPR_ARTChanging(System.Nullable<int> value);
    partial void OnPR_ARTChanged();
    partial void OnPR_USERLASTChanging(System.Nullable<int> value);
    partial void OnPR_USERLASTChanged();
    partial void OnPR_CODChanging(string value);
    partial void OnPR_CODChanged();
    partial void OnROWIDChanging(System.Data.Linq.Binary value);
    partial void OnROWIDChanged();
    partial void OnLastUserChanging(string value);
    partial void OnLastUserChanged();
    partial void OnLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateChanged();
    partial void Onpr_IsActiveChanging(int value);
    partial void Onpr_IsActiveChanged();
    partial void OnPR_FilialChanging(int value);
    partial void OnPR_FilialChanged();
    partial void OnPR_DateLastContactChanging(System.Nullable<System.DateTime> value);
    partial void OnPR_DateLastContactChanged();
    partial void OnPR_ExchangePwdChanging(string value);
    partial void OnPR_ExchangePwdChanged();
    partial void OnPR_GUIDChanging(string value);
    partial void OnPR_GUIDChanged();
    partial void OnPR_ExchangeDataChanging(System.Data.Linq.Binary value);
    partial void OnPR_ExchangeDataChanged();
    partial void OnMaskedFaxChanging(string value);
    partial void OnMaskedFaxChanged();
    partial void OnPR_DOGOVORTYPEChanging(short value);
    partial void OnPR_DOGOVORTYPEChanged();
    partial void OnPR_ICQChanging(string value);
    partial void OnPR_ICQChanged();
    partial void OnPR_GDS_PREFIXChanging(string value);
    partial void OnPR_GDS_PREFIXChanged();
    partial void OnPR_GDS_SUFFIXChanging(string value);
    partial void OnPR_GDS_SUFFIXChanged();
    partial void OnPR_OWNERChanging(System.Nullable<int> value);
    partial void OnPR_OWNERChanged();
    partial void OnPR_IPAddressChanging(string value);
    partial void OnPR_IPAddressChanged();
    partial void OnPR_DeletedChanging(short value);
    partial void OnPR_DeletedChanged();
    partial void OnPR_LICENSENUMBERChanging(string value);
    partial void OnPR_LICENSENUMBERChanged();
    partial void OnPR_ADDITIONALINFOChanging(string value);
    partial void OnPR_ADDITIONALINFOChanged();
    partial void OnPR_LEGALADDRESSChanging(string value);
    partial void OnPR_LEGALADDRESSChanged();
    partial void OnPR_INNChanging(string value);
    partial void OnPR_INNChanged();
    partial void OnPR_FOREIGNACCINFOChanging(string value);
    partial void OnPR_FOREIGNACCINFOChanged();
    partial void OnPR_KPPChanging(string value);
    partial void OnPR_KPPChanged();
    partial void OnPR_CODEOKONHChanging(string value);
    partial void OnPR_CODEOKONHChanged();
    partial void OnPR_CODEOKPOChanging(string value);
    partial void OnPR_CODEOKPOChanged();
    partial void OnPR_HOMEPAGEChanging(string value);
    partial void OnPR_HOMEPAGEChanged();
    partial void OnPR_PGKEYChanging(int value);
    partial void OnPR_PGKEYChanged();
    partial void OnPR_BLOCKEDFORANNULChanging(short value);
    partial void OnPR_BLOCKEDFORANNULChanged();
    partial void OnPR_POSTINDEXChanging(string value);
    partial void OnPR_POSTINDEXChanged();
    partial void OnPR_LEGALPOSTINDEXChanging(string value);
    partial void OnPR_LEGALPOSTINDEXChanged();
    partial void OnPR_RegisterSeriesChanging(string value);
    partial void OnPR_RegisterSeriesChanged();
    partial void OnPR_RegisterNumberChanging(string value);
    partial void OnPR_RegisterNumberChanged();
    partial void OnPR_HttpChanging(string value);
    partial void OnPR_HttpChanged();
    partial void Onpr_descriptionChanging(string value);
    partial void Onpr_descriptionChanged();
    partial void OnPR_WebServiceUrlChanging(string value);
    partial void OnPR_WebServiceUrlChanged();
    #endregion
		
		public tbl_Partner()
		{
			this._dict_Documents = new EntitySet<dict_Document>(new Action<dict_Document>(this.attach_dict_Documents), new Action<dict_Document>(this.detach_dict_Documents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_KEY", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int PR_KEY
		{
			get
			{
				return this._PR_KEY;
			}
			set
			{
				if ((this._PR_KEY != value))
				{
					this.OnPR_KEYChanging(value);
					this.SendPropertyChanging();
					this._PR_KEY = value;
					this.SendPropertyChanged("PR_KEY");
					this.OnPR_KEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_FULLNAME", DbType="VarChar(160)", UpdateCheck=UpdateCheck.Never)]
		public string PR_FULLNAME
		{
			get
			{
				return this._PR_FULLNAME;
			}
			set
			{
				if ((this._PR_FULLNAME != value))
				{
					this.OnPR_FULLNAMEChanging(value);
					this.SendPropertyChanging();
					this._PR_FULLNAME = value;
					this.SendPropertyChanged("PR_FULLNAME");
					this.OnPR_FULLNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_NAME", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string PR_NAME
		{
			get
			{
				return this._PR_NAME;
			}
			set
			{
				if ((this._PR_NAME != value))
				{
					this.OnPR_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PR_NAME = value;
					this.SendPropertyChanged("PR_NAME");
					this.OnPR_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_NAMEENG", DbType="VarChar(80)", UpdateCheck=UpdateCheck.Never)]
		public string PR_NAMEENG
		{
			get
			{
				return this._PR_NAMEENG;
			}
			set
			{
				if ((this._PR_NAMEENG != value))
				{
					this.OnPR_NAMEENGChanging(value);
					this.SendPropertyChanging();
					this._PR_NAMEENG = value;
					this.SendPropertyChanged("PR_NAMEENG");
					this.OnPR_NAMEENGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_BOSSNAME", DbType="VarChar(40)", UpdateCheck=UpdateCheck.Never)]
		public string PR_BOSSNAME
		{
			get
			{
				return this._PR_BOSSNAME;
			}
			set
			{
				if ((this._PR_BOSSNAME != value))
				{
					this.OnPR_BOSSNAMEChanging(value);
					this.SendPropertyChanging();
					this._PR_BOSSNAME = value;
					this.SendPropertyChanged("PR_BOSSNAME");
					this.OnPR_BOSSNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_BOSS", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PR_BOSS
		{
			get
			{
				return this._PR_BOSS;
			}
			set
			{
				if ((this._PR_BOSS != value))
				{
					this.OnPR_BOSSChanging(value);
					this.SendPropertyChanging();
					this._PR_BOSS = value;
					this.SendPropertyChanged("PR_BOSS");
					this.OnPR_BOSSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_MALE", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> PR_MALE
		{
			get
			{
				return this._PR_MALE;
			}
			set
			{
				if ((this._PR_MALE != value))
				{
					this.OnPR_MALEChanging(value);
					this.SendPropertyChanging();
					this._PR_MALE = value;
					this.SendPropertyChanged("PR_MALE");
					this.OnPR_MALEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_MAINMEN", DbType="VarChar(45)", UpdateCheck=UpdateCheck.Never)]
		public string PR_MAINMEN
		{
			get
			{
				return this._PR_MAINMEN;
			}
			set
			{
				if ((this._PR_MAINMEN != value))
				{
					this.OnPR_MAINMENChanging(value);
					this.SendPropertyChanging();
					this._PR_MAINMEN = value;
					this.SendPropertyChanged("PR_MAINMEN");
					this.OnPR_MAINMENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_MAINMENPHONE", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PR_MAINMENPHONE
		{
			get
			{
				return this._PR_MAINMENPHONE;
			}
			set
			{
				if ((this._PR_MAINMENPHONE != value))
				{
					this.OnPR_MAINMENPHONEChanging(value);
					this.SendPropertyChanging();
					this._PR_MAINMENPHONE = value;
					this.SendPropertyChanged("PR_MAINMENPHONE");
					this.OnPR_MAINMENPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_DISCOUNT", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> PR_DISCOUNT
		{
			get
			{
				return this._PR_DISCOUNT;
			}
			set
			{
				if ((this._PR_DISCOUNT != value))
				{
					this.OnPR_DISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._PR_DISCOUNT = value;
					this.SendPropertyChanged("PR_DISCOUNT");
					this.OnPR_DISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_ACCOUNT", DbType="VarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string PR_ACCOUNT
		{
			get
			{
				return this._PR_ACCOUNT;
			}
			set
			{
				if ((this._PR_ACCOUNT != value))
				{
					this.OnPR_ACCOUNTChanging(value);
					this.SendPropertyChanging();
					this._PR_ACCOUNT = value;
					this.SendPropertyChanged("PR_ACCOUNT");
					this.OnPR_ACCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_ADRESS", DbType="VarChar(160)", UpdateCheck=UpdateCheck.Never)]
		public string PR_ADRESS
		{
			get
			{
				return this._PR_ADRESS;
			}
			set
			{
				if ((this._PR_ADRESS != value))
				{
					this.OnPR_ADRESSChanging(value);
					this.SendPropertyChanging();
					this._PR_ADRESS = value;
					this.SendPropertyChanged("PR_ADRESS");
					this.OnPR_ADRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_PHONES", DbType="VarChar(254)", UpdateCheck=UpdateCheck.Never)]
		public string PR_PHONES
		{
			get
			{
				return this._PR_PHONES;
			}
			set
			{
				if ((this._PR_PHONES != value))
				{
					this.OnPR_PHONESChanging(value);
					this.SendPropertyChanging();
					this._PR_PHONES = value;
					this.SendPropertyChanged("PR_PHONES");
					this.OnPR_PHONESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_FAX", DbType="VarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string PR_FAX
		{
			get
			{
				return this._PR_FAX;
			}
			set
			{
				if ((this._PR_FAX != value))
				{
					this.OnPR_FAXChanging(value);
					this.SendPropertyChanging();
					this._PR_FAX = value;
					this.SendPropertyChanged("PR_FAX");
					this.OnPR_FAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_EMAIL", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PR_EMAIL
		{
			get
			{
				return this._PR_EMAIL;
			}
			set
			{
				if ((this._PR_EMAIL != value))
				{
					this.OnPR_EMAILChanging(value);
					this.SendPropertyChanging();
					this._PR_EMAIL = value;
					this.SendPropertyChanged("PR_EMAIL");
					this.OnPR_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_CTKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PR_CTKEY
		{
			get
			{
				return this._PR_CTKEY;
			}
			set
			{
				if ((this._PR_CTKEY != value))
				{
					this.OnPR_CTKEYChanging(value);
					this.SendPropertyChanging();
					this._PR_CTKEY = value;
					this.SendPropertyChanged("PR_CTKEY");
					this.OnPR_CTKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_CREATOR", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int PR_CREATOR
		{
			get
			{
				return this._PR_CREATOR;
			}
			set
			{
				if ((this._PR_CREATOR != value))
				{
					this.OnPR_CREATORChanging(value);
					this.SendPropertyChanging();
					this._PR_CREATOR = value;
					this.SendPropertyChanged("PR_CREATOR");
					this.OnPR_CREATORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_AGENTDOGOVOR", DbType="VarChar(12)", UpdateCheck=UpdateCheck.Never)]
		public string PR_AGENTDOGOVOR
		{
			get
			{
				return this._PR_AGENTDOGOVOR;
			}
			set
			{
				if ((this._PR_AGENTDOGOVOR != value))
				{
					this.OnPR_AGENTDOGOVORChanging(value);
					this.SendPropertyChanging();
					this._PR_AGENTDOGOVOR = value;
					this.SendPropertyChanged("PR_AGENTDOGOVOR");
					this.OnPR_AGENTDOGOVORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_TYPE", DbType="BigInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<long> PR_TYPE
		{
			get
			{
				return this._PR_TYPE;
			}
			set
			{
				if ((this._PR_TYPE != value))
				{
					this.OnPR_TYPEChanging(value);
					this.SendPropertyChanging();
					this._PR_TYPE = value;
					this.SendPropertyChanged("PR_TYPE");
					this.OnPR_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_CITY", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PR_CITY
		{
			get
			{
				return this._PR_CITY;
			}
			set
			{
				if ((this._PR_CITY != value))
				{
					this.OnPR_CITYChanging(value);
					this.SendPropertyChanging();
					this._PR_CITY = value;
					this.SendPropertyChanged("PR_CITY");
					this.OnPR_CITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_WEBAGENT", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PR_WEBAGENT
		{
			get
			{
				return this._PR_WEBAGENT;
			}
			set
			{
				if ((this._PR_WEBAGENT != value))
				{
					this.OnPR_WEBAGENTChanging(value);
					this.SendPropertyChanging();
					this._PR_WEBAGENT = value;
					this.SendPropertyChanged("PR_WEBAGENT");
					this.OnPR_WEBAGENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_AGENTDATE", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> PR_AGENTDATE
		{
			get
			{
				return this._PR_AGENTDATE;
			}
			set
			{
				if ((this._PR_AGENTDATE != value))
				{
					this.OnPR_AGENTDATEChanging(value);
					this.SendPropertyChanging();
					this._PR_AGENTDATE = value;
					this.SendPropertyChanged("PR_AGENTDATE");
					this.OnPR_AGENTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_AGENTDOGOVOR2", DbType="VarChar(12)", UpdateCheck=UpdateCheck.Never)]
		public string PR_AGENTDOGOVOR2
		{
			get
			{
				return this._PR_AGENTDOGOVOR2;
			}
			set
			{
				if ((this._PR_AGENTDOGOVOR2 != value))
				{
					this.OnPR_AGENTDOGOVOR2Changing(value);
					this.SendPropertyChanging();
					this._PR_AGENTDOGOVOR2 = value;
					this.SendPropertyChanged("PR_AGENTDOGOVOR2");
					this.OnPR_AGENTDOGOVOR2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_AGENTDATE2", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> PR_AGENTDATE2
		{
			get
			{
				return this._PR_AGENTDATE2;
			}
			set
			{
				if ((this._PR_AGENTDATE2 != value))
				{
					this.OnPR_AGENTDATE2Changing(value);
					this.SendPropertyChanging();
					this._PR_AGENTDATE2 = value;
					this.SendPropertyChanged("PR_AGENTDATE2");
					this.OnPR_AGENTDATE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_FAX1", DbType="VarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string PR_FAX1
		{
			get
			{
				return this._PR_FAX1;
			}
			set
			{
				if ((this._PR_FAX1 != value))
				{
					this.OnPR_FAX1Changing(value);
					this.SendPropertyChanging();
					this._PR_FAX1 = value;
					this.SendPropertyChanged("PR_FAX1");
					this.OnPR_FAX1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_REMARK", DbType="VarChar(254)", UpdateCheck=UpdateCheck.Never)]
		public string PR_REMARK
		{
			get
			{
				return this._PR_REMARK;
			}
			set
			{
				if ((this._PR_REMARK != value))
				{
					this.OnPR_REMARKChanging(value);
					this.SendPropertyChanging();
					this._PR_REMARK = value;
					this.SendPropertyChanged("PR_REMARK");
					this.OnPR_REMARKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_CREATEDATE", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> PR_CREATEDATE
		{
			get
			{
				return this._PR_CREATEDATE;
			}
			set
			{
				if ((this._PR_CREATEDATE != value))
				{
					this.OnPR_CREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._PR_CREATEDATE = value;
					this.SendPropertyChanged("PR_CREATEDATE");
					this.OnPR_CREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_UPDATEDATE", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> PR_UPDATEDATE
		{
			get
			{
				return this._PR_UPDATEDATE;
			}
			set
			{
				if ((this._PR_UPDATEDATE != value))
				{
					this.OnPR_UPDATEDATEChanging(value);
					this.SendPropertyChanging();
					this._PR_UPDATEDATE = value;
					this.SendPropertyChanged("PR_UPDATEDATE");
					this.OnPR_UPDATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_ART", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PR_ART
		{
			get
			{
				return this._PR_ART;
			}
			set
			{
				if ((this._PR_ART != value))
				{
					this.OnPR_ARTChanging(value);
					this.SendPropertyChanging();
					this._PR_ART = value;
					this.SendPropertyChanged("PR_ART");
					this.OnPR_ARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_USERLAST", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PR_USERLAST
		{
			get
			{
				return this._PR_USERLAST;
			}
			set
			{
				if ((this._PR_USERLAST != value))
				{
					this.OnPR_USERLASTChanging(value);
					this.SendPropertyChanging();
					this._PR_USERLAST = value;
					this.SendPropertyChanged("PR_USERLAST");
					this.OnPR_USERLASTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_COD", DbType="VarChar(6)", UpdateCheck=UpdateCheck.Never)]
		public string PR_COD
		{
			get
			{
				return this._PR_COD;
			}
			set
			{
				if ((this._PR_COD != value))
				{
					this.OnPR_CODChanging(value);
					this.SendPropertyChanging();
					this._PR_COD = value;
					this.SendPropertyChanged("PR_COD");
					this.OnPR_CODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWID", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ROWID
		{
			get
			{
				return this._ROWID;
			}
			set
			{
				if ((this._ROWID != value))
				{
					this.OnROWIDChanging(value);
					this.SendPropertyChanging();
					this._ROWID = value;
					this.SendPropertyChanged("ROWID");
					this.OnROWIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUser", DbType="Char(30)", UpdateCheck=UpdateCheck.Never)]
		public string LastUser
		{
			get
			{
				return this._LastUser;
			}
			set
			{
				if ((this._LastUser != value))
				{
					this.OnLastUserChanging(value);
					this.SendPropertyChanging();
					this._LastUser = value;
					this.SendPropertyChanged("LastUser");
					this.OnLastUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_IsActive", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int pr_IsActive
		{
			get
			{
				return this._pr_IsActive;
			}
			set
			{
				if ((this._pr_IsActive != value))
				{
					this.Onpr_IsActiveChanging(value);
					this.SendPropertyChanging();
					this._pr_IsActive = value;
					this.SendPropertyChanged("pr_IsActive");
					this.Onpr_IsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_Filial", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int PR_Filial
		{
			get
			{
				return this._PR_Filial;
			}
			set
			{
				if ((this._PR_Filial != value))
				{
					this.OnPR_FilialChanging(value);
					this.SendPropertyChanging();
					this._PR_Filial = value;
					this.SendPropertyChanged("PR_Filial");
					this.OnPR_FilialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_DateLastContact", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> PR_DateLastContact
		{
			get
			{
				return this._PR_DateLastContact;
			}
			set
			{
				if ((this._PR_DateLastContact != value))
				{
					this.OnPR_DateLastContactChanging(value);
					this.SendPropertyChanging();
					this._PR_DateLastContact = value;
					this.SendPropertyChanged("PR_DateLastContact");
					this.OnPR_DateLastContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_ExchangePwd", DbType="VarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string PR_ExchangePwd
		{
			get
			{
				return this._PR_ExchangePwd;
			}
			set
			{
				if ((this._PR_ExchangePwd != value))
				{
					this.OnPR_ExchangePwdChanging(value);
					this.SendPropertyChanging();
					this._PR_ExchangePwd = value;
					this.SendPropertyChanged("PR_ExchangePwd");
					this.OnPR_ExchangePwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_GUID", DbType="VarChar(40)", UpdateCheck=UpdateCheck.Never)]
		public string PR_GUID
		{
			get
			{
				return this._PR_GUID;
			}
			set
			{
				if ((this._PR_GUID != value))
				{
					this.OnPR_GUIDChanging(value);
					this.SendPropertyChanging();
					this._PR_GUID = value;
					this.SendPropertyChanged("PR_GUID");
					this.OnPR_GUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_ExchangeData", DbType="Binary(50)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PR_ExchangeData
		{
			get
			{
				return this._PR_ExchangeData;
			}
			set
			{
				if ((this._PR_ExchangeData != value))
				{
					this.OnPR_ExchangeDataChanging(value);
					this.SendPropertyChanging();
					this._PR_ExchangeData = value;
					this.SendPropertyChanged("PR_ExchangeData");
					this.OnPR_ExchangeDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaskedFax", DbType="VarChar(25)", UpdateCheck=UpdateCheck.Never)]
		public string MaskedFax
		{
			get
			{
				return this._MaskedFax;
			}
			set
			{
				if ((this._MaskedFax != value))
				{
					this.OnMaskedFaxChanging(value);
					this.SendPropertyChanging();
					this._MaskedFax = value;
					this.SendPropertyChanged("MaskedFax");
					this.OnMaskedFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_DOGOVORTYPE", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short PR_DOGOVORTYPE
		{
			get
			{
				return this._PR_DOGOVORTYPE;
			}
			set
			{
				if ((this._PR_DOGOVORTYPE != value))
				{
					this.OnPR_DOGOVORTYPEChanging(value);
					this.SendPropertyChanging();
					this._PR_DOGOVORTYPE = value;
					this.SendPropertyChanged("PR_DOGOVORTYPE");
					this.OnPR_DOGOVORTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_ICQ", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PR_ICQ
		{
			get
			{
				return this._PR_ICQ;
			}
			set
			{
				if ((this._PR_ICQ != value))
				{
					this.OnPR_ICQChanging(value);
					this.SendPropertyChanging();
					this._PR_ICQ = value;
					this.SendPropertyChanged("PR_ICQ");
					this.OnPR_ICQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_GDS_PREFIX", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PR_GDS_PREFIX
		{
			get
			{
				return this._PR_GDS_PREFIX;
			}
			set
			{
				if ((this._PR_GDS_PREFIX != value))
				{
					this.OnPR_GDS_PREFIXChanging(value);
					this.SendPropertyChanging();
					this._PR_GDS_PREFIX = value;
					this.SendPropertyChanged("PR_GDS_PREFIX");
					this.OnPR_GDS_PREFIXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_GDS_SUFFIX", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PR_GDS_SUFFIX
		{
			get
			{
				return this._PR_GDS_SUFFIX;
			}
			set
			{
				if ((this._PR_GDS_SUFFIX != value))
				{
					this.OnPR_GDS_SUFFIXChanging(value);
					this.SendPropertyChanging();
					this._PR_GDS_SUFFIX = value;
					this.SendPropertyChanged("PR_GDS_SUFFIX");
					this.OnPR_GDS_SUFFIXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_OWNER", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PR_OWNER
		{
			get
			{
				return this._PR_OWNER;
			}
			set
			{
				if ((this._PR_OWNER != value))
				{
					this.OnPR_OWNERChanging(value);
					this.SendPropertyChanging();
					this._PR_OWNER = value;
					this.SendPropertyChanged("PR_OWNER");
					this.OnPR_OWNERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_IPAddress", DbType="VarChar(80)", UpdateCheck=UpdateCheck.Never)]
		public string PR_IPAddress
		{
			get
			{
				return this._PR_IPAddress;
			}
			set
			{
				if ((this._PR_IPAddress != value))
				{
					this.OnPR_IPAddressChanging(value);
					this.SendPropertyChanging();
					this._PR_IPAddress = value;
					this.SendPropertyChanged("PR_IPAddress");
					this.OnPR_IPAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_Deleted", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short PR_Deleted
		{
			get
			{
				return this._PR_Deleted;
			}
			set
			{
				if ((this._PR_Deleted != value))
				{
					this.OnPR_DeletedChanging(value);
					this.SendPropertyChanging();
					this._PR_Deleted = value;
					this.SendPropertyChanged("PR_Deleted");
					this.OnPR_DeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_LICENSENUMBER", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PR_LICENSENUMBER
		{
			get
			{
				return this._PR_LICENSENUMBER;
			}
			set
			{
				if ((this._PR_LICENSENUMBER != value))
				{
					this.OnPR_LICENSENUMBERChanging(value);
					this.SendPropertyChanging();
					this._PR_LICENSENUMBER = value;
					this.SendPropertyChanged("PR_LICENSENUMBER");
					this.OnPR_LICENSENUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_ADDITIONALINFO", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PR_ADDITIONALINFO
		{
			get
			{
				return this._PR_ADDITIONALINFO;
			}
			set
			{
				if ((this._PR_ADDITIONALINFO != value))
				{
					this.OnPR_ADDITIONALINFOChanging(value);
					this.SendPropertyChanging();
					this._PR_ADDITIONALINFO = value;
					this.SendPropertyChanged("PR_ADDITIONALINFO");
					this.OnPR_ADDITIONALINFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_LEGALADDRESS", DbType="VarChar(160)", UpdateCheck=UpdateCheck.Never)]
		public string PR_LEGALADDRESS
		{
			get
			{
				return this._PR_LEGALADDRESS;
			}
			set
			{
				if ((this._PR_LEGALADDRESS != value))
				{
					this.OnPR_LEGALADDRESSChanging(value);
					this.SendPropertyChanging();
					this._PR_LEGALADDRESS = value;
					this.SendPropertyChanged("PR_LEGALADDRESS");
					this.OnPR_LEGALADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_INN", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PR_INN
		{
			get
			{
				return this._PR_INN;
			}
			set
			{
				if ((this._PR_INN != value))
				{
					this.OnPR_INNChanging(value);
					this.SendPropertyChanging();
					this._PR_INN = value;
					this.SendPropertyChanged("PR_INN");
					this.OnPR_INNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_FOREIGNACCINFO", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string PR_FOREIGNACCINFO
		{
			get
			{
				return this._PR_FOREIGNACCINFO;
			}
			set
			{
				if ((this._PR_FOREIGNACCINFO != value))
				{
					this.OnPR_FOREIGNACCINFOChanging(value);
					this.SendPropertyChanging();
					this._PR_FOREIGNACCINFO = value;
					this.SendPropertyChanged("PR_FOREIGNACCINFO");
					this.OnPR_FOREIGNACCINFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_KPP", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string PR_KPP
		{
			get
			{
				return this._PR_KPP;
			}
			set
			{
				if ((this._PR_KPP != value))
				{
					this.OnPR_KPPChanging(value);
					this.SendPropertyChanging();
					this._PR_KPP = value;
					this.SendPropertyChanged("PR_KPP");
					this.OnPR_KPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_CODEOKONH", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string PR_CODEOKONH
		{
			get
			{
				return this._PR_CODEOKONH;
			}
			set
			{
				if ((this._PR_CODEOKONH != value))
				{
					this.OnPR_CODEOKONHChanging(value);
					this.SendPropertyChanging();
					this._PR_CODEOKONH = value;
					this.SendPropertyChanged("PR_CODEOKONH");
					this.OnPR_CODEOKONHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_CODEOKPO", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string PR_CODEOKPO
		{
			get
			{
				return this._PR_CODEOKPO;
			}
			set
			{
				if ((this._PR_CODEOKPO != value))
				{
					this.OnPR_CODEOKPOChanging(value);
					this.SendPropertyChanging();
					this._PR_CODEOKPO = value;
					this.SendPropertyChanged("PR_CODEOKPO");
					this.OnPR_CODEOKPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_HOMEPAGE", DbType="VarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string PR_HOMEPAGE
		{
			get
			{
				return this._PR_HOMEPAGE;
			}
			set
			{
				if ((this._PR_HOMEPAGE != value))
				{
					this.OnPR_HOMEPAGEChanging(value);
					this.SendPropertyChanging();
					this._PR_HOMEPAGE = value;
					this.SendPropertyChanged("PR_HOMEPAGE");
					this.OnPR_HOMEPAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_PGKEY", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int PR_PGKEY
		{
			get
			{
				return this._PR_PGKEY;
			}
			set
			{
				if ((this._PR_PGKEY != value))
				{
					this.OnPR_PGKEYChanging(value);
					this.SendPropertyChanging();
					this._PR_PGKEY = value;
					this.SendPropertyChanged("PR_PGKEY");
					this.OnPR_PGKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_BLOCKEDFORANNUL", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short PR_BLOCKEDFORANNUL
		{
			get
			{
				return this._PR_BLOCKEDFORANNUL;
			}
			set
			{
				if ((this._PR_BLOCKEDFORANNUL != value))
				{
					this.OnPR_BLOCKEDFORANNULChanging(value);
					this.SendPropertyChanging();
					this._PR_BLOCKEDFORANNUL = value;
					this.SendPropertyChanged("PR_BLOCKEDFORANNUL");
					this.OnPR_BLOCKEDFORANNULChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_POSTINDEX", DbType="VarChar(6)", UpdateCheck=UpdateCheck.Never)]
		public string PR_POSTINDEX
		{
			get
			{
				return this._PR_POSTINDEX;
			}
			set
			{
				if ((this._PR_POSTINDEX != value))
				{
					this.OnPR_POSTINDEXChanging(value);
					this.SendPropertyChanging();
					this._PR_POSTINDEX = value;
					this.SendPropertyChanged("PR_POSTINDEX");
					this.OnPR_POSTINDEXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_LEGALPOSTINDEX", DbType="VarChar(6)", UpdateCheck=UpdateCheck.Never)]
		public string PR_LEGALPOSTINDEX
		{
			get
			{
				return this._PR_LEGALPOSTINDEX;
			}
			set
			{
				if ((this._PR_LEGALPOSTINDEX != value))
				{
					this.OnPR_LEGALPOSTINDEXChanging(value);
					this.SendPropertyChanging();
					this._PR_LEGALPOSTINDEX = value;
					this.SendPropertyChanged("PR_LEGALPOSTINDEX");
					this.OnPR_LEGALPOSTINDEXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_RegisterSeries", DbType="VarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string PR_RegisterSeries
		{
			get
			{
				return this._PR_RegisterSeries;
			}
			set
			{
				if ((this._PR_RegisterSeries != value))
				{
					this.OnPR_RegisterSeriesChanging(value);
					this.SendPropertyChanging();
					this._PR_RegisterSeries = value;
					this.SendPropertyChanged("PR_RegisterSeries");
					this.OnPR_RegisterSeriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_RegisterNumber", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PR_RegisterNumber
		{
			get
			{
				return this._PR_RegisterNumber;
			}
			set
			{
				if ((this._PR_RegisterNumber != value))
				{
					this.OnPR_RegisterNumberChanging(value);
					this.SendPropertyChanging();
					this._PR_RegisterNumber = value;
					this.SendPropertyChanged("PR_RegisterNumber");
					this.OnPR_RegisterNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_Http", DbType="VarChar(254)", UpdateCheck=UpdateCheck.Never)]
		public string PR_Http
		{
			get
			{
				return this._PR_Http;
			}
			set
			{
				if ((this._PR_Http != value))
				{
					this.OnPR_HttpChanging(value);
					this.SendPropertyChanging();
					this._PR_Http = value;
					this.SendPropertyChanged("PR_Http");
					this.OnPR_HttpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string pr_description
		{
			get
			{
				return this._pr_description;
			}
			set
			{
				if ((this._pr_description != value))
				{
					this.Onpr_descriptionChanging(value);
					this.SendPropertyChanging();
					this._pr_description = value;
					this.SendPropertyChanged("pr_description");
					this.Onpr_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_WebServiceUrl", DbType="VarChar(150)", UpdateCheck=UpdateCheck.Never)]
		public string PR_WebServiceUrl
		{
			get
			{
				return this._PR_WebServiceUrl;
			}
			set
			{
				if ((this._PR_WebServiceUrl != value))
				{
					this.OnPR_WebServiceUrlChanging(value);
					this.SendPropertyChanging();
					this._PR_WebServiceUrl = value;
					this.SendPropertyChanged("PR_WebServiceUrl");
					this.OnPR_WebServiceUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Partner_dict_Document", Storage="_dict_Documents", ThisKey="PR_KEY", OtherKey="PartnerKey")]
		public EntitySet<dict_Document> dict_Documents
		{
			get
			{
				return this._dict_Documents;
			}
			set
			{
				this._dict_Documents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dict_Documents(dict_Document entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Partner = this;
		}
		
		private void detach_dict_Documents(dict_Document entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Partner = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LTArh_Arhive")]
	public partial class ArhiveDocument : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ARH_Id;
		
		private System.DateTime _ARH_CRDate;
		
		private int _ARH_ARDTKey;
		
		private string _ARH_Number;
		
		private System.Nullable<int> _ARH_ARHID;
		
		private string _ARH_Comment;
		
		private string _ARH_UserName;
		
		private int _ARH_PkgNum;
		
		private System.Nullable<int> _ARH_CodeKey;
		
		private EntitySet<ArhiveDocument> _Chield;
		
		private EntitySet<LTArh_History> _HistoryChield;
		
		private EntitySet<LTArh_History> _HistoryParent;
		
		private EntityRef<ArhiveDocument> _Parent;
		
		private EntityRef<DocumentType> _DocumentType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnARH_IdChanging(int value);
    partial void OnARH_IdChanged();
    partial void OnARH_CRDateChanging(System.DateTime value);
    partial void OnARH_CRDateChanged();
    partial void OnARH_ARDTKeyChanging(int value);
    partial void OnARH_ARDTKeyChanged();
    partial void OnARH_NumberChanging(string value);
    partial void OnARH_NumberChanged();
    partial void OnARH_ARHIDChanging(System.Nullable<int> value);
    partial void OnARH_ARHIDChanged();
    partial void OnARH_CommentChanging(string value);
    partial void OnARH_CommentChanged();
    partial void OnARH_UserNameChanging(string value);
    partial void OnARH_UserNameChanged();
    partial void OnARH_PkgNumChanging(int value);
    partial void OnARH_PkgNumChanged();
    partial void OnARH_CodeKeyChanging(System.Nullable<int> value);
    partial void OnARH_CodeKeyChanged();
    #endregion
		
		public ArhiveDocument()
		{
			this._Chield = new EntitySet<ArhiveDocument>(new Action<ArhiveDocument>(this.attach_Chield), new Action<ArhiveDocument>(this.detach_Chield));
			this._HistoryChield = new EntitySet<LTArh_History>(new Action<LTArh_History>(this.attach_HistoryChield), new Action<LTArh_History>(this.detach_HistoryChield));
			this._HistoryParent = new EntitySet<LTArh_History>(new Action<LTArh_History>(this.attach_HistoryParent), new Action<LTArh_History>(this.detach_HistoryParent));
			this._Parent = default(EntityRef<ArhiveDocument>);
			this._DocumentType = default(EntityRef<DocumentType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARH_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ARH_Id
		{
			get
			{
				return this._ARH_Id;
			}
			set
			{
				if ((this._ARH_Id != value))
				{
					this.OnARH_IdChanging(value);
					this.SendPropertyChanging();
					this._ARH_Id = value;
					this.SendPropertyChanged("ARH_Id");
					this.OnARH_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARH_CRDate", DbType="DateTime NOT NULL")]
		public System.DateTime ARH_CRDate
		{
			get
			{
				return this._ARH_CRDate;
			}
			set
			{
				if ((this._ARH_CRDate != value))
				{
					this.OnARH_CRDateChanging(value);
					this.SendPropertyChanging();
					this._ARH_CRDate = value;
					this.SendPropertyChanged("ARH_CRDate");
					this.OnARH_CRDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARH_ARDTKey", DbType="Int NOT NULL")]
		public int ARH_ARDTKey
		{
			get
			{
				return this._ARH_ARDTKey;
			}
			set
			{
				if ((this._ARH_ARDTKey != value))
				{
					if (this._DocumentType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnARH_ARDTKeyChanging(value);
					this.SendPropertyChanging();
					this._ARH_ARDTKey = value;
					this.SendPropertyChanged("ARH_ARDTKey");
					this.OnARH_ARDTKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARH_Number", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ARH_Number
		{
			get
			{
				return this._ARH_Number;
			}
			set
			{
				if ((this._ARH_Number != value))
				{
					this.OnARH_NumberChanging(value);
					this.SendPropertyChanging();
					this._ARH_Number = value;
					this.SendPropertyChanged("ARH_Number");
					this.OnARH_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARH_ARHID", DbType="Int")]
		public System.Nullable<int> ARH_ARHID
		{
			get
			{
				return this._ARH_ARHID;
			}
			set
			{
				if ((this._ARH_ARHID != value))
				{
					if (this._Parent.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnARH_ARHIDChanging(value);
					this.SendPropertyChanging();
					this._ARH_ARHID = value;
					this.SendPropertyChanged("ARH_ARHID");
					this.OnARH_ARHIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARH_Comment", DbType="NVarChar(MAX)")]
		public string ARH_Comment
		{
			get
			{
				return this._ARH_Comment;
			}
			set
			{
				if ((this._ARH_Comment != value))
				{
					this.OnARH_CommentChanging(value);
					this.SendPropertyChanging();
					this._ARH_Comment = value;
					this.SendPropertyChanged("ARH_Comment");
					this.OnARH_CommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARH_UserName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string ARH_UserName
		{
			get
			{
				return this._ARH_UserName;
			}
			set
			{
				if ((this._ARH_UserName != value))
				{
					this.OnARH_UserNameChanging(value);
					this.SendPropertyChanging();
					this._ARH_UserName = value;
					this.SendPropertyChanged("ARH_UserName");
					this.OnARH_UserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARH_PkgNum", DbType="Int NOT NULL")]
		public int ARH_PkgNum
		{
			get
			{
				return this._ARH_PkgNum;
			}
			set
			{
				if ((this._ARH_PkgNum != value))
				{
					this.OnARH_PkgNumChanging(value);
					this.SendPropertyChanging();
					this._ARH_PkgNum = value;
					this.SendPropertyChanged("ARH_PkgNum");
					this.OnARH_PkgNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARH_CodeKey", DbType="int")]
		public System.Nullable<int> ARH_CodeKey
		{
			get
			{
				return this._ARH_CodeKey;
			}
			set
			{
				if ((this._ARH_CodeKey != value))
				{
					this.OnARH_CodeKeyChanging(value);
					this.SendPropertyChanging();
					this._ARH_CodeKey = value;
					this.SendPropertyChanged("ARH_CodeKey");
					this.OnARH_CodeKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ArhiveDocument_ArhiveDocument", Storage="_Chield", ThisKey="ARH_Id", OtherKey="ARH_ARHID")]
		public EntitySet<ArhiveDocument> Chield
		{
			get
			{
				return this._Chield;
			}
			set
			{
				this._Chield.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ArhiveDocument_LTArh_History", Storage="_HistoryChield", ThisKey="ARH_Id", OtherKey="LTARH_CodeId")]
		public EntitySet<LTArh_History> HistoryChield
		{
			get
			{
				return this._HistoryChield;
			}
			set
			{
				this._HistoryChield.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ArhiveDocument_LTArh_History1", Storage="_HistoryParent", ThisKey="ARH_Id", OtherKey="LTARH_ParentCodeId")]
		public EntitySet<LTArh_History> HistoryParent
		{
			get
			{
				return this._HistoryParent;
			}
			set
			{
				this._HistoryParent.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ArhiveDocument_ArhiveDocument", Storage="_Parent", ThisKey="ARH_ARHID", OtherKey="ARH_Id", IsForeignKey=true)]
		public ArhiveDocument Parent
		{
			get
			{
				return this._Parent.Entity;
			}
			set
			{
				ArhiveDocument previousValue = this._Parent.Entity;
				if (((previousValue != value) 
							|| (this._Parent.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Parent.Entity = null;
						previousValue.Chield.Remove(this);
					}
					this._Parent.Entity = value;
					if ((value != null))
					{
						value.Chield.Add(this);
						this._ARH_ARHID = value.ARH_Id;
					}
					else
					{
						this._ARH_ARHID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Parent");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DocumentType_ArhiveDocument", Storage="_DocumentType", ThisKey="ARH_ARDTKey", OtherKey="ARDT_Id", IsForeignKey=true)]
		public DocumentType DocumentType
		{
			get
			{
				return this._DocumentType.Entity;
			}
			set
			{
				if ((this._DocumentType.Entity != value))
				{
					this.SendPropertyChanging();
					this._DocumentType.Entity = value;
					this.SendPropertyChanged("DocumentType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Chield(ArhiveDocument entity)
		{
			this.SendPropertyChanging();
			entity.Parent = this;
		}
		
		private void detach_Chield(ArhiveDocument entity)
		{
			this.SendPropertyChanging();
			entity.Parent = null;
		}
		
		private void attach_HistoryChield(LTArh_History entity)
		{
			this.SendPropertyChanging();
			entity.ArhiveDocument = this;
		}
		
		private void detach_HistoryChield(LTArh_History entity)
		{
			this.SendPropertyChanging();
			entity.ArhiveDocument = null;
		}
		
		private void attach_HistoryParent(LTArh_History entity)
		{
			this.SendPropertyChanging();
			entity.ArhiveDocument1 = this;
		}
		
		private void detach_HistoryParent(LTArh_History entity)
		{
			this.SendPropertyChanging();
			entity.ArhiveDocument1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class dict_Document : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Number;
		
		private int _Id;
		
		private System.Nullable<int> _PartnerKey;
		
		private string _Info;
		
		private System.DateTime _CreateDate;
		
		private EntityRef<tbl_Partner> _tbl_Partner;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNumberChanging(string value);
    partial void OnNumberChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPartnerKeyChanging(System.Nullable<int> value);
    partial void OnPartnerKeyChanged();
    partial void OnInfoChanging(string value);
    partial void OnInfoChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    #endregion
		
		public dict_Document()
		{
			this._tbl_Partner = default(EntityRef<tbl_Partner>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", CanBeNull=false)]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartnerKey")]
		public System.Nullable<int> PartnerKey
		{
			get
			{
				return this._PartnerKey;
			}
			set
			{
				if ((this._PartnerKey != value))
				{
					if (this._tbl_Partner.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPartnerKeyChanging(value);
					this.SendPropertyChanging();
					this._PartnerKey = value;
					this.SendPropertyChanged("PartnerKey");
					this.OnPartnerKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Info", CanBeNull=false)]
		public string Info
		{
			get
			{
				return this._Info;
			}
			set
			{
				if ((this._Info != value))
				{
					this.OnInfoChanging(value);
					this.SendPropertyChanging();
					this._Info = value;
					this.SendPropertyChanged("Info");
					this.OnInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Partner_dict_Document", Storage="_tbl_Partner", ThisKey="PartnerKey", OtherKey="PR_KEY", IsForeignKey=true)]
		public tbl_Partner tbl_Partner
		{
			get
			{
				return this._tbl_Partner.Entity;
			}
			set
			{
				tbl_Partner previousValue = this._tbl_Partner.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Partner.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Partner.Entity = null;
						previousValue.dict_Documents.Remove(this);
					}
					this._tbl_Partner.Entity = value;
					if ((value != null))
					{
						value.dict_Documents.Add(this);
						this._PartnerKey = value.PR_KEY;
					}
					else
					{
						this._PartnerKey = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Partner");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LTArh_DocType")]
	public partial class DocumentType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ARDT_Id;
		
		private bool _ARDT_CanHaveChildren;
		
		private bool _ARDT_IsRoot;
		
		private string _ARDT_Name;
		
		private string _ARDT_Code;
		
		private int _ARDT_GroupId;
		
		private System.Nullable<int> _ARDT_ParentGroupId;
		
		private string _ARDT_Sql;
		
		private EntitySet<DocumentType> _CheldDocType;
		
		private EntityRef<DocumentType> _ParentDocType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnARDT_IdChanging(int value);
    partial void OnARDT_IdChanged();
    partial void OnARDT_CanHaveChildrenChanging(bool value);
    partial void OnARDT_CanHaveChildrenChanged();
    partial void OnARDT_IsRootChanging(bool value);
    partial void OnARDT_IsRootChanged();
    partial void OnARDT_NameChanging(string value);
    partial void OnARDT_NameChanged();
    partial void OnARDT_CodeChanging(string value);
    partial void OnARDT_CodeChanged();
    partial void OnARDT_GroupIdChanging(int value);
    partial void OnARDT_GroupIdChanged();
    partial void OnARDT_ParentGroupIdChanging(System.Nullable<int> value);
    partial void OnARDT_ParentGroupIdChanged();
    partial void OnARDT_SqlChanging(string value);
    partial void OnARDT_SqlChanged();
    #endregion
		
		public DocumentType()
		{
			this._CheldDocType = new EntitySet<DocumentType>(new Action<DocumentType>(this.attach_CheldDocType), new Action<DocumentType>(this.detach_CheldDocType));
			this._ParentDocType = default(EntityRef<DocumentType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARDT_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ARDT_Id
		{
			get
			{
				return this._ARDT_Id;
			}
			set
			{
				if ((this._ARDT_Id != value))
				{
					this.OnARDT_IdChanging(value);
					this.SendPropertyChanging();
					this._ARDT_Id = value;
					this.SendPropertyChanged("ARDT_Id");
					this.OnARDT_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARDT_CanHaveChildren", DbType="Bit NOT NULL")]
		public bool ARDT_CanHaveChildren
		{
			get
			{
				return this._ARDT_CanHaveChildren;
			}
			set
			{
				if ((this._ARDT_CanHaveChildren != value))
				{
					this.OnARDT_CanHaveChildrenChanging(value);
					this.SendPropertyChanging();
					this._ARDT_CanHaveChildren = value;
					this.SendPropertyChanged("ARDT_CanHaveChildren");
					this.OnARDT_CanHaveChildrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARDT_IsRoot", DbType="Bit NOT NULL")]
		public bool ARDT_IsRoot
		{
			get
			{
				return this._ARDT_IsRoot;
			}
			set
			{
				if ((this._ARDT_IsRoot != value))
				{
					this.OnARDT_IsRootChanging(value);
					this.SendPropertyChanging();
					this._ARDT_IsRoot = value;
					this.SendPropertyChanged("ARDT_IsRoot");
					this.OnARDT_IsRootChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARDT_Name", DbType="VarChar(MAX)")]
		public string ARDT_Name
		{
			get
			{
				return this._ARDT_Name;
			}
			set
			{
				if ((this._ARDT_Name != value))
				{
					this.OnARDT_NameChanging(value);
					this.SendPropertyChanging();
					this._ARDT_Name = value;
					this.SendPropertyChanged("ARDT_Name");
					this.OnARDT_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARDT_Code", DbType="VarChar(3)")]
		public string ARDT_Code
		{
			get
			{
				return this._ARDT_Code;
			}
			set
			{
				if ((this._ARDT_Code != value))
				{
					this.OnARDT_CodeChanging(value);
					this.SendPropertyChanging();
					this._ARDT_Code = value;
					this.SendPropertyChanged("ARDT_Code");
					this.OnARDT_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARDT_GroupId", DbType="Int NOT NULL")]
		public int ARDT_GroupId
		{
			get
			{
				return this._ARDT_GroupId;
			}
			set
			{
				if ((this._ARDT_GroupId != value))
				{
					this.OnARDT_GroupIdChanging(value);
					this.SendPropertyChanging();
					this._ARDT_GroupId = value;
					this.SendPropertyChanged("ARDT_GroupId");
					this.OnARDT_GroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARDT_ParentGroupId", DbType="Int")]
		public System.Nullable<int> ARDT_ParentGroupId
		{
			get
			{
				return this._ARDT_ParentGroupId;
			}
			set
			{
				if ((this._ARDT_ParentGroupId != value))
				{
					if (this._ParentDocType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnARDT_ParentGroupIdChanging(value);
					this.SendPropertyChanging();
					this._ARDT_ParentGroupId = value;
					this.SendPropertyChanged("ARDT_ParentGroupId");
					this.OnARDT_ParentGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARDT_Sql", DbType="NVarChar(MAX)")]
		public string ARDT_Sql
		{
			get
			{
				return this._ARDT_Sql;
			}
			set
			{
				if ((this._ARDT_Sql != value))
				{
					this.OnARDT_SqlChanging(value);
					this.SendPropertyChanging();
					this._ARDT_Sql = value;
					this.SendPropertyChanged("ARDT_Sql");
					this.OnARDT_SqlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DocumentType_DocumentType", Storage="_CheldDocType", ThisKey="ARDT_GroupId", OtherKey="ARDT_ParentGroupId")]
		public EntitySet<DocumentType> CheldDocType
		{
			get
			{
				return this._CheldDocType;
			}
			set
			{
				this._CheldDocType.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DocumentType_DocumentType", Storage="_ParentDocType", ThisKey="ARDT_ParentGroupId", OtherKey="ARDT_GroupId", IsForeignKey=true)]
		public DocumentType ParentDocType
		{
			get
			{
				return this._ParentDocType.Entity;
			}
			set
			{
				DocumentType previousValue = this._ParentDocType.Entity;
				if (((previousValue != value) 
							|| (this._ParentDocType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ParentDocType.Entity = null;
						previousValue.CheldDocType.Remove(this);
					}
					this._ParentDocType.Entity = value;
					if ((value != null))
					{
						value.CheldDocType.Add(this);
						this._ARDT_ParentGroupId = value.ARDT_GroupId;
					}
					else
					{
						this._ARDT_ParentGroupId = default(Nullable<int>);
					}
					this.SendPropertyChanged("ParentDocType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CheldDocType(DocumentType entity)
		{
			this.SendPropertyChanging();
			entity.ParentDocType = this;
		}
		
		private void detach_CheldDocType(DocumentType entity)
		{
			this.SendPropertyChanging();
			entity.ParentDocType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LTArh_History")]
	public partial class LTArh_History : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LTARH_Id;
		
		private System.DateTime _LTARH_Date;
		
		private string _LTARH_Mod;
		
		private string _LTARH_UserName;
		
		private int _LTARH_CodeId;
		
		private string _LTARH_Comment;
		
		private System.Nullable<int> _LTARH_ParentCodeId;
		
		private EntityRef<ArhiveDocument> _ArhiveDocument;
		
		private EntityRef<ArhiveDocument> _ArhiveDocument1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLTARH_IdChanging(int value);
    partial void OnLTARH_IdChanged();
    partial void OnLTARH_DateChanging(System.DateTime value);
    partial void OnLTARH_DateChanged();
    partial void OnLTARH_ModChanging(string value);
    partial void OnLTARH_ModChanged();
    partial void OnLTARH_UserNameChanging(string value);
    partial void OnLTARH_UserNameChanged();
    partial void OnLTARH_CodeIdChanging(int value);
    partial void OnLTARH_CodeIdChanged();
    partial void OnLTARH_CommentChanging(string value);
    partial void OnLTARH_CommentChanged();
    partial void OnLTARH_ParentCodeIdChanging(System.Nullable<int> value);
    partial void OnLTARH_ParentCodeIdChanged();
    #endregion
		
		public LTArh_History()
		{
			this._ArhiveDocument = default(EntityRef<ArhiveDocument>);
			this._ArhiveDocument1 = default(EntityRef<ArhiveDocument>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LTARH_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LTARH_Id
		{
			get
			{
				return this._LTARH_Id;
			}
			set
			{
				if ((this._LTARH_Id != value))
				{
					this.OnLTARH_IdChanging(value);
					this.SendPropertyChanging();
					this._LTARH_Id = value;
					this.SendPropertyChanged("LTARH_Id");
					this.OnLTARH_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LTARH_Date", DbType="DateTime NOT NULL")]
		public System.DateTime LTARH_Date
		{
			get
			{
				return this._LTARH_Date;
			}
			set
			{
				if ((this._LTARH_Date != value))
				{
					this.OnLTARH_DateChanging(value);
					this.SendPropertyChanging();
					this._LTARH_Date = value;
					this.SendPropertyChanged("LTARH_Date");
					this.OnLTARH_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LTARH_Mod", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string LTARH_Mod
		{
			get
			{
				return this._LTARH_Mod;
			}
			set
			{
				if ((this._LTARH_Mod != value))
				{
					this.OnLTARH_ModChanging(value);
					this.SendPropertyChanging();
					this._LTARH_Mod = value;
					this.SendPropertyChanged("LTARH_Mod");
					this.OnLTARH_ModChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LTARH_UserName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string LTARH_UserName
		{
			get
			{
				return this._LTARH_UserName;
			}
			set
			{
				if ((this._LTARH_UserName != value))
				{
					this.OnLTARH_UserNameChanging(value);
					this.SendPropertyChanging();
					this._LTARH_UserName = value;
					this.SendPropertyChanged("LTARH_UserName");
					this.OnLTARH_UserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LTARH_CodeId", DbType="Int NOT NULL")]
		public int LTARH_CodeId
		{
			get
			{
				return this._LTARH_CodeId;
			}
			set
			{
				if ((this._LTARH_CodeId != value))
				{
					if (this._ArhiveDocument.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLTARH_CodeIdChanging(value);
					this.SendPropertyChanging();
					this._LTARH_CodeId = value;
					this.SendPropertyChanged("LTARH_CodeId");
					this.OnLTARH_CodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LTARH_Comment", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string LTARH_Comment
		{
			get
			{
				return this._LTARH_Comment;
			}
			set
			{
				if ((this._LTARH_Comment != value))
				{
					this.OnLTARH_CommentChanging(value);
					this.SendPropertyChanging();
					this._LTARH_Comment = value;
					this.SendPropertyChanged("LTARH_Comment");
					this.OnLTARH_CommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LTARH_ParentCodeId", DbType="Int")]
		public System.Nullable<int> LTARH_ParentCodeId
		{
			get
			{
				return this._LTARH_ParentCodeId;
			}
			set
			{
				if ((this._LTARH_ParentCodeId != value))
				{
					if (this._ArhiveDocument1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLTARH_ParentCodeIdChanging(value);
					this.SendPropertyChanging();
					this._LTARH_ParentCodeId = value;
					this.SendPropertyChanged("LTARH_ParentCodeId");
					this.OnLTARH_ParentCodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ArhiveDocument_LTArh_History", Storage="_ArhiveDocument", ThisKey="LTARH_CodeId", OtherKey="ARH_Id", IsForeignKey=true)]
		public ArhiveDocument ArhiveDocument
		{
			get
			{
				return this._ArhiveDocument.Entity;
			}
			set
			{
				ArhiveDocument previousValue = this._ArhiveDocument.Entity;
				if (((previousValue != value) 
							|| (this._ArhiveDocument.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ArhiveDocument.Entity = null;
						previousValue.HistoryChield.Remove(this);
					}
					this._ArhiveDocument.Entity = value;
					if ((value != null))
					{
						value.HistoryChield.Add(this);
						this._LTARH_CodeId = value.ARH_Id;
					}
					else
					{
						this._LTARH_CodeId = default(int);
					}
					this.SendPropertyChanged("ArhiveDocument");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ArhiveDocument_LTArh_History1", Storage="_ArhiveDocument1", ThisKey="LTARH_ParentCodeId", OtherKey="ARH_Id", IsForeignKey=true)]
		public ArhiveDocument ArhiveDocument1
		{
			get
			{
				return this._ArhiveDocument1.Entity;
			}
			set
			{
				ArhiveDocument previousValue = this._ArhiveDocument1.Entity;
				if (((previousValue != value) 
							|| (this._ArhiveDocument1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ArhiveDocument1.Entity = null;
						previousValue.HistoryParent.Remove(this);
					}
					this._ArhiveDocument1.Entity = value;
					if ((value != null))
					{
						value.HistoryParent.Add(this);
						this._LTARH_ParentCodeId = value.ARH_Id;
					}
					else
					{
						this._LTARH_ParentCodeId = default(Nullable<int>);
					}
					this.SendPropertyChanged("ArhiveDocument1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
