//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace rep259921.Megatec_Web {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ArtWebServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback WebCreateDogovorOperationCompleted;
        
        private System.Threading.SendOrPostCallback WebCreateTuristOperationCompleted;
        
        private System.Threading.SendOrPostCallback WebCreateDogListOperationCompleted;
        
        private System.Threading.SendOrPostCallback WebRecalculateDogovorOperationCompleted;
        
        private System.Threading.SendOrPostCallback WebCreateMFPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback WebInsertDictionaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback WebCreateCostOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::rep259921.Properties.Settings.Default.rep259921_ru_lantatur_lanta_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ArtWebServiceCompletedEventHandler ArtWebServiceCompleted;
        
        /// <remarks/>
        public event WebCreateDogovorCompletedEventHandler WebCreateDogovorCompleted;
        
        /// <remarks/>
        public event WebCreateTuristCompletedEventHandler WebCreateTuristCompleted;
        
        /// <remarks/>
        public event WebCreateDogListCompletedEventHandler WebCreateDogListCompleted;
        
        /// <remarks/>
        public event WebRecalculateDogovorCompletedEventHandler WebRecalculateDogovorCompleted;
        
        /// <remarks/>
        public event WebCreateMFPaymentCompletedEventHandler WebCreateMFPaymentCompleted;
        
        /// <remarks/>
        public event WebInsertDictionaryCompletedEventHandler WebInsertDictionaryCompleted;
        
        /// <remarks/>
        public event WebCreateCostCompletedEventHandler WebCreateCostCompleted;
        
        /// <remarks/>
        public event GetInfoCompletedEventHandler GetInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ArtWebService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ArtWebService() {
            object[] results = this.Invoke("ArtWebService", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ArtWebServiceAsync() {
            this.ArtWebServiceAsync(null);
        }
        
        /// <remarks/>
        public void ArtWebServiceAsync(object userState) {
            if ((this.ArtWebServiceOperationCompleted == null)) {
                this.ArtWebServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnArtWebServiceOperationCompleted);
            }
            this.InvokeAsync("ArtWebService", new object[0], this.ArtWebServiceOperationCompleted, userState);
        }
        
        private void OnArtWebServiceOperationCompleted(object arg) {
            if ((this.ArtWebServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ArtWebServiceCompleted(this, new ArtWebServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebCreateDogovor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageInfos WebCreateDogovor(string sDateBeg, int nTrKey, string sCnCode, int nCtKey, int nCtDepartureKey, string sRate, int nMen, int nPartnerKey, int nDays, float nPrice, string sDgCodePartner, int nBTKey, int nCnKey) {
            object[] results = this.Invoke("WebCreateDogovor", new object[] {
                        sDateBeg,
                        nTrKey,
                        sCnCode,
                        nCtKey,
                        nCtDepartureKey,
                        sRate,
                        nMen,
                        nPartnerKey,
                        nDays,
                        nPrice,
                        sDgCodePartner,
                        nBTKey,
                        nCnKey});
            return ((MessageInfos)(results[0]));
        }
        
        /// <remarks/>
        public void WebCreateDogovorAsync(string sDateBeg, int nTrKey, string sCnCode, int nCtKey, int nCtDepartureKey, string sRate, int nMen, int nPartnerKey, int nDays, float nPrice, string sDgCodePartner, int nBTKey, int nCnKey) {
            this.WebCreateDogovorAsync(sDateBeg, nTrKey, sCnCode, nCtKey, nCtDepartureKey, sRate, nMen, nPartnerKey, nDays, nPrice, sDgCodePartner, nBTKey, nCnKey, null);
        }
        
        /// <remarks/>
        public void WebCreateDogovorAsync(string sDateBeg, int nTrKey, string sCnCode, int nCtKey, int nCtDepartureKey, string sRate, int nMen, int nPartnerKey, int nDays, float nPrice, string sDgCodePartner, int nBTKey, int nCnKey, object userState) {
            if ((this.WebCreateDogovorOperationCompleted == null)) {
                this.WebCreateDogovorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWebCreateDogovorOperationCompleted);
            }
            this.InvokeAsync("WebCreateDogovor", new object[] {
                        sDateBeg,
                        nTrKey,
                        sCnCode,
                        nCtKey,
                        nCtDepartureKey,
                        sRate,
                        nMen,
                        nPartnerKey,
                        nDays,
                        nPrice,
                        sDgCodePartner,
                        nBTKey,
                        nCnKey}, this.WebCreateDogovorOperationCompleted, userState);
        }
        
        private void OnWebCreateDogovorOperationCompleted(object arg) {
            if ((this.WebCreateDogovorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WebCreateDogovorCompleted(this, new WebCreateDogovorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebCreateTurist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageInfos WebCreateTurist(int nSex, string sFName, string sName, string sDR, string sNom, string sPasport, string sDatePasportEnd, string sDgCode) {
            object[] results = this.Invoke("WebCreateTurist", new object[] {
                        nSex,
                        sFName,
                        sName,
                        sDR,
                        sNom,
                        sPasport,
                        sDatePasportEnd,
                        sDgCode});
            return ((MessageInfos)(results[0]));
        }
        
        /// <remarks/>
        public void WebCreateTuristAsync(int nSex, string sFName, string sName, string sDR, string sNom, string sPasport, string sDatePasportEnd, string sDgCode) {
            this.WebCreateTuristAsync(nSex, sFName, sName, sDR, sNom, sPasport, sDatePasportEnd, sDgCode, null);
        }
        
        /// <remarks/>
        public void WebCreateTuristAsync(int nSex, string sFName, string sName, string sDR, string sNom, string sPasport, string sDatePasportEnd, string sDgCode, object userState) {
            if ((this.WebCreateTuristOperationCompleted == null)) {
                this.WebCreateTuristOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWebCreateTuristOperationCompleted);
            }
            this.InvokeAsync("WebCreateTurist", new object[] {
                        nSex,
                        sFName,
                        sName,
                        sDR,
                        sNom,
                        sPasport,
                        sDatePasportEnd,
                        sDgCode}, this.WebCreateTuristOperationCompleted, userState);
        }
        
        private void OnWebCreateTuristOperationCompleted(object arg) {
            if ((this.WebCreateTuristCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WebCreateTuristCompleted(this, new WebCreateTuristCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebCreateDogList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageInfos WebCreateDogList(string sDgCode, int nDay, int nSvKey, int nCode, int nSubCode1, int nSubCode2, int nPkKey, int nPrKey, int nMen, int nDays, int nCtKey, float nNetto, float nBrutto, string sNameService, string sTuristKeys) {
            object[] results = this.Invoke("WebCreateDogList", new object[] {
                        sDgCode,
                        nDay,
                        nSvKey,
                        nCode,
                        nSubCode1,
                        nSubCode2,
                        nPkKey,
                        nPrKey,
                        nMen,
                        nDays,
                        nCtKey,
                        nNetto,
                        nBrutto,
                        sNameService,
                        sTuristKeys});
            return ((MessageInfos)(results[0]));
        }
        
        /// <remarks/>
        public void WebCreateDogListAsync(string sDgCode, int nDay, int nSvKey, int nCode, int nSubCode1, int nSubCode2, int nPkKey, int nPrKey, int nMen, int nDays, int nCtKey, float nNetto, float nBrutto, string sNameService, string sTuristKeys) {
            this.WebCreateDogListAsync(sDgCode, nDay, nSvKey, nCode, nSubCode1, nSubCode2, nPkKey, nPrKey, nMen, nDays, nCtKey, nNetto, nBrutto, sNameService, sTuristKeys, null);
        }
        
        /// <remarks/>
        public void WebCreateDogListAsync(
                    string sDgCode, 
                    int nDay, 
                    int nSvKey, 
                    int nCode, 
                    int nSubCode1, 
                    int nSubCode2, 
                    int nPkKey, 
                    int nPrKey, 
                    int nMen, 
                    int nDays, 
                    int nCtKey, 
                    float nNetto, 
                    float nBrutto, 
                    string sNameService, 
                    string sTuristKeys, 
                    object userState) {
            if ((this.WebCreateDogListOperationCompleted == null)) {
                this.WebCreateDogListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWebCreateDogListOperationCompleted);
            }
            this.InvokeAsync("WebCreateDogList", new object[] {
                        sDgCode,
                        nDay,
                        nSvKey,
                        nCode,
                        nSubCode1,
                        nSubCode2,
                        nPkKey,
                        nPrKey,
                        nMen,
                        nDays,
                        nCtKey,
                        nNetto,
                        nBrutto,
                        sNameService,
                        sTuristKeys}, this.WebCreateDogListOperationCompleted, userState);
        }
        
        private void OnWebCreateDogListOperationCompleted(object arg) {
            if ((this.WebCreateDogListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WebCreateDogListCompleted(this, new WebCreateDogListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebRecalculateDogovor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageInfos WebRecalculateDogovor(string sDgCode) {
            object[] results = this.Invoke("WebRecalculateDogovor", new object[] {
                        sDgCode});
            return ((MessageInfos)(results[0]));
        }
        
        /// <remarks/>
        public void WebRecalculateDogovorAsync(string sDgCode) {
            this.WebRecalculateDogovorAsync(sDgCode, null);
        }
        
        /// <remarks/>
        public void WebRecalculateDogovorAsync(string sDgCode, object userState) {
            if ((this.WebRecalculateDogovorOperationCompleted == null)) {
                this.WebRecalculateDogovorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWebRecalculateDogovorOperationCompleted);
            }
            this.InvokeAsync("WebRecalculateDogovor", new object[] {
                        sDgCode}, this.WebRecalculateDogovorOperationCompleted, userState);
        }
        
        private void OnWebRecalculateDogovorOperationCompleted(object arg) {
            if ((this.WebRecalculateDogovorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WebRecalculateDogovorCompleted(this, new WebRecalculateDogovorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebCreateMFPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageInfos WebCreateMFPayment(string sDgCode, float fSumma) {
            object[] results = this.Invoke("WebCreateMFPayment", new object[] {
                        sDgCode,
                        fSumma});
            return ((MessageInfos)(results[0]));
        }
        
        /// <remarks/>
        public void WebCreateMFPaymentAsync(string sDgCode, float fSumma) {
            this.WebCreateMFPaymentAsync(sDgCode, fSumma, null);
        }
        
        /// <remarks/>
        public void WebCreateMFPaymentAsync(string sDgCode, float fSumma, object userState) {
            if ((this.WebCreateMFPaymentOperationCompleted == null)) {
                this.WebCreateMFPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWebCreateMFPaymentOperationCompleted);
            }
            this.InvokeAsync("WebCreateMFPayment", new object[] {
                        sDgCode,
                        fSumma}, this.WebCreateMFPaymentOperationCompleted, userState);
        }
        
        private void OnWebCreateMFPaymentOperationCompleted(object arg) {
            if ((this.WebCreateMFPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WebCreateMFPaymentCompleted(this, new WebCreateMFPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebInsertDictionary", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageInfos WebInsertDictionary(int nSvKey, string sNameRus, string sNameLat, int nCnKey, int nCtKey, int nDaysCountMin) {
            object[] results = this.Invoke("WebInsertDictionary", new object[] {
                        nSvKey,
                        sNameRus,
                        sNameLat,
                        nCnKey,
                        nCtKey,
                        nDaysCountMin});
            return ((MessageInfos)(results[0]));
        }
        
        /// <remarks/>
        public void WebInsertDictionaryAsync(int nSvKey, string sNameRus, string sNameLat, int nCnKey, int nCtKey, int nDaysCountMin) {
            this.WebInsertDictionaryAsync(nSvKey, sNameRus, sNameLat, nCnKey, nCtKey, nDaysCountMin, null);
        }
        
        /// <remarks/>
        public void WebInsertDictionaryAsync(int nSvKey, string sNameRus, string sNameLat, int nCnKey, int nCtKey, int nDaysCountMin, object userState) {
            if ((this.WebInsertDictionaryOperationCompleted == null)) {
                this.WebInsertDictionaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWebInsertDictionaryOperationCompleted);
            }
            this.InvokeAsync("WebInsertDictionary", new object[] {
                        nSvKey,
                        sNameRus,
                        sNameLat,
                        nCnKey,
                        nCtKey,
                        nDaysCountMin}, this.WebInsertDictionaryOperationCompleted, userState);
        }
        
        private void OnWebInsertDictionaryOperationCompleted(object arg) {
            if ((this.WebInsertDictionaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WebInsertDictionaryCompleted(this, new WebInsertDictionaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebCreateCost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageInfos WebCreateCost(int nSvKey, int nCode, int nSubCode1, int nSubCode2, int nPkKey, int nPrKey, int nNetto, int nBrutto, string sDateFrom, string sDateTo, string sPPDateFrom, string sPPDateTo, int nComiss, int nGroup, string sRate) {
            object[] results = this.Invoke("WebCreateCost", new object[] {
                        nSvKey,
                        nCode,
                        nSubCode1,
                        nSubCode2,
                        nPkKey,
                        nPrKey,
                        nNetto,
                        nBrutto,
                        sDateFrom,
                        sDateTo,
                        sPPDateFrom,
                        sPPDateTo,
                        nComiss,
                        nGroup,
                        sRate});
            return ((MessageInfos)(results[0]));
        }
        
        /// <remarks/>
        public void WebCreateCostAsync(int nSvKey, int nCode, int nSubCode1, int nSubCode2, int nPkKey, int nPrKey, int nNetto, int nBrutto, string sDateFrom, string sDateTo, string sPPDateFrom, string sPPDateTo, int nComiss, int nGroup, string sRate) {
            this.WebCreateCostAsync(nSvKey, nCode, nSubCode1, nSubCode2, nPkKey, nPrKey, nNetto, nBrutto, sDateFrom, sDateTo, sPPDateFrom, sPPDateTo, nComiss, nGroup, sRate, null);
        }
        
        /// <remarks/>
        public void WebCreateCostAsync(
                    int nSvKey, 
                    int nCode, 
                    int nSubCode1, 
                    int nSubCode2, 
                    int nPkKey, 
                    int nPrKey, 
                    int nNetto, 
                    int nBrutto, 
                    string sDateFrom, 
                    string sDateTo, 
                    string sPPDateFrom, 
                    string sPPDateTo, 
                    int nComiss, 
                    int nGroup, 
                    string sRate, 
                    object userState) {
            if ((this.WebCreateCostOperationCompleted == null)) {
                this.WebCreateCostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWebCreateCostOperationCompleted);
            }
            this.InvokeAsync("WebCreateCost", new object[] {
                        nSvKey,
                        nCode,
                        nSubCode1,
                        nSubCode2,
                        nPkKey,
                        nPrKey,
                        nNetto,
                        nBrutto,
                        sDateFrom,
                        sDateTo,
                        sPPDateFrom,
                        sPPDateTo,
                        nComiss,
                        nGroup,
                        sRate}, this.WebCreateCostOperationCompleted, userState);
        }
        
        private void OnWebCreateCostOperationCompleted(object arg) {
            if ((this.WebCreateCostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WebCreateCostCompleted(this, new WebCreateCostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TourInfo GetInfo(string sDgCode) {
            object[] results = this.Invoke("GetInfo", new object[] {
                        sDgCode});
            return ((TourInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoAsync(string sDgCode) {
            this.GetInfoAsync(sDgCode, null);
        }
        
        /// <remarks/>
        public void GetInfoAsync(string sDgCode, object userState) {
            if ((this.GetInfoOperationCompleted == null)) {
                this.GetInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoOperationCompleted);
            }
            this.InvokeAsync("GetInfo", new object[] {
                        sDgCode}, this.GetInfoOperationCompleted, userState);
        }
        
        private void OnGetInfoOperationCompleted(object arg) {
            if ((this.GetInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoCompleted(this, new GetInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageInfos {
        
        private MessageInfo[] allMessageInfoField;
        
        /// <remarks/>
        public MessageInfo[] AllMessageInfo {
            get {
                return this.allMessageInfoField;
            }
            set {
                this.allMessageInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageInfo {
        
        private int keyField;
        
        private int infoNumberField;
        
        private string infoField;
        
        private string dopInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int InfoNumber {
            get {
                return this.infoNumberField;
            }
            set {
                this.infoNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DopInfo {
            get {
                return this.dopInfoField;
            }
            set {
                this.dopInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AllTourInfo {
        
        private string statusField;
        
        private string priceField;
        
        private string payedField;
        
        private string rateDogovorField;
        
        private string rate1Field;
        
        private string rate2Field;
        
        private string realCourseField;
        
        private string inCourseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Payed {
            get {
                return this.payedField;
            }
            set {
                this.payedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RateDogovor {
            get {
                return this.rateDogovorField;
            }
            set {
                this.rateDogovorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Rate1 {
            get {
                return this.rate1Field;
            }
            set {
                this.rate1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Rate2 {
            get {
                return this.rate2Field;
            }
            set {
                this.rate2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RealCourse {
            get {
                return this.realCourseField;
            }
            set {
                this.realCourseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InCourse {
            get {
                return this.inCourseField;
            }
            set {
                this.inCourseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TourInfo {
        
        private AllTourInfo[] allInfoField;
        
        /// <remarks/>
        public AllTourInfo[] AllInfo {
            get {
                return this.allInfoField;
            }
            set {
                this.allInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ArtWebServiceCompletedEventHandler(object sender, ArtWebServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArtWebServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ArtWebServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WebCreateDogovorCompletedEventHandler(object sender, WebCreateDogovorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WebCreateDogovorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WebCreateDogovorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageInfos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageInfos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WebCreateTuristCompletedEventHandler(object sender, WebCreateTuristCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WebCreateTuristCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WebCreateTuristCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageInfos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageInfos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WebCreateDogListCompletedEventHandler(object sender, WebCreateDogListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WebCreateDogListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WebCreateDogListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageInfos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageInfos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WebRecalculateDogovorCompletedEventHandler(object sender, WebRecalculateDogovorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WebRecalculateDogovorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WebRecalculateDogovorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageInfos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageInfos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WebCreateMFPaymentCompletedEventHandler(object sender, WebCreateMFPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WebCreateMFPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WebCreateMFPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageInfos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageInfos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WebInsertDictionaryCompletedEventHandler(object sender, WebInsertDictionaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WebInsertDictionaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WebInsertDictionaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageInfos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageInfos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WebCreateCostCompletedEventHandler(object sender, WebCreateCostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WebCreateCostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WebCreateCostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageInfos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageInfos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetInfoCompletedEventHandler(object sender, GetInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TourInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TourInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591