<?xml version="1.0" encoding="utf-8"?>
<Database Name="lanta" Class="ReportingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.10.4;Initial Catalog=lanta;Persist Security Info=True;User ID=sa" SettingsObjectName="rep259916.Properties.Settings" SettingsPropertyName="lantaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.COUNTRY" Member="COUNTRies">
    <Type Name="COUNTRY">
      <Column Name="CN_KEY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CN_NAME" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="CN_NAMELAT" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="CN_FRAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CN_WEB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CN_WEBIMAGE" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="CN_WEBHTTP" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="CN_CODE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="CN_AnkLang" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CN_StdKey" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="CN_Updatedate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CN_SMALLDESC" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="CN_COKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CN_NameAC" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="CN_Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CN_CitizenName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CN_CitizenNameLat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CN_INNName" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CN_CheckINN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CN_PassportMinDur" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="COUNTRY_tbl_Dogovor" Member="tbl_Dogovors" ThisKey="CN_KEY" OtherKey="DG_CNKEY" Type="tbl_Dogovor" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Dogovor" Member="tbl_Dogovors">
    <Type Name="tbl_Dogovor">
      <Column Name="DG_CODE" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DG_TURDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DG_TRKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_CNKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_CTKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_NMEN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DG_PRICE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DG_PAYED" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_NDAY" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DG_MAINMEN" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="DG_MAINMENPHONE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DG_MAINMENADRESS" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="DG_MAINMENPASPORT" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="DG_PARTNERKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_OPERATOR" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="DG_PRINTDOGOVOR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DG_PRINTVAUCHER" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DG_TYPECOUNT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DG_DISCOUNT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_DISCOUNTSUM" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DG_CREATOR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_OWNER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_SOR_CODE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_CRDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DG_RATE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="DG_ADVERTISE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_LOCKED" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DG_CAUSEDISC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_VISADATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DG_PPAYMENTDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DG_PAYMENTDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DG_TURPUTDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DG_DOCUMENT" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DG_TURPUTPLACE" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="DG_PROCENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_OLDTOURDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="DG_TurDateBfrAnnul" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DG_ARKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_Key" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DG_CodePartner" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DG_FilialKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_IsOutDoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_AgentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_DISCSUMBFRANN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_PRICEBFRANN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_TRANSFERRED" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DG_NOTES" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DG_DCRCLIENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_DCRPAYMENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_ISMAKEDISCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_RazmerP" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_LEADDEPARTMENT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_MAINMENEMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DG_MAINMENCOMMENT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DG_DUPUSERKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_BTKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_INVOICECOST" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="DG_ConfirmedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DG_PRTDOGKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_CTDepartureKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_SalePrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_SaleDiscount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_PDTType" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DG_NATIONALCURRENCYPRICE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_NATIONALCURRENCYDISCOUNTSUM" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_DAKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_NATIONALCURRENCYPAYED" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="tbl_Dogovor_tbl_DogovorList" Member="tbl_DogovorLists" ThisKey="DG_CODE" OtherKey="DL_DGCOD" Type="tbl_DogovorList" />
      <Association Name="tbl_Dogovor_Lanta_NNT_Name" Member="Lanta_NNT_Names" ThisKey="DG_TRKEY" OtherKey="IDTR_Key" Type="Lanta_NNT_Name" />
      <Association Name="tbl_Partner_tbl_Dogovor" Member="tbl_Partner" ThisKey="DG_PARTNERKEY" OtherKey="PR_KEY" Type="tbl_Partner" IsForeignKey="true" />
      <Association Name="COUNTRY_tbl_Dogovor" Member="COUNTRY" ThisKey="DG_CNKEY" OtherKey="CN_KEY" Type="COUNTRY" IsForeignKey="true" />
      <Association Name="tbl_TurList_tbl_Dogovor" Member="tbl_TurList" ThisKey="DG_TRKEY" OtherKey="TL_KEY" Type="tbl_TurList" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Partners" Member="tbl_Partners">
    <Type Name="tbl_Partner">
      <Column Name="PR_KEY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PR_FULLNAME" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="PR_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PR_NAMEENG" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="PR_BOSSNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PR_BOSS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_MALE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PR_MAINMEN" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="PR_MAINMENPHONE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_DISCOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PR_ACCOUNT" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="PR_ADRESS" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="PR_PHONES" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="PR_FAX" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PR_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_CTKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PR_CREATOR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PR_AGENTDOGOVOR" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="PR_TYPE" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PR_CITY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_WEBAGENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PR_AGENTDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PR_AGENTDOGOVOR2" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="PR_AGENTDATE2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PR_FAX1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PR_REMARK" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="PR_CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PR_UPDATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PR_ART" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PR_USERLAST" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PR_COD" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="LastUser" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="pr_IsActive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PR_Filial" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PR_DateLastContact" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PR_ExchangePwd" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PR_GUID" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PR_ExchangeData" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" />
      <Column Name="MaskedFax" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="PR_DOGOVORTYPE" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PR_ICQ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_GDS_PREFIX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_GDS_SUFFIX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_OWNER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PR_IPAddress" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="PR_Deleted" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PR_LICENSENUMBER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_ADDITIONALINFO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_LEGALADDRESS" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="PR_INN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_FOREIGNACCINFO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PR_KPP" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PR_CODEOKONH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PR_CODEOKPO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PR_HOMEPAGE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PR_PGKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PR_BLOCKEDFORANNUL" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PR_POSTINDEX" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="PR_LEGALPOSTINDEX" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="PR_RegisterSeries" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PR_RegisterNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_Http" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="pr_description" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="PR_WebServiceUrl" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="tbl_Partner_tbl_Dogovor" Member="tbl_Dogovors" ThisKey="PR_KEY" OtherKey="DG_PARTNERKEY" Type="tbl_Dogovor" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_DogovorList" Member="tbl_DogovorLists">
    <Type Name="tbl_DogovorList">
      <Column Name="DL_DGCOD" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DL_TURDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DL_KEY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DL_PAKETKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_TRKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DL_SVKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DL_NAME" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="DL_DAY" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DL_CODE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DL_SUBCODE1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_SUBCODE2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_NMEN" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DL_NDAYS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DL_CNKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_CTKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_PARTNERKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_COST" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DL_REALNETTO" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DL_BRUTTO" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DL_PAYED" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DL_WAIT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DL_WARNING" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_TIMEBEG" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DL_CONTROL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DL_CREATOR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DL_OWNER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DL_ATTRIBUTE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_ISPAYED" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DL_DATEBEG" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DL_DATEEND" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DL_DISCOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DL_QUOTEKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_AGENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="DL_AgentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_Comment" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="DL_Reserved" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_DGKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_FORMULANETTO" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="DL_FORMULABRUTTO" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="DL_BLOCKED" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DL_NameLat" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="DL_PRTDOGKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_TAXZONEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_Long" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DL_IsDeleted" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DL_SalePrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DL_SaleDiscount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DL_FormulaDiscount" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Association Name="tbl_Dogovor_tbl_DogovorList" Member="tbl_Dogovor" ThisKey="DL_DGCOD" OtherKey="DG_CODE" Type="tbl_Dogovor" IsForeignKey="true" />
      <Association Name="HotelDictionary_tbl_DogovorList" Member="HotelDictionary" ThisKey="DL_CODE" OtherKey="HD_KEY" Type="HotelDictionary" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lanta_NNT_Name" Member="Lanta_NNT_Names">
    <Type Name="Lanta_NNT_Name">
      <Column Name="IDNewNameTour" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NewNameTour" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IDTourInMaster" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDCountryInMaster" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OnlyCatalog" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OnlySite" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OnlyMoscow" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OnlyRegions" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrintOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDTR_Key" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LongNewName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IDCity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddressHTTP" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Categ" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateSP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="BaseIDTR_Key" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUserKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUserDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActionSP" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SP_SendOn_Agency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SP_HitsOfDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lucky" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LuckyBaseIDTR_Key" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionRow" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="release" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="release2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_Dogovor_Lanta_NNT_Name" Member="tbl_Dogovor" ThisKey="IDTR_Key" OtherKey="DG_TRKEY" Type="tbl_Dogovor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HotelDictionary" Member="HotelDictionaries">
    <Type Name="HotelDictionary">
      <Column Name="HD_CNKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_CTKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_KEY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HD_NAME" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="HD_STARS" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="HD_ADDRESS" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="HD_PHONE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_FAX" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HD_SITE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="HD_DESCRIPT" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="HD_PERSONNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_PERSONAPP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_CODE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HD_RSKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HD_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HD_HTTP" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="HD_DESCROOM" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="HD_DESCMEAL" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="HD_DESCSERVICE" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="HD_DESCSPORT" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="HD_DESCEXCUR" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="HD_DESCHEALTH" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="HD_DISTANCE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HD_WEB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HD_DESCRAZVL" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="HD_WEBIMAGE" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_WEBIMAGE1" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_WEBIMAGE2" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_WEBIMAGE3" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_WEBIMAGE4" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_WEBIMAGE5" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_WEBIMAGE6" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_WEBIMAGE7" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_WEBIMAGE8" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_REMARK" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_REMARK1" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_REMARK2" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_REMARK3" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_REMARK4" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_REMARK5" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_REMARK6" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_REMARK7" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="HD_REMARK8" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="HD_StdKey" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="HD_UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_UNICODE" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="HD_Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HD_IsCruise" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_COHId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HD_NAMELAT" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="HD_PayHour1" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="HD_PayHour2" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="HD_Travel" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="HD_PayHourNote" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="HD_PayHour" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="HotelDictionary_tbl_DogovorList" Member="tbl_DogovorLists" ThisKey="HD_KEY" OtherKey="DL_CODE" Type="tbl_DogovorList" />
    </Type>
  </Table>
  <Table Name="dbo.TipTur" Member="TipTurs">
    <Type Name="TipTur">
      <Column Name="TP_KEY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TP_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TP_TPKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TP_NameLat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="TipTur_TipTur" Member="TipTurs" ThisKey="TP_KEY" OtherKey="TP_TPKEY" Type="TipTur" />
      <Association Name="TipTur_tbl_TurList" Member="tbl_TurLists" ThisKey="TP_KEY" OtherKey="TL_TIP" Type="tbl_TurList" />
      <Association Name="TipTur_TipTur" Member="TipTur1" ThisKey="TP_TPKEY" OtherKey="TP_KEY" Type="TipTur" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TurList" Member="tbl_TurLists">
    <Type Name="tbl_TurList">
      <Column Name="TL_CNKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TL_KEY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TL_NAME" Type="System.String" DbType="VarChar(160) NOT NULL" CanBeNull="false" />
      <Column Name="TL_TYPECOUNT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TL_PROFIT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TL_PRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TL_NDAY" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="TL_CREATOR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TL_DESCRIPTION" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="TL_REMARK" Type="System.String" DbType="VarChar(240)" CanBeNull="true" />
      <Column Name="TL_RATE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="TL_WEBHTTP" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="TL_NAMEWEB" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="TL_WEB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TL_DATEDOC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TL_DATEDOCVISA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TL_TIP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TL_WEBCOST" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="TL_EMAIL" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TL_datequotes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TL_datepayed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TL_DfltPaymentPcnt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TL_Margin" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="TL_MarginType" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TL_PRKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TL_OpKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TL_AdvDesc" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="TL_AttDesc" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="TL_FullDesc" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="TL_DopDesc" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="TL_PriceHttp" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="TL_RGKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TL_SmallDesc" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="TL_ISDISABLED" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="TL_Deleted" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="TL_LEADDEPARTMENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TL_NameLat" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="TL_CTDepartureKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tl_webHttpPers" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="TL_Attribute" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tbl_TurList_tbl_Dogovor" Member="tbl_Dogovors" ThisKey="TL_KEY" OtherKey="DG_TRKEY" Type="tbl_Dogovor" />
      <Association Name="TipTur_tbl_TurList" Member="TipTur" ThisKey="TL_TIP" OtherKey="TP_KEY" Type="TipTur" IsForeignKey="true" />
    </Type>
  </Table>
</Database>