<?xml version="1.0" encoding="utf-8"?><Database Name="lanta" Class="sqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.10.4;Initial Catalog=lanta;Persist Security Info=True;User ID=sa" SettingsObjectName="Rep22341.Properties.Settings" SettingsPropertyName="lantaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Dogovor" Member="tbl_Dogovors">
    <Type Name="tbl_Dogovor">
      <Column Name="DG_CODE" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DG_TURDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DG_TRKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_CNKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_CTKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_NMEN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DG_PRICE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DG_PAYED" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_NDAY" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DG_MAINMEN" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="DG_MAINMENPHONE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DG_MAINMENADRESS" Type="System.String" DbType="VarChar(320)" CanBeNull="true" />
      <Column Name="DG_MAINMENPASPORT" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="DG_PARTNERKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_OPERATOR" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="DG_PRINTDOGOVOR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DG_PRINTVAUCHER" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DG_TYPECOUNT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DG_DISCOUNT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_DISCOUNTSUM" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DG_CREATOR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_OWNER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_SOR_CODE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_CRDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DG_RATE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="DG_ADVERTISE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_LOCKED" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DG_CAUSEDISC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_VISADATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DG_PPAYMENTDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DG_PAYMENTDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DG_TURPUTDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DG_DOCUMENT" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DG_TURPUTPLACE" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="DG_PROCENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_OLDTOURDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="DG_TurDateBfrAnnul" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DG_ARKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_Key" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DG_CodePartner" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DG_FilialKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_IsOutDoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_AgentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_DISCSUMBFRANN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_PRICEBFRANN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_TRANSFERRED" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DG_NOTES" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DG_DCRCLIENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_DCRPAYMENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_ISMAKEDISCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_RazmerP" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_LEADDEPARTMENT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_MAINMENEMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DG_MAINMENCOMMENT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DG_DUPUSERKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_BTKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_INVOICECOST" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="DG_ConfirmedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DG_PRTDOGKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DG_CTDepartureKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_SalePrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_SaleDiscount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_PDTType" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DG_NATIONALCURRENCYPRICE" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_NATIONALCURRENCYDISCOUNTSUM" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DG_DAKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DG_NATIONALCURRENCYPAYED" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="tbl_Dogovor_tbl_DogovorList" Member="tbl_DogovorLists" ThisKey="DG_CODE" OtherKey="DL_DGCOD" Type="tbl_DogovorList" />
      <Association Name="tbl_Dogovor_tbl_Turist" Member="tbl_Turists" ThisKey="DG_CODE" OtherKey="TU_DGCOD" Type="tbl_Turist" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_DogovorList" Member="tbl_DogovorLists">
    <Type Name="tbl_DogovorList">
      <Column Name="DL_DGCOD" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DL_TURDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DL_KEY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DL_SVKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DL_NAME" Type="System.String" DbType="VarChar(255)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DL_DAY" Type="System.Int16" DbType="SmallInt" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DL_CODE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DL_SUBCODE1" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DL_SUBCODE2" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DL_NDAYS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DL_WAIT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DL_CONTROL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DL_ATTRIBUTE" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DL_PARTNERKEY" Type="System.Int32" DbType="int" CanBeNull="false" />
      <Association Name="tbl_DogovorList_TuristService" Member="TuristServices" ThisKey="DL_KEY" OtherKey="TU_DLKEY" Type="TuristService" />
      <Association Name="tbl_Dogovor_tbl_DogovorList" Member="tbl_Dogovor" ThisKey="DL_DGCOD" OtherKey="DG_CODE" Type="tbl_Dogovor" IsForeignKey="true" />
      <Association Name="Charter_tbl_DogovorList" Member="Charter" ThisKey="DL_CODE" OtherKey="CH_KEY" Type="Charter" IsForeignKey="true" />
      <Association Name="AirService_tbl_DogovorList" Member="AirService" ThisKey="DL_SUBCODE1" OtherKey="AS_KEY" Type="AirService" IsForeignKey="true" />
      <Association Name="tbl_Partner_tbl_DogovorList" Member="tbl_Partner" ThisKey="DL_PARTNERKEY" OtherKey="PR_KEY" Type="tbl_Partner" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Turist" Member="tbl_Turists">
    <Type Name="tbl_Turist">
      <Column Name="TU_DGCOD" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TU_KEY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TU_TURDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_NAMERUS" Type="System.String" DbType="VarChar(35)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_NAMELAT" Type="System.String" DbType="VarChar(35)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_SHORTNAME" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TU_SEX" Type="System.Int16" DbType="SmallInt" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_FNAMERUS" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TU_FNAMELAT" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TU_SNAMERUS" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_SNAMELAT" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_BIRTHDAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_BIRTHCOUNTRY" Type="System.String" DbType="VarChar(25)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_PASPORTTYPE" Type="System.String" DbType="VarChar(5)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_PASPORTNUM" Type="System.String" DbType="VarChar(13)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_PASPORTDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_PASPORTDATEEND" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_PASPORTBYWHOM" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_PASPRUNUM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_PASPRUDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_PASPRUBYWHOM" Type="System.String" DbType="VarChar(45)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TU_RealSex" Type="System.Int16" DbType="SmallInt" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="tbl_Turist_TuristService" Member="TuristServices" ThisKey="TU_KEY" OtherKey="TU_TUKEY" Type="TuristService" />
      <Association Name="tbl_Dogovor_tbl_Turist" Member="tbl_Dogovor" ThisKey="TU_DGCOD" OtherKey="DG_CODE" Type="tbl_Dogovor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TuristService" Member="TuristServices">
    <Type Name="TuristService">
      <Column Name="TU_TUKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TU_DLKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TU_NUMDOC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TU_NUMROOM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TU_SEAT" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="TU_AREA" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TU_DOCDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="TU_IDKEY" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="tbl_DogovorList_TuristService" Member="tbl_DogovorList" ThisKey="TU_DLKEY" OtherKey="DL_KEY" Type="tbl_DogovorList" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="tbl_Turist_TuristService" Member="tbl_Turist" ThisKey="TU_TUKEY" OtherKey="TU_KEY" Type="tbl_Turist" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Charter" Member="Charters">
    <Type Name="Charter">
      <Column Name="CH_KEY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CH_CITYKEYFROM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CH_PORTCODEFROM" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="CH_CITYKEYTO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CH_PORTCODETO" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="CH_DATEFROM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CH_DATETO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CH_DAYS" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="CH_TIMEFROM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CH_TIMETO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CH_NEXTDAYARRIV" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CH_AIRLINECODE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="CH_FLIGHT" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="CH_AIRCRAFT" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="CH_SERVICE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CH_STOPS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CH_TIMECHANGES" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="CH_StdKey" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="Charter_tbl_DogovorList" Member="tbl_DogovorLists" ThisKey="CH_KEY" OtherKey="DL_CODE" Type="tbl_DogovorList" />
      <Association Name="Charter_AirSeason" Member="AirSeasons" ThisKey="CH_KEY" OtherKey="AS_CHKEY" Type="AirSeason" />
      <Association Name="Airline_Charter" Member="Airline" ThisKey="CH_AIRLINECODE" OtherKey="AL_CODE" Type="Airline" IsForeignKey="true" />
      <Association Name="Aircraft_Charter" Member="Aircraft" ThisKey="CH_AIRCRAFT" OtherKey="AC_CODE" Type="Aircraft" IsForeignKey="true" />
      <Association Name="Airport_Charter" Member="AirportFrom" ThisKey="CH_PORTCODEFROM" OtherKey="AP_CODE" Type="Airport" IsForeignKey="true" />
      <Association Name="Airport_Charter1" Member="AirportTo" ThisKey="CH_PORTCODETO" OtherKey="AP_CODE" Type="Airport" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AirService" Member="AirServices">
    <Type Name="AirService">
      <Column Name="AS_CODE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AS_NAMERUS" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AS_KEY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="AirService_tbl_DogovorList" Member="tbl_DogovorLists" ThisKey="AS_KEY" OtherKey="DL_SUBCODE1" Type="tbl_DogovorList" />
    </Type>
  </Table>
  <Table Name="dbo.AirSeason" Member="AirSeasons">
    <Type Name="AirSeason">
      <Column Name="AS_CHKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AS_DATEFROM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AS_DATETO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AS_WEEK" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="AS_TIMEFROM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AS_TIMETO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="AS_NextDayArriv" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="AS_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AS_Remark" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Charter_AirSeason" Member="Charter" ThisKey="AS_CHKEY" OtherKey="CH_KEY" Type="Charter" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Airport" Member="Airports">
    <Type Name="Airport">
      <Column Name="AP_CODE" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="AP_CTKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AP_NAME" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="AP_LETTER" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="AP_SITE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="AP_StdKey" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ap_key" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AP_NameLat" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="CityDictionary_Airport" Member="CityDictionary" ThisKey="AP_CTKEY" OtherKey="CT_KEY" Type="CityDictionary" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Airline" Member="Airlines">
    <Type Name="Airline">
      <Column Name="AL_CODE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="AL_NAME" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="AL_StdKey" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="al_key" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AL_NameLat" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Airline_Charter" Member="Charters" ThisKey="AL_CODE" OtherKey="CH_AIRLINECODE" Type="Charter" />
    </Type>
  </Table>
  <Table Name="dbo.Aircraft" Member="Aircrafts">
    <Type Name="Aircraft">
      <Column Name="AC_CODE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="AC_NAME" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="AC_KEY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="AC_StdKey" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="AC_NameLat" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Aircraft_Charter" Member="Charters" ThisKey="AC_CODE" OtherKey="CH_AIRCRAFT" Type="Charter" />
    </Type>
  </Table>
  <Table Name="dbo.CityDictionary" Member="CityDictionaries">
    <Type Name="CityDictionary">
      <Column Name="CT_CNKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CT_KEY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CT_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CT_NAMELAT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CT_CODE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="CT_CREATOR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CT_UPDATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="CT_StdKey" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="CT_NameAC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CT_Web" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CT_RSKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CT_WEBIMAGE" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="CT_Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CT_IsDeparture" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CT_Coordinate" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="CityDictionary_Airport" Member="Airports" ThisKey="CT_KEY" OtherKey="AP_CTKEY" Type="Airport" />
    </Type>
  </Table>
  <Table Name="dbo.LTA_AviaOutTurist" Member="LTA_AviaOutTurists">
    <Type Name="LTA_AviaOutTurist">
      <Column Name="LTA_ID" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LTA_TUKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LTA_InsDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LTA_DLCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LTA_DLCode1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Partners" Member="tbl_Partners">
    <Type Name="tbl_Partner">
      <Column Name="PR_KEY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PR_FULLNAME" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="PR_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PR_NAMEENG" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="PR_BOSSNAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PR_BOSS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_MALE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PR_MAINMEN" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="PR_MAINMENPHONE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_DISCOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PR_ACCOUNT" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="PR_ADRESS" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="PR_PHONES" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="PR_FAX" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PR_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_CTKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PR_CREATOR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PR_AGENTDOGOVOR" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="PR_TYPE" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PR_CITY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_WEBAGENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PR_AGENTDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PR_AGENTDOGOVOR2" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="PR_AGENTDATE2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PR_FAX1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PR_REMARK" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="PR_CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PR_UPDATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PR_ART" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PR_USERLAST" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PR_COD" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="ROWID" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="LastUser" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="pr_IsActive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PR_Filial" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PR_DateLastContact" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PR_ExchangePwd" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PR_GUID" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PR_ExchangeData" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" />
      <Column Name="MaskedFax" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="PR_DOGOVORTYPE" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PR_ICQ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_GDS_PREFIX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_GDS_SUFFIX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_OWNER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PR_IPAddress" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="PR_Deleted" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PR_LICENSENUMBER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_ADDITIONALINFO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_LEGALADDRESS" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="PR_INN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_FOREIGNACCINFO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PR_KPP" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PR_CODEOKONH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PR_CODEOKPO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PR_HOMEPAGE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PR_PGKEY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PR_BLOCKEDFORANNUL" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PR_POSTINDEX" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="PR_LEGALPOSTINDEX" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="PR_RegisterSeries" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PR_RegisterNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PR_Http" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="pr_description" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="PR_WebServiceUrl" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="PR_PrivatePerson" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tbl_Partner_tbl_DogovorList" Member="tbl_DogovorLists" ThisKey="PR_KEY" OtherKey="DL_PARTNERKEY" Type="tbl_DogovorList" />
    </Type>
  </Table>
</Database>