//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLW.SpamMashine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.4;Initial Catalog=lanta;Persist Security Info=True;User ID" +
            "=sysadm;pwd=ieheg")]
        public string dbConnectionString {
            get {
                return ((string)(this["dbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <center>
          <br>
          <br>
          По вопросам работы системы автоматического оповещения обращайтесь по адресу:<a href=""mailto:imt.man5@lantatur.ru"">kropotov@lantatur.ru</a>
          </center>
          </body>
          </html>
        ")]
        public string BottomToInternal {
            get {
                return ((string)(this["BottomToInternal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Spamus_Service_ERR@lantatur.ru")]
        public string ErrorMailFrom {
            get {
                return ((string)(this["ErrorMailFrom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mar.man6@lantatur.ru")]
        public string ErrorMailIfMailAddressError {
            get {
                return ((string)(this["ErrorMailIfMailAddressError"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <html>
          <head>
          <title>Автоматическое извещение об изменениях в путевке</title>
          </head>
          <body>
          <center>
          <img src=""http://www.lantatur.ru/img/logo.gif""><br>
          Сервис автоматического оповещения
          </center>
          <br>
        ")]
        public string HeadToInternal {
            get {
                return ((string)(this["HeadToInternal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ланта-тур вояж:")]
        public string SubjectBeg {
            get {
                return ((string)(this["SubjectBeg"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          </body>\r\n          </html>\r\n        ")]
        public string BottomToExternal {
            get {
                return ((string)(this["BottomToExternal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("itm.man5@zmail.lantatur.ru")]
        public string ErrorMailToAdmin {
            get {
                return ((string)(this["ErrorMailToAdmin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string ExecuteInterval {
            get {
                return ((string)(this["ExecuteInterval"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <html>
          <head>
          <title>Автоматическое извещение об изменениях в путевке</title>
          </head>
          <body>
          <center>
          <img src=""http://www.lantatur.ru/img/logo.gif""><br>
          Полную информацию смотрите на сайте <a href=""http://www.lantatur.ru/OrderListBonus/"">www.lantatur.ru</a><br>
          </center><br>
        ")]
        public string HeadToExternal {
            get {
                return ((string)(this["HeadToExternal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zmail.lantatur.ru")]
        public string SMTP_Server2 {
            get {
                return ((string)(this["SMTP_Server2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mar.doc@lantatur.ru")]
        public string SMTP_Server2_UsedForAddress {
            get {
                return ((string)(this["SMTP_Server2_UsedForAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string SMTP_Server {
            get {
                return ((string)(this["SMTP_Server"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.4;Initial Catalog=lanta;Persist Security Info=True;User ID" +
            "=sa")]
        public string lantaConnectionString {
            get {
                return ((string)(this["lantaConnectionString"]));
            }
        }
    }
}
