#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rep25991
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="total_services")]
	public partial class SqlTSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertShip(Ship instance);
    partial void UpdateShip(Ship instance);
    partial void DeleteShip(Ship instance);
    partial void InsertCruiseLine(CruiseLine instance);
    partial void UpdateCruiseLine(CruiseLine instance);
    partial void DeleteCruiseLine(CruiseLine instance);
    partial void InsertSeaPOrtAdress(SeaPOrtAdress instance);
    partial void UpdateSeaPOrtAdress(SeaPOrtAdress instance);
    partial void DeleteSeaPOrtAdress(SeaPOrtAdress instance);
    partial void InsertSeaport(Seaport instance);
    partial void UpdateSeaport(Seaport instance);
    partial void DeleteSeaport(Seaport instance);
    partial void InsertRegion(Region instance);
    partial void UpdateRegion(Region instance);
    partial void DeleteRegion(Region instance);
    #endregion
		
		public SqlTSDataContext() : 
				base(global::rep25991.Properties.Settings.Default.total_servicesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SqlTSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SqlTSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SqlTSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SqlTSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ship> Ships
		{
			get
			{
				return this.GetTable<Ship>();
			}
		}
		
		public System.Data.Linq.Table<CruiseLine> CruiseLines
		{
			get
			{
				return this.GetTable<CruiseLine>();
			}
		}
		
		public System.Data.Linq.Table<Itinerary_old_all> Itinerary_old_alls
		{
			get
			{
				return this.GetTable<Itinerary_old_all>();
			}
		}
		
		public System.Data.Linq.Table<CRUISES_by_cabincategiory_and_action> CRUISES_by_cabincategiory_and_actions
		{
			get
			{
				return this.GetTable<CRUISES_by_cabincategiory_and_action>();
			}
		}
		
		public System.Data.Linq.Table<CRUISES_serch> CRUISES_serches
		{
			get
			{
				return this.GetTable<CRUISES_serch>();
			}
		}
		
		public System.Data.Linq.Table<SeaPOrtAdress> SeaPOrtAdresses
		{
			get
			{
				return this.GetTable<SeaPOrtAdress>();
			}
		}
		
		public System.Data.Linq.Table<Seaport> Seaports
		{
			get
			{
				return this.GetTable<Seaport>();
			}
		}
		
		public System.Data.Linq.Table<CRUISE> CRUISEs
		{
			get
			{
				return this.GetTable<CRUISE>();
			}
		}
		
		public System.Data.Linq.Table<Region> Regions
		{
			get
			{
				return this.GetTable<Region>();
			}
		}
		
		public System.Data.Linq.Table<CruiseTerminal> CruiseTerminals
		{
			get
			{
				return this.GetTable<CruiseTerminal>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ships")]
	public partial class Ship : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private byte _cruise_line_id;
		
		private System.Nullable<byte> _ship_class_id;
		
		private string _code;
		
		private string _name_ru;
		
		private string _name_en;
		
		private bool _visible;
		
		private System.Nullable<int> _version_prise;
		
		private EntityRef<CruiseLine> _CruiseLine;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncruise_line_idChanging(byte value);
    partial void Oncruise_line_idChanged();
    partial void Onship_class_idChanging(System.Nullable<byte> value);
    partial void Onship_class_idChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void Onname_ruChanging(string value);
    partial void Onname_ruChanged();
    partial void Onname_enChanging(string value);
    partial void Onname_enChanged();
    partial void OnvisibleChanging(bool value);
    partial void OnvisibleChanged();
    partial void Onversion_priseChanging(System.Nullable<int> value);
    partial void Onversion_priseChanged();
    #endregion
		
		public Ship()
		{
			this._CruiseLine = default(EntityRef<CruiseLine>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cruise_line_id", DbType="TinyInt NOT NULL")]
		public byte cruise_line_id
		{
			get
			{
				return this._cruise_line_id;
			}
			set
			{
				if ((this._cruise_line_id != value))
				{
					if (this._CruiseLine.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncruise_line_idChanging(value);
					this.SendPropertyChanging();
					this._cruise_line_id = value;
					this.SendPropertyChanged("cruise_line_id");
					this.Oncruise_line_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_class_id", DbType="TinyInt")]
		public System.Nullable<byte> ship_class_id
		{
			get
			{
				return this._ship_class_id;
			}
			set
			{
				if ((this._ship_class_id != value))
				{
					this.Onship_class_idChanging(value);
					this.SendPropertyChanging();
					this._ship_class_id = value;
					this.SendPropertyChanged("ship_class_id");
					this.Onship_class_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_ru", DbType="VarChar(255)")]
		public string name_ru
		{
			get
			{
				return this._name_ru;
			}
			set
			{
				if ((this._name_ru != value))
				{
					this.Onname_ruChanging(value);
					this.SendPropertyChanging();
					this._name_ru = value;
					this.SendPropertyChanged("name_ru");
					this.Onname_ruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_en", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string name_en
		{
			get
			{
				return this._name_en;
			}
			set
			{
				if ((this._name_en != value))
				{
					this.Onname_enChanging(value);
					this.SendPropertyChanging();
					this._name_en = value;
					this.SendPropertyChanged("name_en");
					this.Onname_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visible", DbType="Bit NOT NULL")]
		public bool visible
		{
			get
			{
				return this._visible;
			}
			set
			{
				if ((this._visible != value))
				{
					this.OnvisibleChanging(value);
					this.SendPropertyChanging();
					this._visible = value;
					this.SendPropertyChanged("visible");
					this.OnvisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_version_prise", DbType="Int")]
		public System.Nullable<int> version_prise
		{
			get
			{
				return this._version_prise;
			}
			set
			{
				if ((this._version_prise != value))
				{
					this.Onversion_priseChanging(value);
					this.SendPropertyChanging();
					this._version_prise = value;
					this.SendPropertyChanged("version_prise");
					this.Onversion_priseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CruiseLine_Ship", Storage="_CruiseLine", ThisKey="cruise_line_id", OtherKey="id", IsForeignKey=true)]
		public CruiseLine CruiseLine
		{
			get
			{
				return this._CruiseLine.Entity;
			}
			set
			{
				CruiseLine previousValue = this._CruiseLine.Entity;
				if (((previousValue != value) 
							|| (this._CruiseLine.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CruiseLine.Entity = null;
						previousValue.Ships.Remove(this);
					}
					this._CruiseLine.Entity = value;
					if ((value != null))
					{
						value.Ships.Add(this);
						this._cruise_line_id = value.id;
					}
					else
					{
						this._cruise_line_id = default(byte);
					}
					this.SendPropertyChanged("CruiseLine");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CruiseLines")]
	public partial class CruiseLine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _id;
		
		private string _mnemo;
		
		private string _code;
		
		private string _name_ru;
		
		private string _name_en;
		
		private bool _visible;
		
		private string _redirect;
		
		private System.Nullable<int> _order;
		
		private System.Nullable<int> _bookingtype;
		
		private System.Nullable<int> _class;
		
		private string _currency;
		
		private string _price;
		
		private EntitySet<Ship> _Ships;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(byte value);
    partial void OnidChanged();
    partial void OnmnemoChanging(string value);
    partial void OnmnemoChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void Onname_ruChanging(string value);
    partial void Onname_ruChanged();
    partial void Onname_enChanging(string value);
    partial void Onname_enChanged();
    partial void OnvisibleChanging(bool value);
    partial void OnvisibleChanged();
    partial void OnredirectChanging(string value);
    partial void OnredirectChanged();
    partial void OnorderChanging(System.Nullable<int> value);
    partial void OnorderChanged();
    partial void OnbookingtypeChanging(System.Nullable<int> value);
    partial void OnbookingtypeChanged();
    partial void OnclassChanging(System.Nullable<int> value);
    partial void OnclassChanged();
    partial void OncurrencyChanging(string value);
    partial void OncurrencyChanged();
    partial void OnpriceChanging(string value);
    partial void OnpriceChanged();
    #endregion
		
		public CruiseLine()
		{
			this._Ships = new EntitySet<Ship>(new Action<Ship>(this.attach_Ships), new Action<Ship>(this.detach_Ships));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mnemo", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string mnemo
		{
			get
			{
				return this._mnemo;
			}
			set
			{
				if ((this._mnemo != value))
				{
					this.OnmnemoChanging(value);
					this.SendPropertyChanging();
					this._mnemo = value;
					this.SendPropertyChanged("mnemo");
					this.OnmnemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_ru", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string name_ru
		{
			get
			{
				return this._name_ru;
			}
			set
			{
				if ((this._name_ru != value))
				{
					this.Onname_ruChanging(value);
					this.SendPropertyChanging();
					this._name_ru = value;
					this.SendPropertyChanged("name_ru");
					this.Onname_ruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_en", DbType="VarChar(255)")]
		public string name_en
		{
			get
			{
				return this._name_en;
			}
			set
			{
				if ((this._name_en != value))
				{
					this.Onname_enChanging(value);
					this.SendPropertyChanging();
					this._name_en = value;
					this.SendPropertyChanged("name_en");
					this.Onname_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visible", DbType="Bit NOT NULL")]
		public bool visible
		{
			get
			{
				return this._visible;
			}
			set
			{
				if ((this._visible != value))
				{
					this.OnvisibleChanging(value);
					this.SendPropertyChanging();
					this._visible = value;
					this.SendPropertyChanged("visible");
					this.OnvisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_redirect", DbType="VarChar(255)")]
		public string redirect
		{
			get
			{
				return this._redirect;
			}
			set
			{
				if ((this._redirect != value))
				{
					this.OnredirectChanging(value);
					this.SendPropertyChanging();
					this._redirect = value;
					this.SendPropertyChanged("redirect");
					this.OnredirectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[order]", Storage="_order", DbType="Int")]
		public System.Nullable<int> order
		{
			get
			{
				return this._order;
			}
			set
			{
				if ((this._order != value))
				{
					this.OnorderChanging(value);
					this.SendPropertyChanging();
					this._order = value;
					this.SendPropertyChanged("order");
					this.OnorderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bookingtype", DbType="Int")]
		public System.Nullable<int> bookingtype
		{
			get
			{
				return this._bookingtype;
			}
			set
			{
				if ((this._bookingtype != value))
				{
					this.OnbookingtypeChanging(value);
					this.SendPropertyChanging();
					this._bookingtype = value;
					this.SendPropertyChanged("bookingtype");
					this.OnbookingtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="class", Storage="_class", DbType="Int")]
		public System.Nullable<int> @class
		{
			get
			{
				return this._class;
			}
			set
			{
				if ((this._class != value))
				{
					this.OnclassChanging(value);
					this.SendPropertyChanging();
					this._class = value;
					this.SendPropertyChanged("@class");
					this.OnclassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currency", DbType="NChar(3)")]
		public string currency
		{
			get
			{
				return this._currency;
			}
			set
			{
				if ((this._currency != value))
				{
					this.OncurrencyChanging(value);
					this.SendPropertyChanging();
					this._currency = value;
					this.SendPropertyChanged("currency");
					this.OncurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="VarChar(100)")]
		public string price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CruiseLine_Ship", Storage="_Ships", ThisKey="id", OtherKey="cruise_line_id")]
		public EntitySet<Ship> Ships
		{
			get
			{
				return this._Ships;
			}
			set
			{
				this._Ships.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ships(Ship entity)
		{
			this.SendPropertyChanging();
			entity.CruiseLine = this;
		}
		
		private void detach_Ships(Ship entity)
		{
			this.SendPropertyChanging();
			entity.CruiseLine = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Itinerary_old_all")]
	public partial class Itinerary_old_all
	{
		
		private string _package;
		
		private System.DateTime _sailDate;
		
		private System.DateTime _activityDate;
		
		private string _shipCode;
		
		private string _itinerary;
		
		private bool _sailingFlag;
		
		private string _portion;
		
		private string _locCode;
		
		private string _locName;
		
		private string _activity;
		
		private string _arrival;
		
		private string _departure;
		
		private System.Nullable<int> _id_crline;
		
		public Itinerary_old_all()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_package", DbType="VarChar(100)")]
		public string package
		{
			get
			{
				return this._package;
			}
			set
			{
				if ((this._package != value))
				{
					this._package = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sailDate", DbType="DateTime NOT NULL")]
		public System.DateTime sailDate
		{
			get
			{
				return this._sailDate;
			}
			set
			{
				if ((this._sailDate != value))
				{
					this._sailDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activityDate", DbType="DateTime NOT NULL")]
		public System.DateTime activityDate
		{
			get
			{
				return this._activityDate;
			}
			set
			{
				if ((this._activityDate != value))
				{
					this._activityDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipCode", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string shipCode
		{
			get
			{
				return this._shipCode;
			}
			set
			{
				if ((this._shipCode != value))
				{
					this._shipCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itinerary", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string itinerary
		{
			get
			{
				return this._itinerary;
			}
			set
			{
				if ((this._itinerary != value))
				{
					this._itinerary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sailingFlag", DbType="Bit NOT NULL")]
		public bool sailingFlag
		{
			get
			{
				return this._sailingFlag;
			}
			set
			{
				if ((this._sailingFlag != value))
				{
					this._sailingFlag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string portion
		{
			get
			{
				return this._portion;
			}
			set
			{
				if ((this._portion != value))
				{
					this._portion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_locCode", DbType="VarChar(7)")]
		public string locCode
		{
			get
			{
				return this._locCode;
			}
			set
			{
				if ((this._locCode != value))
				{
					this._locCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_locName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string locName
		{
			get
			{
				return this._locName;
			}
			set
			{
				if ((this._locName != value))
				{
					this._locName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activity", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string activity
		{
			get
			{
				return this._activity;
			}
			set
			{
				if ((this._activity != value))
				{
					this._activity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arrival", DbType="VarChar(12)")]
		public string arrival
		{
			get
			{
				return this._arrival;
			}
			set
			{
				if ((this._arrival != value))
				{
					this._arrival = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departure", DbType="VarChar(12)")]
		public string departure
		{
			get
			{
				return this._departure;
			}
			set
			{
				if ((this._departure != value))
				{
					this._departure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_crline", DbType="Int")]
		public System.Nullable<int> id_crline
		{
			get
			{
				return this._id_crline;
			}
			set
			{
				if ((this._id_crline != value))
				{
					this._id_crline = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CRUISES_by_cabincategiory_and_actions")]
	public partial class CRUISES_by_cabincategiory_and_action
	{
		
		private string _package;
		
		private System.Nullable<System.DateTime> _sailDate;
		
		private string _brandCode;
		
		private string _Actions_client;
		
		private string _Actions_agensy;
		
		private string _Actions_agensy_serch;
		
		private string _price_all;
		
		public CRUISES_by_cabincategiory_and_action()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_package", DbType="Char(20)")]
		public string package
		{
			get
			{
				return this._package;
			}
			set
			{
				if ((this._package != value))
				{
					this._package = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sailDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> sailDate
		{
			get
			{
				return this._sailDate;
			}
			set
			{
				if ((this._sailDate != value))
				{
					this._sailDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brandCode", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string brandCode
		{
			get
			{
				return this._brandCode;
			}
			set
			{
				if ((this._brandCode != value))
				{
					this._brandCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Actions_client", DbType="VarChar(300)")]
		public string Actions_client
		{
			get
			{
				return this._Actions_client;
			}
			set
			{
				if ((this._Actions_client != value))
				{
					this._Actions_client = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Actions_agensy", DbType="VarChar(300)")]
		public string Actions_agensy
		{
			get
			{
				return this._Actions_agensy;
			}
			set
			{
				if ((this._Actions_agensy != value))
				{
					this._Actions_agensy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Actions_agensy_serch", DbType="VarChar(300)")]
		public string Actions_agensy_serch
		{
			get
			{
				return this._Actions_agensy_serch;
			}
			set
			{
				if ((this._Actions_agensy_serch != value))
				{
					this._Actions_agensy_serch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_all", DbType="VarChar(200)")]
		public string price_all
		{
			get
			{
				return this._price_all;
			}
			set
			{
				if ((this._price_all != value))
				{
					this._price_all = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CRUISES_serch")]
	public partial class CRUISES_serch
	{
		
		private string _package;
		
		private System.Nullable<System.DateTime> _sailDate;
		
		private string _brandCode;
		
		private string _shipCode;
		
		private string _cruiseName;
		
		private string _itinerary;
		
		private string _days_action;
		
		private System.Nullable<int> _min_cost;
		
		private System.Nullable<int> _old_min_cost;
		
		public CRUISES_serch()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_package", DbType="Char(20)")]
		public string package
		{
			get
			{
				return this._package;
			}
			set
			{
				if ((this._package != value))
				{
					this._package = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sailDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> sailDate
		{
			get
			{
				return this._sailDate;
			}
			set
			{
				if ((this._sailDate != value))
				{
					this._sailDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brandCode", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string brandCode
		{
			get
			{
				return this._brandCode;
			}
			set
			{
				if ((this._brandCode != value))
				{
					this._brandCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipCode", DbType="VarChar(3)")]
		public string shipCode
		{
			get
			{
				return this._shipCode;
			}
			set
			{
				if ((this._shipCode != value))
				{
					this._shipCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cruiseName", DbType="VarChar(100)")]
		public string cruiseName
		{
			get
			{
				return this._cruiseName;
			}
			set
			{
				if ((this._cruiseName != value))
				{
					this._cruiseName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itinerary", DbType="VarChar(8000)")]
		public string itinerary
		{
			get
			{
				return this._itinerary;
			}
			set
			{
				if ((this._itinerary != value))
				{
					this._itinerary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_days_action", DbType="VarChar(MAX)")]
		public string days_action
		{
			get
			{
				return this._days_action;
			}
			set
			{
				if ((this._days_action != value))
				{
					this._days_action = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_min_cost", DbType="Int")]
		public System.Nullable<int> min_cost
		{
			get
			{
				return this._min_cost;
			}
			set
			{
				if ((this._min_cost != value))
				{
					this._min_cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_old_min_cost", DbType="Int")]
		public System.Nullable<int> old_min_cost
		{
			get
			{
				return this._old_min_cost;
			}
			set
			{
				if ((this._old_min_cost != value))
				{
					this._old_min_cost = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SeaPOrtAdress")]
	public partial class SeaPOrtAdress : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PA_ID;
		
		private int _PA_SPID;
		
		private string _PA_NAME;
		
		private string _PA_ADRESS;
		
		private string _PA_DESCRIPTION;
		
		private EntityRef<Seaport> _Seaport;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPA_IDChanging(int value);
    partial void OnPA_IDChanged();
    partial void OnPA_SPIDChanging(int value);
    partial void OnPA_SPIDChanged();
    partial void OnPA_NAMEChanging(string value);
    partial void OnPA_NAMEChanged();
    partial void OnPA_ADRESSChanging(string value);
    partial void OnPA_ADRESSChanged();
    partial void OnPA_DESCRIPTIONChanging(string value);
    partial void OnPA_DESCRIPTIONChanged();
    #endregion
		
		public SeaPOrtAdress()
		{
			this._Seaport = default(EntityRef<Seaport>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PA_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PA_ID
		{
			get
			{
				return this._PA_ID;
			}
			set
			{
				if ((this._PA_ID != value))
				{
					this.OnPA_IDChanging(value);
					this.SendPropertyChanging();
					this._PA_ID = value;
					this.SendPropertyChanged("PA_ID");
					this.OnPA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PA_SPID", DbType="Int NOT NULL")]
		public int PA_SPID
		{
			get
			{
				return this._PA_SPID;
			}
			set
			{
				if ((this._PA_SPID != value))
				{
					if (this._Seaport.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPA_SPIDChanging(value);
					this.SendPropertyChanging();
					this._PA_SPID = value;
					this.SendPropertyChanged("PA_SPID");
					this.OnPA_SPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PA_NAME", DbType="VarChar(200)")]
		public string PA_NAME
		{
			get
			{
				return this._PA_NAME;
			}
			set
			{
				if ((this._PA_NAME != value))
				{
					this.OnPA_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PA_NAME = value;
					this.SendPropertyChanged("PA_NAME");
					this.OnPA_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PA_ADRESS", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PA_ADRESS
		{
			get
			{
				return this._PA_ADRESS;
			}
			set
			{
				if ((this._PA_ADRESS != value))
				{
					this.OnPA_ADRESSChanging(value);
					this.SendPropertyChanging();
					this._PA_ADRESS = value;
					this.SendPropertyChanged("PA_ADRESS");
					this.OnPA_ADRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PA_DESCRIPTION", DbType="VarChar(500)")]
		public string PA_DESCRIPTION
		{
			get
			{
				return this._PA_DESCRIPTION;
			}
			set
			{
				if ((this._PA_DESCRIPTION != value))
				{
					this.OnPA_DESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._PA_DESCRIPTION = value;
					this.SendPropertyChanged("PA_DESCRIPTION");
					this.OnPA_DESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seaport_SeaPOrtAdress", Storage="_Seaport", ThisKey="PA_SPID", OtherKey="id", IsForeignKey=true)]
		public Seaport Seaport
		{
			get
			{
				return this._Seaport.Entity;
			}
			set
			{
				Seaport previousValue = this._Seaport.Entity;
				if (((previousValue != value) 
							|| (this._Seaport.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Seaport.Entity = null;
						previousValue.SeaPOrtAdresses.Remove(this);
					}
					this._Seaport.Entity = value;
					if ((value != null))
					{
						value.SeaPOrtAdresses.Add(this);
						this._PA_SPID = value.id;
					}
					else
					{
						this._PA_SPID = default(int);
					}
					this.SendPropertyChanged("Seaport");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Seaports")]
	public partial class Seaport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _code;
		
		private string _name_ru;
		
		private string _name_en;
		
		private bool _visible;
		
		private System.Nullable<int> _parent;
		
		private System.Nullable<int> _id_crline;
		
		private System.Nullable<int> _id_region;
		
		private System.Nullable<int> _id_contry_master;
		
		private EntitySet<SeaPOrtAdress> _SeaPOrtAdresses;
		
		private EntitySet<Seaport> _Seaports;
		
		private EntityRef<Seaport> _Seaport1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void Onname_ruChanging(string value);
    partial void Onname_ruChanged();
    partial void Onname_enChanging(string value);
    partial void Onname_enChanged();
    partial void OnvisibleChanging(bool value);
    partial void OnvisibleChanged();
    partial void OnparentChanging(System.Nullable<int> value);
    partial void OnparentChanged();
    partial void Onid_crlineChanging(System.Nullable<int> value);
    partial void Onid_crlineChanged();
    partial void Onid_regionChanging(System.Nullable<int> value);
    partial void Onid_regionChanged();
    partial void Onid_contry_masterChanging(System.Nullable<int> value);
    partial void Onid_contry_masterChanged();
    #endregion
		
		public Seaport()
		{
			this._SeaPOrtAdresses = new EntitySet<SeaPOrtAdress>(new Action<SeaPOrtAdress>(this.attach_SeaPOrtAdresses), new Action<SeaPOrtAdress>(this.detach_SeaPOrtAdresses));
			this._Seaports = new EntitySet<Seaport>(new Action<Seaport>(this.attach_Seaports), new Action<Seaport>(this.detach_Seaports));
			this._Seaport1 = default(EntityRef<Seaport>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(7)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_ru", DbType="VarChar(150)")]
		public string name_ru
		{
			get
			{
				return this._name_ru;
			}
			set
			{
				if ((this._name_ru != value))
				{
					this.Onname_ruChanging(value);
					this.SendPropertyChanging();
					this._name_ru = value;
					this.SendPropertyChanged("name_ru");
					this.Onname_ruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_en", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string name_en
		{
			get
			{
				return this._name_en;
			}
			set
			{
				if ((this._name_en != value))
				{
					this.Onname_enChanging(value);
					this.SendPropertyChanging();
					this._name_en = value;
					this.SendPropertyChanged("name_en");
					this.Onname_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visible", DbType="Bit NOT NULL")]
		public bool visible
		{
			get
			{
				return this._visible;
			}
			set
			{
				if ((this._visible != value))
				{
					this.OnvisibleChanging(value);
					this.SendPropertyChanging();
					this._visible = value;
					this.SendPropertyChanged("visible");
					this.OnvisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent", DbType="Int")]
		public System.Nullable<int> parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					if (this._Seaport1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnparentChanging(value);
					this.SendPropertyChanging();
					this._parent = value;
					this.SendPropertyChanged("parent");
					this.OnparentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_crline", DbType="Int")]
		public System.Nullable<int> id_crline
		{
			get
			{
				return this._id_crline;
			}
			set
			{
				if ((this._id_crline != value))
				{
					this.Onid_crlineChanging(value);
					this.SendPropertyChanging();
					this._id_crline = value;
					this.SendPropertyChanged("id_crline");
					this.Onid_crlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_region", DbType="Int")]
		public System.Nullable<int> id_region
		{
			get
			{
				return this._id_region;
			}
			set
			{
				if ((this._id_region != value))
				{
					this.Onid_regionChanging(value);
					this.SendPropertyChanging();
					this._id_region = value;
					this.SendPropertyChanged("id_region");
					this.Onid_regionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contry_master", DbType="Int")]
		public System.Nullable<int> id_contry_master
		{
			get
			{
				return this._id_contry_master;
			}
			set
			{
				if ((this._id_contry_master != value))
				{
					this.Onid_contry_masterChanging(value);
					this.SendPropertyChanging();
					this._id_contry_master = value;
					this.SendPropertyChanged("id_contry_master");
					this.Onid_contry_masterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seaport_SeaPOrtAdress", Storage="_SeaPOrtAdresses", ThisKey="id", OtherKey="PA_SPID")]
		public EntitySet<SeaPOrtAdress> SeaPOrtAdresses
		{
			get
			{
				return this._SeaPOrtAdresses;
			}
			set
			{
				this._SeaPOrtAdresses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seaport_Seaport", Storage="_Seaports", ThisKey="id", OtherKey="parent")]
		public EntitySet<Seaport> Seaports
		{
			get
			{
				return this._Seaports;
			}
			set
			{
				this._Seaports.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seaport_Seaport", Storage="_Seaport1", ThisKey="parent", OtherKey="id", IsForeignKey=true)]
		public Seaport Seaport1
		{
			get
			{
				return this._Seaport1.Entity;
			}
			set
			{
				Seaport previousValue = this._Seaport1.Entity;
				if (((previousValue != value) 
							|| (this._Seaport1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Seaport1.Entity = null;
						previousValue.Seaports.Remove(this);
					}
					this._Seaport1.Entity = value;
					if ((value != null))
					{
						value.Seaports.Add(this);
						this._parent = value.id;
					}
					else
					{
						this._parent = default(Nullable<int>);
					}
					this.SendPropertyChanged("Seaport1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SeaPOrtAdresses(SeaPOrtAdress entity)
		{
			this.SendPropertyChanging();
			entity.Seaport = this;
		}
		
		private void detach_SeaPOrtAdresses(SeaPOrtAdress entity)
		{
			this.SendPropertyChanging();
			entity.Seaport = null;
		}
		
		private void attach_Seaports(Seaport entity)
		{
			this.SendPropertyChanging();
			entity.Seaport1 = this;
		}
		
		private void detach_Seaports(Seaport entity)
		{
			this.SendPropertyChanging();
			entity.Seaport1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CRUISES")]
	public partial class CRUISE
	{
		
		private string _package;
		
		private System.Nullable<System.DateTime> _sailDate;
		
		private string _brandCode;
		
		private string _shipCode;
		
		private string _departurePort;
		
		private string _regionCode;
		
		private string _subRegionCode;
		
		private string _packageDesc;
		
		private System.Nullable<byte> _isRussianGroup;
		
		private System.Nullable<byte> _available;
		
		private System.Nullable<int> _duration;
		
		private string _cruiseName;
		
		private System.Nullable<int> _itinerary;
		
		public CRUISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_package", DbType="Char(20)")]
		public string package
		{
			get
			{
				return this._package;
			}
			set
			{
				if ((this._package != value))
				{
					this._package = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sailDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> sailDate
		{
			get
			{
				return this._sailDate;
			}
			set
			{
				if ((this._sailDate != value))
				{
					this._sailDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brandCode", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string brandCode
		{
			get
			{
				return this._brandCode;
			}
			set
			{
				if ((this._brandCode != value))
				{
					this._brandCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipCode", DbType="VarChar(3)")]
		public string shipCode
		{
			get
			{
				return this._shipCode;
			}
			set
			{
				if ((this._shipCode != value))
				{
					this._shipCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departurePort", DbType="VarChar(7)")]
		public string departurePort
		{
			get
			{
				return this._departurePort;
			}
			set
			{
				if ((this._departurePort != value))
				{
					this._departurePort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regionCode", DbType="VarChar(50)")]
		public string regionCode
		{
			get
			{
				return this._regionCode;
			}
			set
			{
				if ((this._regionCode != value))
				{
					this._regionCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subRegionCode", DbType="VarChar(10)")]
		public string subRegionCode
		{
			get
			{
				return this._subRegionCode;
			}
			set
			{
				if ((this._subRegionCode != value))
				{
					this._subRegionCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_packageDesc", DbType="VarChar(250)")]
		public string packageDesc
		{
			get
			{
				return this._packageDesc;
			}
			set
			{
				if ((this._packageDesc != value))
				{
					this._packageDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isRussianGroup", DbType="TinyInt")]
		public System.Nullable<byte> isRussianGroup
		{
			get
			{
				return this._isRussianGroup;
			}
			set
			{
				if ((this._isRussianGroup != value))
				{
					this._isRussianGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_available", DbType="TinyInt")]
		public System.Nullable<byte> available
		{
			get
			{
				return this._available;
			}
			set
			{
				if ((this._available != value))
				{
					this._available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="Int")]
		public System.Nullable<int> duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this._duration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cruiseName", DbType="VarChar(100)")]
		public string cruiseName
		{
			get
			{
				return this._cruiseName;
			}
			set
			{
				if ((this._cruiseName != value))
				{
					this._cruiseName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itinerary", DbType="Int")]
		public System.Nullable<int> itinerary
		{
			get
			{
				return this._itinerary;
			}
			set
			{
				if ((this._itinerary != value))
				{
					this._itinerary = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Regions")]
	public partial class Region : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _code;
		
		private string _name_ru;
		
		private string _name_en;
		
		private bool _visible;
		
		private System.Nullable<int> _parent;
		
		private System.Nullable<int> _ordrer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void Onname_ruChanging(string value);
    partial void Onname_ruChanged();
    partial void Onname_enChanging(string value);
    partial void Onname_enChanged();
    partial void OnvisibleChanging(bool value);
    partial void OnvisibleChanged();
    partial void OnparentChanging(System.Nullable<int> value);
    partial void OnparentChanged();
    partial void OnordrerChanging(System.Nullable<int> value);
    partial void OnordrerChanged();
    #endregion
		
		public Region()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(50)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_ru", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name_ru
		{
			get
			{
				return this._name_ru;
			}
			set
			{
				if ((this._name_ru != value))
				{
					this.Onname_ruChanging(value);
					this.SendPropertyChanging();
					this._name_ru = value;
					this.SendPropertyChanged("name_ru");
					this.Onname_ruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_en", DbType="VarChar(100)")]
		public string name_en
		{
			get
			{
				return this._name_en;
			}
			set
			{
				if ((this._name_en != value))
				{
					this.Onname_enChanging(value);
					this.SendPropertyChanging();
					this._name_en = value;
					this.SendPropertyChanged("name_en");
					this.Onname_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visible", DbType="Bit NOT NULL")]
		public bool visible
		{
			get
			{
				return this._visible;
			}
			set
			{
				if ((this._visible != value))
				{
					this.OnvisibleChanging(value);
					this.SendPropertyChanging();
					this._visible = value;
					this.SendPropertyChanged("visible");
					this.OnvisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent", DbType="Int")]
		public System.Nullable<int> parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					this.OnparentChanging(value);
					this.SendPropertyChanging();
					this._parent = value;
					this.SendPropertyChanged("parent");
					this.OnparentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordrer", DbType="Int")]
		public System.Nullable<int> ordrer
		{
			get
			{
				return this._ordrer;
			}
			set
			{
				if ((this._ordrer != value))
				{
					this.OnordrerChanging(value);
					this.SendPropertyChanging();
					this._ordrer = value;
					this.SendPropertyChanged("ordrer");
					this.OnordrerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CruiseTerminal")]
	public partial class CruiseTerminal
	{
		
		private string _pacage;
		
		private System.DateTime _saildate;
		
		private int _ID_terminal;
		
		public CruiseTerminal()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pacage", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pacage
		{
			get
			{
				return this._pacage;
			}
			set
			{
				if ((this._pacage != value))
				{
					this._pacage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saildate", DbType="DateTime NOT NULL")]
		public System.DateTime saildate
		{
			get
			{
				return this._saildate;
			}
			set
			{
				if ((this._saildate != value))
				{
					this._saildate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_terminal", DbType="Int NOT NULL")]
		public int ID_terminal
		{
			get
			{
				return this._ID_terminal;
			}
			set
			{
				if ((this._ID_terminal != value))
				{
					this._ID_terminal = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
