#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rep259920
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="lanta")]
	public partial class sqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Dogovor(tbl_Dogovor instance);
    partial void Updatetbl_Dogovor(tbl_Dogovor instance);
    partial void Deletetbl_Dogovor(tbl_Dogovor instance);
    partial void InsertHistory(History instance);
    partial void UpdateHistory(History instance);
    partial void DeleteHistory(History instance);
    partial void Inserttbl_DogovorList(tbl_DogovorList instance);
    partial void Updatetbl_DogovorList(tbl_DogovorList instance);
    partial void Deletetbl_DogovorList(tbl_DogovorList instance);
    partial void InsertLanta_RouteCertificateAdmin(Lanta_RouteCertificateAdmin instance);
    partial void UpdateLanta_RouteCertificateAdmin(Lanta_RouteCertificateAdmin instance);
    partial void DeleteLanta_RouteCertificateAdmin(Lanta_RouteCertificateAdmin instance);
    #endregion
		
		public sqlDataContext() : 
				base(global::rep259920.Properties.Settings.Default.lantaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public sqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Dogovor> tbl_Dogovors
		{
			get
			{
				return this.GetTable<tbl_Dogovor>();
			}
		}
		
		public System.Data.Linq.Table<History> Histories
		{
			get
			{
				return this.GetTable<History>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DogovorList> tbl_DogovorLists
		{
			get
			{
				return this.GetTable<tbl_DogovorList>();
			}
		}
		
		public System.Data.Linq.Table<Lanta_RouteCertificateAdmin> Lanta_RouteCertificateAdmins
		{
			get
			{
				return this.GetTable<Lanta_RouteCertificateAdmin>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LANTA2011_PAYMENTS_DATES_UPDATE")]
		public int LANTA2011_PAYMENTS_DATES_UPDATE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DG_Code", DbType="VarChar(10)")] string dG_Code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dG_Code);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Dogovor")]
	public partial class tbl_Dogovor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DG_CODE;
		
		private System.DateTime _DG_TURDATE;
		
		private System.Nullable<int> _DG_TRKEY;
		
		private int _DG_CNKEY;
		
		private int _DG_CTKEY;
		
		private System.Nullable<short> _DG_NMEN;
		
		private decimal _DG_PRICE;
		
		private System.Nullable<decimal> _DG_PAYED;
		
		private double _DG_NDAY;
		
		private string _DG_MAINMEN;
		
		private string _DG_MAINMENPHONE;
		
		private string _DG_MAINMENADRESS;
		
		private string _DG_MAINMENPASPORT;
		
		private System.Nullable<int> _DG_PARTNERKEY;
		
		private string _DG_OPERATOR;
		
		private System.Nullable<short> _DG_PRINTDOGOVOR;
		
		private System.Nullable<short> _DG_PRINTVAUCHER;
		
		private System.Nullable<short> _DG_TYPECOUNT;
		
		private System.Nullable<decimal> _DG_DISCOUNT;
		
		private decimal _DG_DISCOUNTSUM;
		
		private int _DG_CREATOR;
		
		private int _DG_OWNER;
		
		private int _DG_SOR_CODE;
		
		private System.DateTime _DG_CRDATE;
		
		private string _DG_RATE;
		
		private System.Nullable<int> _DG_ADVERTISE;
		
		private System.Nullable<short> _DG_LOCKED;
		
		private System.Nullable<int> _DG_CAUSEDISC;
		
		private System.Nullable<System.DateTime> _DG_VISADATE;
		
		private System.Nullable<System.DateTime> _DG_PPAYMENTDATE;
		
		private System.Nullable<System.DateTime> _DG_PAYMENTDATE;
		
		private System.Nullable<System.DateTime> _DG_TURPUTDATE;
		
		private string _DG_DOCUMENT;
		
		private string _DG_TURPUTPLACE;
		
		private System.Nullable<int> _DG_PROCENT;
		
		private System.Nullable<System.DateTime> _DG_OLDTOURDATE;
		
		private System.Data.Linq.Binary _ROWID;
		
		private System.Nullable<System.DateTime> _DG_TurDateBfrAnnul;
		
		private System.Nullable<int> _DG_ARKey;
		
		private int _DG_Key;
		
		private string _DG_CodePartner;
		
		private int _DG_FilialKey;
		
		private int _DG_IsOutDoc;
		
		private System.Nullable<int> _DG_AgentID;
		
		private System.Nullable<decimal> _DG_DISCSUMBFRANN;
		
		private System.Nullable<decimal> _DG_PRICEBFRANN;
		
		private System.Nullable<short> _DG_TRANSFERRED;
		
		private string _DG_NOTES;
		
		private System.Nullable<int> _DG_DCRCLIENT;
		
		private System.Nullable<int> _DG_DCRPAYMENT;
		
		private System.Nullable<int> _DG_ISMAKEDISCOUNT;
		
		private System.Nullable<decimal> _DG_RazmerP;
		
		private int _DG_LEADDEPARTMENT;
		
		private string _DG_MAINMENEMAIL;
		
		private string _DG_MAINMENCOMMENT;
		
		private System.Nullable<int> _DG_DUPUSERKEY;
		
		private System.Nullable<int> _DG_BTKEY;
		
		private string _DG_INVOICECOST;
		
		private System.Nullable<System.DateTime> _DG_ConfirmedDate;
		
		private int _DG_PRTDOGKEY;
		
		private System.Nullable<int> _DG_CTDepartureKey;
		
		private System.Nullable<decimal> _DG_SalePrice;
		
		private System.Nullable<decimal> _DG_SaleDiscount;
		
		private short _DG_PDTType;
		
		private System.Nullable<decimal> _DG_NATIONALCURRENCYPRICE;
		
		private System.Nullable<decimal> _DG_NATIONALCURRENCYDISCOUNTSUM;
		
		private System.Nullable<int> _DG_DAKey;
		
		private System.Nullable<decimal> _DG_NATIONALCURRENCYPAYED;
		
		private EntitySet<tbl_DogovorList> _tbl_DogovorLists;
		
		private EntitySet<Lanta_RouteCertificateAdmin> _Lanta_RouteCertificateAdmins;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDG_CODEChanging(string value);
    partial void OnDG_CODEChanged();
    partial void OnDG_TURDATEChanging(System.DateTime value);
    partial void OnDG_TURDATEChanged();
    partial void OnDG_TRKEYChanging(System.Nullable<int> value);
    partial void OnDG_TRKEYChanged();
    partial void OnDG_CNKEYChanging(int value);
    partial void OnDG_CNKEYChanged();
    partial void OnDG_CTKEYChanging(int value);
    partial void OnDG_CTKEYChanged();
    partial void OnDG_NMENChanging(System.Nullable<short> value);
    partial void OnDG_NMENChanged();
    partial void OnDG_PRICEChanging(decimal value);
    partial void OnDG_PRICEChanged();
    partial void OnDG_PAYEDChanging(System.Nullable<decimal> value);
    partial void OnDG_PAYEDChanged();
    partial void OnDG_NDAYChanging(double value);
    partial void OnDG_NDAYChanged();
    partial void OnDG_MAINMENChanging(string value);
    partial void OnDG_MAINMENChanged();
    partial void OnDG_MAINMENPHONEChanging(string value);
    partial void OnDG_MAINMENPHONEChanged();
    partial void OnDG_MAINMENADRESSChanging(string value);
    partial void OnDG_MAINMENADRESSChanged();
    partial void OnDG_MAINMENPASPORTChanging(string value);
    partial void OnDG_MAINMENPASPORTChanged();
    partial void OnDG_PARTNERKEYChanging(System.Nullable<int> value);
    partial void OnDG_PARTNERKEYChanged();
    partial void OnDG_OPERATORChanging(string value);
    partial void OnDG_OPERATORChanged();
    partial void OnDG_PRINTDOGOVORChanging(System.Nullable<short> value);
    partial void OnDG_PRINTDOGOVORChanged();
    partial void OnDG_PRINTVAUCHERChanging(System.Nullable<short> value);
    partial void OnDG_PRINTVAUCHERChanged();
    partial void OnDG_TYPECOUNTChanging(System.Nullable<short> value);
    partial void OnDG_TYPECOUNTChanged();
    partial void OnDG_DISCOUNTChanging(System.Nullable<decimal> value);
    partial void OnDG_DISCOUNTChanged();
    partial void OnDG_DISCOUNTSUMChanging(decimal value);
    partial void OnDG_DISCOUNTSUMChanged();
    partial void OnDG_CREATORChanging(int value);
    partial void OnDG_CREATORChanged();
    partial void OnDG_OWNERChanging(int value);
    partial void OnDG_OWNERChanged();
    partial void OnDG_SOR_CODEChanging(int value);
    partial void OnDG_SOR_CODEChanged();
    partial void OnDG_CRDATEChanging(System.DateTime value);
    partial void OnDG_CRDATEChanged();
    partial void OnDG_RATEChanging(string value);
    partial void OnDG_RATEChanged();
    partial void OnDG_ADVERTISEChanging(System.Nullable<int> value);
    partial void OnDG_ADVERTISEChanged();
    partial void OnDG_LOCKEDChanging(System.Nullable<short> value);
    partial void OnDG_LOCKEDChanged();
    partial void OnDG_CAUSEDISCChanging(System.Nullable<int> value);
    partial void OnDG_CAUSEDISCChanged();
    partial void OnDG_VISADATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDG_VISADATEChanged();
    partial void OnDG_PPAYMENTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDG_PPAYMENTDATEChanged();
    partial void OnDG_PAYMENTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDG_PAYMENTDATEChanged();
    partial void OnDG_TURPUTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDG_TURPUTDATEChanged();
    partial void OnDG_DOCUMENTChanging(string value);
    partial void OnDG_DOCUMENTChanged();
    partial void OnDG_TURPUTPLACEChanging(string value);
    partial void OnDG_TURPUTPLACEChanged();
    partial void OnDG_PROCENTChanging(System.Nullable<int> value);
    partial void OnDG_PROCENTChanged();
    partial void OnDG_OLDTOURDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDG_OLDTOURDATEChanged();
    partial void OnROWIDChanging(System.Data.Linq.Binary value);
    partial void OnROWIDChanged();
    partial void OnDG_TurDateBfrAnnulChanging(System.Nullable<System.DateTime> value);
    partial void OnDG_TurDateBfrAnnulChanged();
    partial void OnDG_ARKeyChanging(System.Nullable<int> value);
    partial void OnDG_ARKeyChanged();
    partial void OnDG_KeyChanging(int value);
    partial void OnDG_KeyChanged();
    partial void OnDG_CodePartnerChanging(string value);
    partial void OnDG_CodePartnerChanged();
    partial void OnDG_FilialKeyChanging(int value);
    partial void OnDG_FilialKeyChanged();
    partial void OnDG_IsOutDocChanging(int value);
    partial void OnDG_IsOutDocChanged();
    partial void OnDG_AgentIDChanging(System.Nullable<int> value);
    partial void OnDG_AgentIDChanged();
    partial void OnDG_DISCSUMBFRANNChanging(System.Nullable<decimal> value);
    partial void OnDG_DISCSUMBFRANNChanged();
    partial void OnDG_PRICEBFRANNChanging(System.Nullable<decimal> value);
    partial void OnDG_PRICEBFRANNChanged();
    partial void OnDG_TRANSFERREDChanging(System.Nullable<short> value);
    partial void OnDG_TRANSFERREDChanged();
    partial void OnDG_NOTESChanging(string value);
    partial void OnDG_NOTESChanged();
    partial void OnDG_DCRCLIENTChanging(System.Nullable<int> value);
    partial void OnDG_DCRCLIENTChanged();
    partial void OnDG_DCRPAYMENTChanging(System.Nullable<int> value);
    partial void OnDG_DCRPAYMENTChanged();
    partial void OnDG_ISMAKEDISCOUNTChanging(System.Nullable<int> value);
    partial void OnDG_ISMAKEDISCOUNTChanged();
    partial void OnDG_RazmerPChanging(System.Nullable<decimal> value);
    partial void OnDG_RazmerPChanged();
    partial void OnDG_LEADDEPARTMENTChanging(int value);
    partial void OnDG_LEADDEPARTMENTChanged();
    partial void OnDG_MAINMENEMAILChanging(string value);
    partial void OnDG_MAINMENEMAILChanged();
    partial void OnDG_MAINMENCOMMENTChanging(string value);
    partial void OnDG_MAINMENCOMMENTChanged();
    partial void OnDG_DUPUSERKEYChanging(System.Nullable<int> value);
    partial void OnDG_DUPUSERKEYChanged();
    partial void OnDG_BTKEYChanging(System.Nullable<int> value);
    partial void OnDG_BTKEYChanged();
    partial void OnDG_INVOICECOSTChanging(string value);
    partial void OnDG_INVOICECOSTChanged();
    partial void OnDG_ConfirmedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDG_ConfirmedDateChanged();
    partial void OnDG_PRTDOGKEYChanging(int value);
    partial void OnDG_PRTDOGKEYChanged();
    partial void OnDG_CTDepartureKeyChanging(System.Nullable<int> value);
    partial void OnDG_CTDepartureKeyChanged();
    partial void OnDG_SalePriceChanging(System.Nullable<decimal> value);
    partial void OnDG_SalePriceChanged();
    partial void OnDG_SaleDiscountChanging(System.Nullable<decimal> value);
    partial void OnDG_SaleDiscountChanged();
    partial void OnDG_PDTTypeChanging(short value);
    partial void OnDG_PDTTypeChanged();
    partial void OnDG_NATIONALCURRENCYPRICEChanging(System.Nullable<decimal> value);
    partial void OnDG_NATIONALCURRENCYPRICEChanged();
    partial void OnDG_NATIONALCURRENCYDISCOUNTSUMChanging(System.Nullable<decimal> value);
    partial void OnDG_NATIONALCURRENCYDISCOUNTSUMChanged();
    partial void OnDG_DAKeyChanging(System.Nullable<int> value);
    partial void OnDG_DAKeyChanged();
    partial void OnDG_NATIONALCURRENCYPAYEDChanging(System.Nullable<decimal> value);
    partial void OnDG_NATIONALCURRENCYPAYEDChanged();
    #endregion
		
		public tbl_Dogovor()
		{
			this._tbl_DogovorLists = new EntitySet<tbl_DogovorList>(new Action<tbl_DogovorList>(this.attach_tbl_DogovorLists), new Action<tbl_DogovorList>(this.detach_tbl_DogovorLists));
			this._Lanta_RouteCertificateAdmins = new EntitySet<Lanta_RouteCertificateAdmin>(new Action<Lanta_RouteCertificateAdmin>(this.attach_Lanta_RouteCertificateAdmins), new Action<Lanta_RouteCertificateAdmin>(this.detach_Lanta_RouteCertificateAdmins));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_CODE", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DG_CODE
		{
			get
			{
				return this._DG_CODE;
			}
			set
			{
				if ((this._DG_CODE != value))
				{
					this.OnDG_CODEChanging(value);
					this.SendPropertyChanging();
					this._DG_CODE = value;
					this.SendPropertyChanged("DG_CODE");
					this.OnDG_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_TURDATE", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime DG_TURDATE
		{
			get
			{
				return this._DG_TURDATE;
			}
			set
			{
				if ((this._DG_TURDATE != value))
				{
					this.OnDG_TURDATEChanging(value);
					this.SendPropertyChanging();
					this._DG_TURDATE = value;
					this.SendPropertyChanged("DG_TURDATE");
					this.OnDG_TURDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_TRKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_TRKEY
		{
			get
			{
				return this._DG_TRKEY;
			}
			set
			{
				if ((this._DG_TRKEY != value))
				{
					this.OnDG_TRKEYChanging(value);
					this.SendPropertyChanging();
					this._DG_TRKEY = value;
					this.SendPropertyChanged("DG_TRKEY");
					this.OnDG_TRKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_CNKEY", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DG_CNKEY
		{
			get
			{
				return this._DG_CNKEY;
			}
			set
			{
				if ((this._DG_CNKEY != value))
				{
					this.OnDG_CNKEYChanging(value);
					this.SendPropertyChanging();
					this._DG_CNKEY = value;
					this.SendPropertyChanged("DG_CNKEY");
					this.OnDG_CNKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_CTKEY", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DG_CTKEY
		{
			get
			{
				return this._DG_CTKEY;
			}
			set
			{
				if ((this._DG_CTKEY != value))
				{
					this.OnDG_CTKEYChanging(value);
					this.SendPropertyChanging();
					this._DG_CTKEY = value;
					this.SendPropertyChanged("DG_CTKEY");
					this.OnDG_CTKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_NMEN", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> DG_NMEN
		{
			get
			{
				return this._DG_NMEN;
			}
			set
			{
				if ((this._DG_NMEN != value))
				{
					this.OnDG_NMENChanging(value);
					this.SendPropertyChanging();
					this._DG_NMEN = value;
					this.SendPropertyChanged("DG_NMEN");
					this.OnDG_NMENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_PRICE", DbType="Money NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal DG_PRICE
		{
			get
			{
				return this._DG_PRICE;
			}
			set
			{
				if ((this._DG_PRICE != value))
				{
					this.OnDG_PRICEChanging(value);
					this.SendPropertyChanging();
					this._DG_PRICE = value;
					this.SendPropertyChanged("DG_PRICE");
					this.OnDG_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_PAYED", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DG_PAYED
		{
			get
			{
				return this._DG_PAYED;
			}
			set
			{
				if ((this._DG_PAYED != value))
				{
					this.OnDG_PAYEDChanging(value);
					this.SendPropertyChanging();
					this._DG_PAYED = value;
					this.SendPropertyChanged("DG_PAYED");
					this.OnDG_PAYEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_NDAY", DbType="Float NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public double DG_NDAY
		{
			get
			{
				return this._DG_NDAY;
			}
			set
			{
				if ((this._DG_NDAY != value))
				{
					this.OnDG_NDAYChanging(value);
					this.SendPropertyChanging();
					this._DG_NDAY = value;
					this.SendPropertyChanged("DG_NDAY");
					this.OnDG_NDAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_MAINMEN", DbType="VarChar(70)", UpdateCheck=UpdateCheck.Never)]
		public string DG_MAINMEN
		{
			get
			{
				return this._DG_MAINMEN;
			}
			set
			{
				if ((this._DG_MAINMEN != value))
				{
					this.OnDG_MAINMENChanging(value);
					this.SendPropertyChanging();
					this._DG_MAINMEN = value;
					this.SendPropertyChanged("DG_MAINMEN");
					this.OnDG_MAINMENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_MAINMENPHONE", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string DG_MAINMENPHONE
		{
			get
			{
				return this._DG_MAINMENPHONE;
			}
			set
			{
				if ((this._DG_MAINMENPHONE != value))
				{
					this.OnDG_MAINMENPHONEChanging(value);
					this.SendPropertyChanging();
					this._DG_MAINMENPHONE = value;
					this.SendPropertyChanged("DG_MAINMENPHONE");
					this.OnDG_MAINMENPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_MAINMENADRESS", DbType="VarChar(320)", UpdateCheck=UpdateCheck.Never)]
		public string DG_MAINMENADRESS
		{
			get
			{
				return this._DG_MAINMENADRESS;
			}
			set
			{
				if ((this._DG_MAINMENADRESS != value))
				{
					this.OnDG_MAINMENADRESSChanging(value);
					this.SendPropertyChanging();
					this._DG_MAINMENADRESS = value;
					this.SendPropertyChanged("DG_MAINMENADRESS");
					this.OnDG_MAINMENADRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_MAINMENPASPORT", DbType="VarChar(70)", UpdateCheck=UpdateCheck.Never)]
		public string DG_MAINMENPASPORT
		{
			get
			{
				return this._DG_MAINMENPASPORT;
			}
			set
			{
				if ((this._DG_MAINMENPASPORT != value))
				{
					this.OnDG_MAINMENPASPORTChanging(value);
					this.SendPropertyChanging();
					this._DG_MAINMENPASPORT = value;
					this.SendPropertyChanged("DG_MAINMENPASPORT");
					this.OnDG_MAINMENPASPORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_PARTNERKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_PARTNERKEY
		{
			get
			{
				return this._DG_PARTNERKEY;
			}
			set
			{
				if ((this._DG_PARTNERKEY != value))
				{
					this.OnDG_PARTNERKEYChanging(value);
					this.SendPropertyChanging();
					this._DG_PARTNERKEY = value;
					this.SendPropertyChanged("DG_PARTNERKEY");
					this.OnDG_PARTNERKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_OPERATOR", DbType="VarChar(25)", UpdateCheck=UpdateCheck.Never)]
		public string DG_OPERATOR
		{
			get
			{
				return this._DG_OPERATOR;
			}
			set
			{
				if ((this._DG_OPERATOR != value))
				{
					this.OnDG_OPERATORChanging(value);
					this.SendPropertyChanging();
					this._DG_OPERATOR = value;
					this.SendPropertyChanged("DG_OPERATOR");
					this.OnDG_OPERATORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_PRINTDOGOVOR", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> DG_PRINTDOGOVOR
		{
			get
			{
				return this._DG_PRINTDOGOVOR;
			}
			set
			{
				if ((this._DG_PRINTDOGOVOR != value))
				{
					this.OnDG_PRINTDOGOVORChanging(value);
					this.SendPropertyChanging();
					this._DG_PRINTDOGOVOR = value;
					this.SendPropertyChanged("DG_PRINTDOGOVOR");
					this.OnDG_PRINTDOGOVORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_PRINTVAUCHER", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> DG_PRINTVAUCHER
		{
			get
			{
				return this._DG_PRINTVAUCHER;
			}
			set
			{
				if ((this._DG_PRINTVAUCHER != value))
				{
					this.OnDG_PRINTVAUCHERChanging(value);
					this.SendPropertyChanging();
					this._DG_PRINTVAUCHER = value;
					this.SendPropertyChanged("DG_PRINTVAUCHER");
					this.OnDG_PRINTVAUCHERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_TYPECOUNT", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> DG_TYPECOUNT
		{
			get
			{
				return this._DG_TYPECOUNT;
			}
			set
			{
				if ((this._DG_TYPECOUNT != value))
				{
					this.OnDG_TYPECOUNTChanging(value);
					this.SendPropertyChanging();
					this._DG_TYPECOUNT = value;
					this.SendPropertyChanged("DG_TYPECOUNT");
					this.OnDG_TYPECOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_DISCOUNT", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DG_DISCOUNT
		{
			get
			{
				return this._DG_DISCOUNT;
			}
			set
			{
				if ((this._DG_DISCOUNT != value))
				{
					this.OnDG_DISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._DG_DISCOUNT = value;
					this.SendPropertyChanged("DG_DISCOUNT");
					this.OnDG_DISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_DISCOUNTSUM", DbType="Money NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal DG_DISCOUNTSUM
		{
			get
			{
				return this._DG_DISCOUNTSUM;
			}
			set
			{
				if ((this._DG_DISCOUNTSUM != value))
				{
					this.OnDG_DISCOUNTSUMChanging(value);
					this.SendPropertyChanging();
					this._DG_DISCOUNTSUM = value;
					this.SendPropertyChanged("DG_DISCOUNTSUM");
					this.OnDG_DISCOUNTSUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_CREATOR", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DG_CREATOR
		{
			get
			{
				return this._DG_CREATOR;
			}
			set
			{
				if ((this._DG_CREATOR != value))
				{
					this.OnDG_CREATORChanging(value);
					this.SendPropertyChanging();
					this._DG_CREATOR = value;
					this.SendPropertyChanged("DG_CREATOR");
					this.OnDG_CREATORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_OWNER", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DG_OWNER
		{
			get
			{
				return this._DG_OWNER;
			}
			set
			{
				if ((this._DG_OWNER != value))
				{
					this.OnDG_OWNERChanging(value);
					this.SendPropertyChanging();
					this._DG_OWNER = value;
					this.SendPropertyChanged("DG_OWNER");
					this.OnDG_OWNERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_SOR_CODE", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DG_SOR_CODE
		{
			get
			{
				return this._DG_SOR_CODE;
			}
			set
			{
				if ((this._DG_SOR_CODE != value))
				{
					this.OnDG_SOR_CODEChanging(value);
					this.SendPropertyChanging();
					this._DG_SOR_CODE = value;
					this.SendPropertyChanged("DG_SOR_CODE");
					this.OnDG_SOR_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_CRDATE", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime DG_CRDATE
		{
			get
			{
				return this._DG_CRDATE;
			}
			set
			{
				if ((this._DG_CRDATE != value))
				{
					this.OnDG_CRDATEChanging(value);
					this.SendPropertyChanging();
					this._DG_CRDATE = value;
					this.SendPropertyChanged("DG_CRDATE");
					this.OnDG_CRDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_RATE", DbType="VarChar(3)", UpdateCheck=UpdateCheck.Never)]
		public string DG_RATE
		{
			get
			{
				return this._DG_RATE;
			}
			set
			{
				if ((this._DG_RATE != value))
				{
					this.OnDG_RATEChanging(value);
					this.SendPropertyChanging();
					this._DG_RATE = value;
					this.SendPropertyChanged("DG_RATE");
					this.OnDG_RATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_ADVERTISE", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_ADVERTISE
		{
			get
			{
				return this._DG_ADVERTISE;
			}
			set
			{
				if ((this._DG_ADVERTISE != value))
				{
					this.OnDG_ADVERTISEChanging(value);
					this.SendPropertyChanging();
					this._DG_ADVERTISE = value;
					this.SendPropertyChanged("DG_ADVERTISE");
					this.OnDG_ADVERTISEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_LOCKED", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> DG_LOCKED
		{
			get
			{
				return this._DG_LOCKED;
			}
			set
			{
				if ((this._DG_LOCKED != value))
				{
					this.OnDG_LOCKEDChanging(value);
					this.SendPropertyChanging();
					this._DG_LOCKED = value;
					this.SendPropertyChanged("DG_LOCKED");
					this.OnDG_LOCKEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_CAUSEDISC", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_CAUSEDISC
		{
			get
			{
				return this._DG_CAUSEDISC;
			}
			set
			{
				if ((this._DG_CAUSEDISC != value))
				{
					this.OnDG_CAUSEDISCChanging(value);
					this.SendPropertyChanging();
					this._DG_CAUSEDISC = value;
					this.SendPropertyChanged("DG_CAUSEDISC");
					this.OnDG_CAUSEDISCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_VISADATE", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DG_VISADATE
		{
			get
			{
				return this._DG_VISADATE;
			}
			set
			{
				if ((this._DG_VISADATE != value))
				{
					this.OnDG_VISADATEChanging(value);
					this.SendPropertyChanging();
					this._DG_VISADATE = value;
					this.SendPropertyChanged("DG_VISADATE");
					this.OnDG_VISADATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_PPAYMENTDATE", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DG_PPAYMENTDATE
		{
			get
			{
				return this._DG_PPAYMENTDATE;
			}
			set
			{
				if ((this._DG_PPAYMENTDATE != value))
				{
					this.OnDG_PPAYMENTDATEChanging(value);
					this.SendPropertyChanging();
					this._DG_PPAYMENTDATE = value;
					this.SendPropertyChanged("DG_PPAYMENTDATE");
					this.OnDG_PPAYMENTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_PAYMENTDATE", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DG_PAYMENTDATE
		{
			get
			{
				return this._DG_PAYMENTDATE;
			}
			set
			{
				if ((this._DG_PAYMENTDATE != value))
				{
					this.OnDG_PAYMENTDATEChanging(value);
					this.SendPropertyChanging();
					this._DG_PAYMENTDATE = value;
					this.SendPropertyChanged("DG_PAYMENTDATE");
					this.OnDG_PAYMENTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_TURPUTDATE", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DG_TURPUTDATE
		{
			get
			{
				return this._DG_TURPUTDATE;
			}
			set
			{
				if ((this._DG_TURPUTDATE != value))
				{
					this.OnDG_TURPUTDATEChanging(value);
					this.SendPropertyChanging();
					this._DG_TURPUTDATE = value;
					this.SendPropertyChanged("DG_TURPUTDATE");
					this.OnDG_TURPUTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_DOCUMENT", DbType="VarChar(250)", UpdateCheck=UpdateCheck.Never)]
		public string DG_DOCUMENT
		{
			get
			{
				return this._DG_DOCUMENT;
			}
			set
			{
				if ((this._DG_DOCUMENT != value))
				{
					this.OnDG_DOCUMENTChanging(value);
					this.SendPropertyChanging();
					this._DG_DOCUMENT = value;
					this.SendPropertyChanged("DG_DOCUMENT");
					this.OnDG_DOCUMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_TURPUTPLACE", DbType="VarChar(128)", UpdateCheck=UpdateCheck.Never)]
		public string DG_TURPUTPLACE
		{
			get
			{
				return this._DG_TURPUTPLACE;
			}
			set
			{
				if ((this._DG_TURPUTPLACE != value))
				{
					this.OnDG_TURPUTPLACEChanging(value);
					this.SendPropertyChanging();
					this._DG_TURPUTPLACE = value;
					this.SendPropertyChanged("DG_TURPUTPLACE");
					this.OnDG_TURPUTPLACEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_PROCENT", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_PROCENT
		{
			get
			{
				return this._DG_PROCENT;
			}
			set
			{
				if ((this._DG_PROCENT != value))
				{
					this.OnDG_PROCENTChanging(value);
					this.SendPropertyChanging();
					this._DG_PROCENT = value;
					this.SendPropertyChanged("DG_PROCENT");
					this.OnDG_PROCENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_OLDTOURDATE", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DG_OLDTOURDATE
		{
			get
			{
				return this._DG_OLDTOURDATE;
			}
			set
			{
				if ((this._DG_OLDTOURDATE != value))
				{
					this.OnDG_OLDTOURDATEChanging(value);
					this.SendPropertyChanging();
					this._DG_OLDTOURDATE = value;
					this.SendPropertyChanged("DG_OLDTOURDATE");
					this.OnDG_OLDTOURDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWID", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ROWID
		{
			get
			{
				return this._ROWID;
			}
			set
			{
				if ((this._ROWID != value))
				{
					this.OnROWIDChanging(value);
					this.SendPropertyChanging();
					this._ROWID = value;
					this.SendPropertyChanged("ROWID");
					this.OnROWIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_TurDateBfrAnnul", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DG_TurDateBfrAnnul
		{
			get
			{
				return this._DG_TurDateBfrAnnul;
			}
			set
			{
				if ((this._DG_TurDateBfrAnnul != value))
				{
					this.OnDG_TurDateBfrAnnulChanging(value);
					this.SendPropertyChanging();
					this._DG_TurDateBfrAnnul = value;
					this.SendPropertyChanged("DG_TurDateBfrAnnul");
					this.OnDG_TurDateBfrAnnulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_ARKey", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_ARKey
		{
			get
			{
				return this._DG_ARKey;
			}
			set
			{
				if ((this._DG_ARKey != value))
				{
					this.OnDG_ARKeyChanging(value);
					this.SendPropertyChanging();
					this._DG_ARKey = value;
					this.SendPropertyChanged("DG_ARKey");
					this.OnDG_ARKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_Key", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int DG_Key
		{
			get
			{
				return this._DG_Key;
			}
			set
			{
				if ((this._DG_Key != value))
				{
					this.OnDG_KeyChanging(value);
					this.SendPropertyChanging();
					this._DG_Key = value;
					this.SendPropertyChanged("DG_Key");
					this.OnDG_KeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_CodePartner", DbType="VarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string DG_CodePartner
		{
			get
			{
				return this._DG_CodePartner;
			}
			set
			{
				if ((this._DG_CodePartner != value))
				{
					this.OnDG_CodePartnerChanging(value);
					this.SendPropertyChanging();
					this._DG_CodePartner = value;
					this.SendPropertyChanged("DG_CodePartner");
					this.OnDG_CodePartnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_FilialKey", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DG_FilialKey
		{
			get
			{
				return this._DG_FilialKey;
			}
			set
			{
				if ((this._DG_FilialKey != value))
				{
					this.OnDG_FilialKeyChanging(value);
					this.SendPropertyChanging();
					this._DG_FilialKey = value;
					this.SendPropertyChanged("DG_FilialKey");
					this.OnDG_FilialKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_IsOutDoc", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DG_IsOutDoc
		{
			get
			{
				return this._DG_IsOutDoc;
			}
			set
			{
				if ((this._DG_IsOutDoc != value))
				{
					this.OnDG_IsOutDocChanging(value);
					this.SendPropertyChanging();
					this._DG_IsOutDoc = value;
					this.SendPropertyChanged("DG_IsOutDoc");
					this.OnDG_IsOutDocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_AgentID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_AgentID
		{
			get
			{
				return this._DG_AgentID;
			}
			set
			{
				if ((this._DG_AgentID != value))
				{
					this.OnDG_AgentIDChanging(value);
					this.SendPropertyChanging();
					this._DG_AgentID = value;
					this.SendPropertyChanged("DG_AgentID");
					this.OnDG_AgentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_DISCSUMBFRANN", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DG_DISCSUMBFRANN
		{
			get
			{
				return this._DG_DISCSUMBFRANN;
			}
			set
			{
				if ((this._DG_DISCSUMBFRANN != value))
				{
					this.OnDG_DISCSUMBFRANNChanging(value);
					this.SendPropertyChanging();
					this._DG_DISCSUMBFRANN = value;
					this.SendPropertyChanged("DG_DISCSUMBFRANN");
					this.OnDG_DISCSUMBFRANNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_PRICEBFRANN", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DG_PRICEBFRANN
		{
			get
			{
				return this._DG_PRICEBFRANN;
			}
			set
			{
				if ((this._DG_PRICEBFRANN != value))
				{
					this.OnDG_PRICEBFRANNChanging(value);
					this.SendPropertyChanging();
					this._DG_PRICEBFRANN = value;
					this.SendPropertyChanged("DG_PRICEBFRANN");
					this.OnDG_PRICEBFRANNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_TRANSFERRED", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> DG_TRANSFERRED
		{
			get
			{
				return this._DG_TRANSFERRED;
			}
			set
			{
				if ((this._DG_TRANSFERRED != value))
				{
					this.OnDG_TRANSFERREDChanging(value);
					this.SendPropertyChanging();
					this._DG_TRANSFERRED = value;
					this.SendPropertyChanged("DG_TRANSFERRED");
					this.OnDG_TRANSFERREDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_NOTES", DbType="VarChar(250)", UpdateCheck=UpdateCheck.Never)]
		public string DG_NOTES
		{
			get
			{
				return this._DG_NOTES;
			}
			set
			{
				if ((this._DG_NOTES != value))
				{
					this.OnDG_NOTESChanging(value);
					this.SendPropertyChanging();
					this._DG_NOTES = value;
					this.SendPropertyChanged("DG_NOTES");
					this.OnDG_NOTESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_DCRCLIENT", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_DCRCLIENT
		{
			get
			{
				return this._DG_DCRCLIENT;
			}
			set
			{
				if ((this._DG_DCRCLIENT != value))
				{
					this.OnDG_DCRCLIENTChanging(value);
					this.SendPropertyChanging();
					this._DG_DCRCLIENT = value;
					this.SendPropertyChanged("DG_DCRCLIENT");
					this.OnDG_DCRCLIENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_DCRPAYMENT", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_DCRPAYMENT
		{
			get
			{
				return this._DG_DCRPAYMENT;
			}
			set
			{
				if ((this._DG_DCRPAYMENT != value))
				{
					this.OnDG_DCRPAYMENTChanging(value);
					this.SendPropertyChanging();
					this._DG_DCRPAYMENT = value;
					this.SendPropertyChanged("DG_DCRPAYMENT");
					this.OnDG_DCRPAYMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_ISMAKEDISCOUNT", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_ISMAKEDISCOUNT
		{
			get
			{
				return this._DG_ISMAKEDISCOUNT;
			}
			set
			{
				if ((this._DG_ISMAKEDISCOUNT != value))
				{
					this.OnDG_ISMAKEDISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._DG_ISMAKEDISCOUNT = value;
					this.SendPropertyChanged("DG_ISMAKEDISCOUNT");
					this.OnDG_ISMAKEDISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_RazmerP", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DG_RazmerP
		{
			get
			{
				return this._DG_RazmerP;
			}
			set
			{
				if ((this._DG_RazmerP != value))
				{
					this.OnDG_RazmerPChanging(value);
					this.SendPropertyChanging();
					this._DG_RazmerP = value;
					this.SendPropertyChanged("DG_RazmerP");
					this.OnDG_RazmerPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_LEADDEPARTMENT", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DG_LEADDEPARTMENT
		{
			get
			{
				return this._DG_LEADDEPARTMENT;
			}
			set
			{
				if ((this._DG_LEADDEPARTMENT != value))
				{
					this.OnDG_LEADDEPARTMENTChanging(value);
					this.SendPropertyChanging();
					this._DG_LEADDEPARTMENT = value;
					this.SendPropertyChanged("DG_LEADDEPARTMENT");
					this.OnDG_LEADDEPARTMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_MAINMENEMAIL", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string DG_MAINMENEMAIL
		{
			get
			{
				return this._DG_MAINMENEMAIL;
			}
			set
			{
				if ((this._DG_MAINMENEMAIL != value))
				{
					this.OnDG_MAINMENEMAILChanging(value);
					this.SendPropertyChanging();
					this._DG_MAINMENEMAIL = value;
					this.SendPropertyChanged("DG_MAINMENEMAIL");
					this.OnDG_MAINMENEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_MAINMENCOMMENT", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string DG_MAINMENCOMMENT
		{
			get
			{
				return this._DG_MAINMENCOMMENT;
			}
			set
			{
				if ((this._DG_MAINMENCOMMENT != value))
				{
					this.OnDG_MAINMENCOMMENTChanging(value);
					this.SendPropertyChanging();
					this._DG_MAINMENCOMMENT = value;
					this.SendPropertyChanged("DG_MAINMENCOMMENT");
					this.OnDG_MAINMENCOMMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_DUPUSERKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_DUPUSERKEY
		{
			get
			{
				return this._DG_DUPUSERKEY;
			}
			set
			{
				if ((this._DG_DUPUSERKEY != value))
				{
					this.OnDG_DUPUSERKEYChanging(value);
					this.SendPropertyChanging();
					this._DG_DUPUSERKEY = value;
					this.SendPropertyChanged("DG_DUPUSERKEY");
					this.OnDG_DUPUSERKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_BTKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_BTKEY
		{
			get
			{
				return this._DG_BTKEY;
			}
			set
			{
				if ((this._DG_BTKEY != value))
				{
					this.OnDG_BTKEYChanging(value);
					this.SendPropertyChanging();
					this._DG_BTKEY = value;
					this.SendPropertyChanged("DG_BTKEY");
					this.OnDG_BTKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_INVOICECOST", DbType="VarChar(80)", UpdateCheck=UpdateCheck.Never)]
		public string DG_INVOICECOST
		{
			get
			{
				return this._DG_INVOICECOST;
			}
			set
			{
				if ((this._DG_INVOICECOST != value))
				{
					this.OnDG_INVOICECOSTChanging(value);
					this.SendPropertyChanging();
					this._DG_INVOICECOST = value;
					this.SendPropertyChanged("DG_INVOICECOST");
					this.OnDG_INVOICECOSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_ConfirmedDate", DbType="SmallDateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DG_ConfirmedDate
		{
			get
			{
				return this._DG_ConfirmedDate;
			}
			set
			{
				if ((this._DG_ConfirmedDate != value))
				{
					this.OnDG_ConfirmedDateChanging(value);
					this.SendPropertyChanging();
					this._DG_ConfirmedDate = value;
					this.SendPropertyChanged("DG_ConfirmedDate");
					this.OnDG_ConfirmedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_PRTDOGKEY", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DG_PRTDOGKEY
		{
			get
			{
				return this._DG_PRTDOGKEY;
			}
			set
			{
				if ((this._DG_PRTDOGKEY != value))
				{
					this.OnDG_PRTDOGKEYChanging(value);
					this.SendPropertyChanging();
					this._DG_PRTDOGKEY = value;
					this.SendPropertyChanged("DG_PRTDOGKEY");
					this.OnDG_PRTDOGKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_CTDepartureKey", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_CTDepartureKey
		{
			get
			{
				return this._DG_CTDepartureKey;
			}
			set
			{
				if ((this._DG_CTDepartureKey != value))
				{
					this.OnDG_CTDepartureKeyChanging(value);
					this.SendPropertyChanging();
					this._DG_CTDepartureKey = value;
					this.SendPropertyChanged("DG_CTDepartureKey");
					this.OnDG_CTDepartureKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_SalePrice", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DG_SalePrice
		{
			get
			{
				return this._DG_SalePrice;
			}
			set
			{
				if ((this._DG_SalePrice != value))
				{
					this.OnDG_SalePriceChanging(value);
					this.SendPropertyChanging();
					this._DG_SalePrice = value;
					this.SendPropertyChanged("DG_SalePrice");
					this.OnDG_SalePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_SaleDiscount", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DG_SaleDiscount
		{
			get
			{
				return this._DG_SaleDiscount;
			}
			set
			{
				if ((this._DG_SaleDiscount != value))
				{
					this.OnDG_SaleDiscountChanging(value);
					this.SendPropertyChanging();
					this._DG_SaleDiscount = value;
					this.SendPropertyChanged("DG_SaleDiscount");
					this.OnDG_SaleDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_PDTType", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short DG_PDTType
		{
			get
			{
				return this._DG_PDTType;
			}
			set
			{
				if ((this._DG_PDTType != value))
				{
					this.OnDG_PDTTypeChanging(value);
					this.SendPropertyChanging();
					this._DG_PDTType = value;
					this.SendPropertyChanged("DG_PDTType");
					this.OnDG_PDTTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_NATIONALCURRENCYPRICE", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DG_NATIONALCURRENCYPRICE
		{
			get
			{
				return this._DG_NATIONALCURRENCYPRICE;
			}
			set
			{
				if ((this._DG_NATIONALCURRENCYPRICE != value))
				{
					this.OnDG_NATIONALCURRENCYPRICEChanging(value);
					this.SendPropertyChanging();
					this._DG_NATIONALCURRENCYPRICE = value;
					this.SendPropertyChanged("DG_NATIONALCURRENCYPRICE");
					this.OnDG_NATIONALCURRENCYPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_NATIONALCURRENCYDISCOUNTSUM", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DG_NATIONALCURRENCYDISCOUNTSUM
		{
			get
			{
				return this._DG_NATIONALCURRENCYDISCOUNTSUM;
			}
			set
			{
				if ((this._DG_NATIONALCURRENCYDISCOUNTSUM != value))
				{
					this.OnDG_NATIONALCURRENCYDISCOUNTSUMChanging(value);
					this.SendPropertyChanging();
					this._DG_NATIONALCURRENCYDISCOUNTSUM = value;
					this.SendPropertyChanged("DG_NATIONALCURRENCYDISCOUNTSUM");
					this.OnDG_NATIONALCURRENCYDISCOUNTSUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_DAKey", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DG_DAKey
		{
			get
			{
				return this._DG_DAKey;
			}
			set
			{
				if ((this._DG_DAKey != value))
				{
					this.OnDG_DAKeyChanging(value);
					this.SendPropertyChanging();
					this._DG_DAKey = value;
					this.SendPropertyChanged("DG_DAKey");
					this.OnDG_DAKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_NATIONALCURRENCYPAYED", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DG_NATIONALCURRENCYPAYED
		{
			get
			{
				return this._DG_NATIONALCURRENCYPAYED;
			}
			set
			{
				if ((this._DG_NATIONALCURRENCYPAYED != value))
				{
					this.OnDG_NATIONALCURRENCYPAYEDChanging(value);
					this.SendPropertyChanging();
					this._DG_NATIONALCURRENCYPAYED = value;
					this.SendPropertyChanged("DG_NATIONALCURRENCYPAYED");
					this.OnDG_NATIONALCURRENCYPAYEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Dogovor_tbl_DogovorList", Storage="_tbl_DogovorLists", ThisKey="DG_Key", OtherKey="DL_DGKEY")]
		public EntitySet<tbl_DogovorList> tbl_DogovorLists
		{
			get
			{
				return this._tbl_DogovorLists;
			}
			set
			{
				this._tbl_DogovorLists.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Dogovor_Lanta_RouteCertificateAdmin", Storage="_Lanta_RouteCertificateAdmins", ThisKey="DG_Key", OtherKey="RCA_DGKey")]
		public EntitySet<Lanta_RouteCertificateAdmin> Lanta_RouteCertificateAdmins
		{
			get
			{
				return this._Lanta_RouteCertificateAdmins;
			}
			set
			{
				this._Lanta_RouteCertificateAdmins.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_DogovorLists(tbl_DogovorList entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Dogovor = this;
		}
		
		private void detach_tbl_DogovorLists(tbl_DogovorList entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Dogovor = null;
		}
		
		private void attach_Lanta_RouteCertificateAdmins(Lanta_RouteCertificateAdmin entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Dogovor = this;
		}
		
		private void detach_Lanta_RouteCertificateAdmins(Lanta_RouteCertificateAdmin entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Dogovor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.History")]
	public partial class History : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _HI_DGCOD;
		
		private string _HI_WHO;
		
		private string _HI_TEXT;
		
		private string _HI_MOD;
		
		private int _HI_ID;
		
		private System.Nullable<int> _HI_MessEnabled;
		
		private System.Nullable<int> _HI_DGKEY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHI_DGCODChanging(string value);
    partial void OnHI_DGCODChanged();
    partial void OnHI_WHOChanging(string value);
    partial void OnHI_WHOChanged();
    partial void OnHI_TEXTChanging(string value);
    partial void OnHI_TEXTChanged();
    partial void OnHI_MODChanging(string value);
    partial void OnHI_MODChanged();
    partial void OnHI_IDChanging(int value);
    partial void OnHI_IDChanged();
    partial void OnHI_MessEnabledChanging(System.Nullable<int> value);
    partial void OnHI_MessEnabledChanged();
    partial void OnHI_DGKEYChanging(System.Nullable<int> value);
    partial void OnHI_DGKEYChanged();
    #endregion
		
		public History()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HI_DGCOD", DbType="VarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string HI_DGCOD
		{
			get
			{
				return this._HI_DGCOD;
			}
			set
			{
				if ((this._HI_DGCOD != value))
				{
					this.OnHI_DGCODChanging(value);
					this.SendPropertyChanging();
					this._HI_DGCOD = value;
					this.SendPropertyChanged("HI_DGCOD");
					this.OnHI_DGCODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HI_WHO", DbType="VarChar(25)", UpdateCheck=UpdateCheck.Never)]
		public string HI_WHO
		{
			get
			{
				return this._HI_WHO;
			}
			set
			{
				if ((this._HI_WHO != value))
				{
					this.OnHI_WHOChanging(value);
					this.SendPropertyChanging();
					this._HI_WHO = value;
					this.SendPropertyChanged("HI_WHO");
					this.OnHI_WHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HI_TEXT", DbType="VarChar(254)", UpdateCheck=UpdateCheck.Never)]
		public string HI_TEXT
		{
			get
			{
				return this._HI_TEXT;
			}
			set
			{
				if ((this._HI_TEXT != value))
				{
					this.OnHI_TEXTChanging(value);
					this.SendPropertyChanging();
					this._HI_TEXT = value;
					this.SendPropertyChanged("HI_TEXT");
					this.OnHI_TEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HI_MOD", DbType="VarChar(3)", UpdateCheck=UpdateCheck.Never)]
		public string HI_MOD
		{
			get
			{
				return this._HI_MOD;
			}
			set
			{
				if ((this._HI_MOD != value))
				{
					this.OnHI_MODChanging(value);
					this.SendPropertyChanging();
					this._HI_MOD = value;
					this.SendPropertyChanged("HI_MOD");
					this.OnHI_MODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HI_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int HI_ID
		{
			get
			{
				return this._HI_ID;
			}
			set
			{
				if ((this._HI_ID != value))
				{
					this.OnHI_IDChanging(value);
					this.SendPropertyChanging();
					this._HI_ID = value;
					this.SendPropertyChanged("HI_ID");
					this.OnHI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HI_MessEnabled", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> HI_MessEnabled
		{
			get
			{
				return this._HI_MessEnabled;
			}
			set
			{
				if ((this._HI_MessEnabled != value))
				{
					this.OnHI_MessEnabledChanging(value);
					this.SendPropertyChanging();
					this._HI_MessEnabled = value;
					this.SendPropertyChanged("HI_MessEnabled");
					this.OnHI_MessEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HI_DGKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> HI_DGKEY
		{
			get
			{
				return this._HI_DGKEY;
			}
			set
			{
				if ((this._HI_DGKEY != value))
				{
					this.OnHI_DGKEYChanging(value);
					this.SendPropertyChanging();
					this._HI_DGKEY = value;
					this.SendPropertyChanged("HI_DGKEY");
					this.OnHI_DGKEYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DogovorList")]
	public partial class tbl_DogovorList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DL_DGCOD;
		
		private System.Nullable<System.DateTime> _DL_TURDATE;
		
		private int _DL_KEY;
		
		private System.Nullable<int> _DL_PAKETKEY;
		
		private int _DL_TRKEY;
		
		private int _DL_SVKEY;
		
		private string _DL_NAME;
		
		private System.Nullable<short> _DL_DAY;
		
		private int _DL_CODE;
		
		private System.Nullable<int> _DL_SUBCODE1;
		
		private System.Nullable<int> _DL_SUBCODE2;
		
		private short _DL_NMEN;
		
		private System.Nullable<short> _DL_NDAYS;
		
		private System.Nullable<int> _DL_CNKEY;
		
		private System.Nullable<int> _DL_CTKEY;
		
		private System.Nullable<int> _DL_PARTNERKEY;
		
		private System.Nullable<decimal> _DL_COST;
		
		private System.Nullable<decimal> _DL_REALNETTO;
		
		private System.Nullable<decimal> _DL_BRUTTO;
		
		private System.Nullable<decimal> _DL_PAYED;
		
		private System.Nullable<short> _DL_WAIT;
		
		private System.Nullable<int> _DL_WARNING;
		
		private System.Nullable<System.DateTime> _DL_TIMEBEG;
		
		private int _DL_CONTROL;
		
		private int _DL_CREATOR;
		
		private int _DL_OWNER;
		
		private System.Nullable<int> _DL_ATTRIBUTE;
		
		private System.Nullable<short> _DL_ISPAYED;
		
		private System.Nullable<System.DateTime> _DL_DATEBEG;
		
		private System.Nullable<System.DateTime> _DL_DATEEND;
		
		private System.Nullable<double> _DL_DISCOUNT;
		
		private System.Nullable<int> _DL_QUOTEKEY;
		
		private System.Nullable<int> _DL_AGENT;
		
		private System.Data.Linq.Binary _ROWID;
		
		private System.Nullable<int> _DL_AgentID;
		
		private string _DL_Comment;
		
		private System.Nullable<int> _DL_Reserved;
		
		private System.Nullable<int> _DL_DGKEY;
		
		private string _DL_FORMULANETTO;
		
		private string _DL_FORMULABRUTTO;
		
		private System.Nullable<short> _DL_BLOCKED;
		
		private string _DL_NameLat;
		
		private System.Nullable<int> _DL_PRTDOGKEY;
		
		private System.Nullable<int> _DL_TAXZONEID;
		
		private short _DL_Long;
		
		private System.Nullable<short> _DL_IsDeleted;
		
		private System.Nullable<decimal> _DL_SalePrice;
		
		private System.Nullable<decimal> _DL_SaleDiscount;
		
		private string _DL_FormulaDiscount;
		
		private EntityRef<tbl_Dogovor> _tbl_Dogovor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDL_DGCODChanging(string value);
    partial void OnDL_DGCODChanged();
    partial void OnDL_TURDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDL_TURDATEChanged();
    partial void OnDL_KEYChanging(int value);
    partial void OnDL_KEYChanged();
    partial void OnDL_PAKETKEYChanging(System.Nullable<int> value);
    partial void OnDL_PAKETKEYChanged();
    partial void OnDL_TRKEYChanging(int value);
    partial void OnDL_TRKEYChanged();
    partial void OnDL_SVKEYChanging(int value);
    partial void OnDL_SVKEYChanged();
    partial void OnDL_NAMEChanging(string value);
    partial void OnDL_NAMEChanged();
    partial void OnDL_DAYChanging(System.Nullable<short> value);
    partial void OnDL_DAYChanged();
    partial void OnDL_CODEChanging(int value);
    partial void OnDL_CODEChanged();
    partial void OnDL_SUBCODE1Changing(System.Nullable<int> value);
    partial void OnDL_SUBCODE1Changed();
    partial void OnDL_SUBCODE2Changing(System.Nullable<int> value);
    partial void OnDL_SUBCODE2Changed();
    partial void OnDL_NMENChanging(short value);
    partial void OnDL_NMENChanged();
    partial void OnDL_NDAYSChanging(System.Nullable<short> value);
    partial void OnDL_NDAYSChanged();
    partial void OnDL_CNKEYChanging(System.Nullable<int> value);
    partial void OnDL_CNKEYChanged();
    partial void OnDL_CTKEYChanging(System.Nullable<int> value);
    partial void OnDL_CTKEYChanged();
    partial void OnDL_PARTNERKEYChanging(System.Nullable<int> value);
    partial void OnDL_PARTNERKEYChanged();
    partial void OnDL_COSTChanging(System.Nullable<decimal> value);
    partial void OnDL_COSTChanged();
    partial void OnDL_REALNETTOChanging(System.Nullable<decimal> value);
    partial void OnDL_REALNETTOChanged();
    partial void OnDL_BRUTTOChanging(System.Nullable<decimal> value);
    partial void OnDL_BRUTTOChanged();
    partial void OnDL_PAYEDChanging(System.Nullable<decimal> value);
    partial void OnDL_PAYEDChanged();
    partial void OnDL_WAITChanging(System.Nullable<short> value);
    partial void OnDL_WAITChanged();
    partial void OnDL_WARNINGChanging(System.Nullable<int> value);
    partial void OnDL_WARNINGChanged();
    partial void OnDL_TIMEBEGChanging(System.Nullable<System.DateTime> value);
    partial void OnDL_TIMEBEGChanged();
    partial void OnDL_CONTROLChanging(int value);
    partial void OnDL_CONTROLChanged();
    partial void OnDL_CREATORChanging(int value);
    partial void OnDL_CREATORChanged();
    partial void OnDL_OWNERChanging(int value);
    partial void OnDL_OWNERChanged();
    partial void OnDL_ATTRIBUTEChanging(System.Nullable<int> value);
    partial void OnDL_ATTRIBUTEChanged();
    partial void OnDL_ISPAYEDChanging(System.Nullable<short> value);
    partial void OnDL_ISPAYEDChanged();
    partial void OnDL_DATEBEGChanging(System.Nullable<System.DateTime> value);
    partial void OnDL_DATEBEGChanged();
    partial void OnDL_DATEENDChanging(System.Nullable<System.DateTime> value);
    partial void OnDL_DATEENDChanged();
    partial void OnDL_DISCOUNTChanging(System.Nullable<double> value);
    partial void OnDL_DISCOUNTChanged();
    partial void OnDL_QUOTEKEYChanging(System.Nullable<int> value);
    partial void OnDL_QUOTEKEYChanged();
    partial void OnDL_AGENTChanging(System.Nullable<int> value);
    partial void OnDL_AGENTChanged();
    partial void OnROWIDChanging(System.Data.Linq.Binary value);
    partial void OnROWIDChanged();
    partial void OnDL_AgentIDChanging(System.Nullable<int> value);
    partial void OnDL_AgentIDChanged();
    partial void OnDL_CommentChanging(string value);
    partial void OnDL_CommentChanged();
    partial void OnDL_ReservedChanging(System.Nullable<int> value);
    partial void OnDL_ReservedChanged();
    partial void OnDL_DGKEYChanging(System.Nullable<int> value);
    partial void OnDL_DGKEYChanged();
    partial void OnDL_FORMULANETTOChanging(string value);
    partial void OnDL_FORMULANETTOChanged();
    partial void OnDL_FORMULABRUTTOChanging(string value);
    partial void OnDL_FORMULABRUTTOChanged();
    partial void OnDL_BLOCKEDChanging(System.Nullable<short> value);
    partial void OnDL_BLOCKEDChanged();
    partial void OnDL_NameLatChanging(string value);
    partial void OnDL_NameLatChanged();
    partial void OnDL_PRTDOGKEYChanging(System.Nullable<int> value);
    partial void OnDL_PRTDOGKEYChanged();
    partial void OnDL_TAXZONEIDChanging(System.Nullable<int> value);
    partial void OnDL_TAXZONEIDChanged();
    partial void OnDL_LongChanging(short value);
    partial void OnDL_LongChanged();
    partial void OnDL_IsDeletedChanging(System.Nullable<short> value);
    partial void OnDL_IsDeletedChanged();
    partial void OnDL_SalePriceChanging(System.Nullable<decimal> value);
    partial void OnDL_SalePriceChanged();
    partial void OnDL_SaleDiscountChanging(System.Nullable<decimal> value);
    partial void OnDL_SaleDiscountChanged();
    partial void OnDL_FormulaDiscountChanging(string value);
    partial void OnDL_FormulaDiscountChanged();
    #endregion
		
		public tbl_DogovorList()
		{
			this._tbl_Dogovor = default(EntityRef<tbl_Dogovor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_DGCOD", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DL_DGCOD
		{
			get
			{
				return this._DL_DGCOD;
			}
			set
			{
				if ((this._DL_DGCOD != value))
				{
					this.OnDL_DGCODChanging(value);
					this.SendPropertyChanging();
					this._DL_DGCOD = value;
					this.SendPropertyChanged("DL_DGCOD");
					this.OnDL_DGCODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_TURDATE", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DL_TURDATE
		{
			get
			{
				return this._DL_TURDATE;
			}
			set
			{
				if ((this._DL_TURDATE != value))
				{
					this.OnDL_TURDATEChanging(value);
					this.SendPropertyChanging();
					this._DL_TURDATE = value;
					this.SendPropertyChanged("DL_TURDATE");
					this.OnDL_TURDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_KEY", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int DL_KEY
		{
			get
			{
				return this._DL_KEY;
			}
			set
			{
				if ((this._DL_KEY != value))
				{
					this.OnDL_KEYChanging(value);
					this.SendPropertyChanging();
					this._DL_KEY = value;
					this.SendPropertyChanged("DL_KEY");
					this.OnDL_KEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_PAKETKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_PAKETKEY
		{
			get
			{
				return this._DL_PAKETKEY;
			}
			set
			{
				if ((this._DL_PAKETKEY != value))
				{
					this.OnDL_PAKETKEYChanging(value);
					this.SendPropertyChanging();
					this._DL_PAKETKEY = value;
					this.SendPropertyChanged("DL_PAKETKEY");
					this.OnDL_PAKETKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_TRKEY", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DL_TRKEY
		{
			get
			{
				return this._DL_TRKEY;
			}
			set
			{
				if ((this._DL_TRKEY != value))
				{
					this.OnDL_TRKEYChanging(value);
					this.SendPropertyChanging();
					this._DL_TRKEY = value;
					this.SendPropertyChanged("DL_TRKEY");
					this.OnDL_TRKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_SVKEY", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DL_SVKEY
		{
			get
			{
				return this._DL_SVKEY;
			}
			set
			{
				if ((this._DL_SVKEY != value))
				{
					this.OnDL_SVKEYChanging(value);
					this.SendPropertyChanging();
					this._DL_SVKEY = value;
					this.SendPropertyChanged("DL_SVKEY");
					this.OnDL_SVKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_NAME", DbType="VarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string DL_NAME
		{
			get
			{
				return this._DL_NAME;
			}
			set
			{
				if ((this._DL_NAME != value))
				{
					this.OnDL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DL_NAME = value;
					this.SendPropertyChanged("DL_NAME");
					this.OnDL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_DAY", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> DL_DAY
		{
			get
			{
				return this._DL_DAY;
			}
			set
			{
				if ((this._DL_DAY != value))
				{
					this.OnDL_DAYChanging(value);
					this.SendPropertyChanging();
					this._DL_DAY = value;
					this.SendPropertyChanged("DL_DAY");
					this.OnDL_DAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_CODE", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DL_CODE
		{
			get
			{
				return this._DL_CODE;
			}
			set
			{
				if ((this._DL_CODE != value))
				{
					this.OnDL_CODEChanging(value);
					this.SendPropertyChanging();
					this._DL_CODE = value;
					this.SendPropertyChanged("DL_CODE");
					this.OnDL_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_SUBCODE1", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_SUBCODE1
		{
			get
			{
				return this._DL_SUBCODE1;
			}
			set
			{
				if ((this._DL_SUBCODE1 != value))
				{
					this.OnDL_SUBCODE1Changing(value);
					this.SendPropertyChanging();
					this._DL_SUBCODE1 = value;
					this.SendPropertyChanged("DL_SUBCODE1");
					this.OnDL_SUBCODE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_SUBCODE2", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_SUBCODE2
		{
			get
			{
				return this._DL_SUBCODE2;
			}
			set
			{
				if ((this._DL_SUBCODE2 != value))
				{
					this.OnDL_SUBCODE2Changing(value);
					this.SendPropertyChanging();
					this._DL_SUBCODE2 = value;
					this.SendPropertyChanged("DL_SUBCODE2");
					this.OnDL_SUBCODE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_NMEN", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short DL_NMEN
		{
			get
			{
				return this._DL_NMEN;
			}
			set
			{
				if ((this._DL_NMEN != value))
				{
					this.OnDL_NMENChanging(value);
					this.SendPropertyChanging();
					this._DL_NMEN = value;
					this.SendPropertyChanged("DL_NMEN");
					this.OnDL_NMENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_NDAYS", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> DL_NDAYS
		{
			get
			{
				return this._DL_NDAYS;
			}
			set
			{
				if ((this._DL_NDAYS != value))
				{
					this.OnDL_NDAYSChanging(value);
					this.SendPropertyChanging();
					this._DL_NDAYS = value;
					this.SendPropertyChanged("DL_NDAYS");
					this.OnDL_NDAYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_CNKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_CNKEY
		{
			get
			{
				return this._DL_CNKEY;
			}
			set
			{
				if ((this._DL_CNKEY != value))
				{
					this.OnDL_CNKEYChanging(value);
					this.SendPropertyChanging();
					this._DL_CNKEY = value;
					this.SendPropertyChanged("DL_CNKEY");
					this.OnDL_CNKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_CTKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_CTKEY
		{
			get
			{
				return this._DL_CTKEY;
			}
			set
			{
				if ((this._DL_CTKEY != value))
				{
					this.OnDL_CTKEYChanging(value);
					this.SendPropertyChanging();
					this._DL_CTKEY = value;
					this.SendPropertyChanged("DL_CTKEY");
					this.OnDL_CTKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_PARTNERKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_PARTNERKEY
		{
			get
			{
				return this._DL_PARTNERKEY;
			}
			set
			{
				if ((this._DL_PARTNERKEY != value))
				{
					this.OnDL_PARTNERKEYChanging(value);
					this.SendPropertyChanging();
					this._DL_PARTNERKEY = value;
					this.SendPropertyChanged("DL_PARTNERKEY");
					this.OnDL_PARTNERKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_COST", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DL_COST
		{
			get
			{
				return this._DL_COST;
			}
			set
			{
				if ((this._DL_COST != value))
				{
					this.OnDL_COSTChanging(value);
					this.SendPropertyChanging();
					this._DL_COST = value;
					this.SendPropertyChanged("DL_COST");
					this.OnDL_COSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_REALNETTO", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DL_REALNETTO
		{
			get
			{
				return this._DL_REALNETTO;
			}
			set
			{
				if ((this._DL_REALNETTO != value))
				{
					this.OnDL_REALNETTOChanging(value);
					this.SendPropertyChanging();
					this._DL_REALNETTO = value;
					this.SendPropertyChanged("DL_REALNETTO");
					this.OnDL_REALNETTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_BRUTTO", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DL_BRUTTO
		{
			get
			{
				return this._DL_BRUTTO;
			}
			set
			{
				if ((this._DL_BRUTTO != value))
				{
					this.OnDL_BRUTTOChanging(value);
					this.SendPropertyChanging();
					this._DL_BRUTTO = value;
					this.SendPropertyChanged("DL_BRUTTO");
					this.OnDL_BRUTTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_PAYED", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DL_PAYED
		{
			get
			{
				return this._DL_PAYED;
			}
			set
			{
				if ((this._DL_PAYED != value))
				{
					this.OnDL_PAYEDChanging(value);
					this.SendPropertyChanging();
					this._DL_PAYED = value;
					this.SendPropertyChanged("DL_PAYED");
					this.OnDL_PAYEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_WAIT", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> DL_WAIT
		{
			get
			{
				return this._DL_WAIT;
			}
			set
			{
				if ((this._DL_WAIT != value))
				{
					this.OnDL_WAITChanging(value);
					this.SendPropertyChanging();
					this._DL_WAIT = value;
					this.SendPropertyChanged("DL_WAIT");
					this.OnDL_WAITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_WARNING", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_WARNING
		{
			get
			{
				return this._DL_WARNING;
			}
			set
			{
				if ((this._DL_WARNING != value))
				{
					this.OnDL_WARNINGChanging(value);
					this.SendPropertyChanging();
					this._DL_WARNING = value;
					this.SendPropertyChanged("DL_WARNING");
					this.OnDL_WARNINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_TIMEBEG", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DL_TIMEBEG
		{
			get
			{
				return this._DL_TIMEBEG;
			}
			set
			{
				if ((this._DL_TIMEBEG != value))
				{
					this.OnDL_TIMEBEGChanging(value);
					this.SendPropertyChanging();
					this._DL_TIMEBEG = value;
					this.SendPropertyChanged("DL_TIMEBEG");
					this.OnDL_TIMEBEGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_CONTROL", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DL_CONTROL
		{
			get
			{
				return this._DL_CONTROL;
			}
			set
			{
				if ((this._DL_CONTROL != value))
				{
					this.OnDL_CONTROLChanging(value);
					this.SendPropertyChanging();
					this._DL_CONTROL = value;
					this.SendPropertyChanged("DL_CONTROL");
					this.OnDL_CONTROLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_CREATOR", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DL_CREATOR
		{
			get
			{
				return this._DL_CREATOR;
			}
			set
			{
				if ((this._DL_CREATOR != value))
				{
					this.OnDL_CREATORChanging(value);
					this.SendPropertyChanging();
					this._DL_CREATOR = value;
					this.SendPropertyChanged("DL_CREATOR");
					this.OnDL_CREATORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_OWNER", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DL_OWNER
		{
			get
			{
				return this._DL_OWNER;
			}
			set
			{
				if ((this._DL_OWNER != value))
				{
					this.OnDL_OWNERChanging(value);
					this.SendPropertyChanging();
					this._DL_OWNER = value;
					this.SendPropertyChanged("DL_OWNER");
					this.OnDL_OWNERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_ATTRIBUTE", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_ATTRIBUTE
		{
			get
			{
				return this._DL_ATTRIBUTE;
			}
			set
			{
				if ((this._DL_ATTRIBUTE != value))
				{
					this.OnDL_ATTRIBUTEChanging(value);
					this.SendPropertyChanging();
					this._DL_ATTRIBUTE = value;
					this.SendPropertyChanged("DL_ATTRIBUTE");
					this.OnDL_ATTRIBUTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_ISPAYED", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> DL_ISPAYED
		{
			get
			{
				return this._DL_ISPAYED;
			}
			set
			{
				if ((this._DL_ISPAYED != value))
				{
					this.OnDL_ISPAYEDChanging(value);
					this.SendPropertyChanging();
					this._DL_ISPAYED = value;
					this.SendPropertyChanged("DL_ISPAYED");
					this.OnDL_ISPAYEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_DATEBEG", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DL_DATEBEG
		{
			get
			{
				return this._DL_DATEBEG;
			}
			set
			{
				if ((this._DL_DATEBEG != value))
				{
					this.OnDL_DATEBEGChanging(value);
					this.SendPropertyChanging();
					this._DL_DATEBEG = value;
					this.SendPropertyChanged("DL_DATEBEG");
					this.OnDL_DATEBEGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_DATEEND", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DL_DATEEND
		{
			get
			{
				return this._DL_DATEEND;
			}
			set
			{
				if ((this._DL_DATEEND != value))
				{
					this.OnDL_DATEENDChanging(value);
					this.SendPropertyChanging();
					this._DL_DATEEND = value;
					this.SendPropertyChanged("DL_DATEEND");
					this.OnDL_DATEENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_DISCOUNT", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> DL_DISCOUNT
		{
			get
			{
				return this._DL_DISCOUNT;
			}
			set
			{
				if ((this._DL_DISCOUNT != value))
				{
					this.OnDL_DISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._DL_DISCOUNT = value;
					this.SendPropertyChanged("DL_DISCOUNT");
					this.OnDL_DISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_QUOTEKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_QUOTEKEY
		{
			get
			{
				return this._DL_QUOTEKEY;
			}
			set
			{
				if ((this._DL_QUOTEKEY != value))
				{
					this.OnDL_QUOTEKEYChanging(value);
					this.SendPropertyChanging();
					this._DL_QUOTEKEY = value;
					this.SendPropertyChanged("DL_QUOTEKEY");
					this.OnDL_QUOTEKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_AGENT", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_AGENT
		{
			get
			{
				return this._DL_AGENT;
			}
			set
			{
				if ((this._DL_AGENT != value))
				{
					this.OnDL_AGENTChanging(value);
					this.SendPropertyChanging();
					this._DL_AGENT = value;
					this.SendPropertyChanged("DL_AGENT");
					this.OnDL_AGENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWID", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ROWID
		{
			get
			{
				return this._ROWID;
			}
			set
			{
				if ((this._ROWID != value))
				{
					this.OnROWIDChanging(value);
					this.SendPropertyChanging();
					this._ROWID = value;
					this.SendPropertyChanged("ROWID");
					this.OnROWIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_AgentID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_AgentID
		{
			get
			{
				return this._DL_AgentID;
			}
			set
			{
				if ((this._DL_AgentID != value))
				{
					this.OnDL_AgentIDChanging(value);
					this.SendPropertyChanging();
					this._DL_AgentID = value;
					this.SendPropertyChanged("DL_AgentID");
					this.OnDL_AgentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_Comment", DbType="VarChar(254)", UpdateCheck=UpdateCheck.Never)]
		public string DL_Comment
		{
			get
			{
				return this._DL_Comment;
			}
			set
			{
				if ((this._DL_Comment != value))
				{
					this.OnDL_CommentChanging(value);
					this.SendPropertyChanging();
					this._DL_Comment = value;
					this.SendPropertyChanged("DL_Comment");
					this.OnDL_CommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_Reserved", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_Reserved
		{
			get
			{
				return this._DL_Reserved;
			}
			set
			{
				if ((this._DL_Reserved != value))
				{
					this.OnDL_ReservedChanging(value);
					this.SendPropertyChanging();
					this._DL_Reserved = value;
					this.SendPropertyChanged("DL_Reserved");
					this.OnDL_ReservedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_DGKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_DGKEY
		{
			get
			{
				return this._DL_DGKEY;
			}
			set
			{
				if ((this._DL_DGKEY != value))
				{
					if (this._tbl_Dogovor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDL_DGKEYChanging(value);
					this.SendPropertyChanging();
					this._DL_DGKEY = value;
					this.SendPropertyChanged("DL_DGKEY");
					this.OnDL_DGKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_FORMULANETTO", DbType="VarChar(254)", UpdateCheck=UpdateCheck.Never)]
		public string DL_FORMULANETTO
		{
			get
			{
				return this._DL_FORMULANETTO;
			}
			set
			{
				if ((this._DL_FORMULANETTO != value))
				{
					this.OnDL_FORMULANETTOChanging(value);
					this.SendPropertyChanging();
					this._DL_FORMULANETTO = value;
					this.SendPropertyChanged("DL_FORMULANETTO");
					this.OnDL_FORMULANETTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_FORMULABRUTTO", DbType="VarChar(254)", UpdateCheck=UpdateCheck.Never)]
		public string DL_FORMULABRUTTO
		{
			get
			{
				return this._DL_FORMULABRUTTO;
			}
			set
			{
				if ((this._DL_FORMULABRUTTO != value))
				{
					this.OnDL_FORMULABRUTTOChanging(value);
					this.SendPropertyChanging();
					this._DL_FORMULABRUTTO = value;
					this.SendPropertyChanged("DL_FORMULABRUTTO");
					this.OnDL_FORMULABRUTTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_BLOCKED", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> DL_BLOCKED
		{
			get
			{
				return this._DL_BLOCKED;
			}
			set
			{
				if ((this._DL_BLOCKED != value))
				{
					this.OnDL_BLOCKEDChanging(value);
					this.SendPropertyChanging();
					this._DL_BLOCKED = value;
					this.SendPropertyChanged("DL_BLOCKED");
					this.OnDL_BLOCKEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_NameLat", DbType="VarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string DL_NameLat
		{
			get
			{
				return this._DL_NameLat;
			}
			set
			{
				if ((this._DL_NameLat != value))
				{
					this.OnDL_NameLatChanging(value);
					this.SendPropertyChanging();
					this._DL_NameLat = value;
					this.SendPropertyChanged("DL_NameLat");
					this.OnDL_NameLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_PRTDOGKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_PRTDOGKEY
		{
			get
			{
				return this._DL_PRTDOGKEY;
			}
			set
			{
				if ((this._DL_PRTDOGKEY != value))
				{
					this.OnDL_PRTDOGKEYChanging(value);
					this.SendPropertyChanging();
					this._DL_PRTDOGKEY = value;
					this.SendPropertyChanged("DL_PRTDOGKEY");
					this.OnDL_PRTDOGKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_TAXZONEID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DL_TAXZONEID
		{
			get
			{
				return this._DL_TAXZONEID;
			}
			set
			{
				if ((this._DL_TAXZONEID != value))
				{
					this.OnDL_TAXZONEIDChanging(value);
					this.SendPropertyChanging();
					this._DL_TAXZONEID = value;
					this.SendPropertyChanged("DL_TAXZONEID");
					this.OnDL_TAXZONEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_Long", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short DL_Long
		{
			get
			{
				return this._DL_Long;
			}
			set
			{
				if ((this._DL_Long != value))
				{
					this.OnDL_LongChanging(value);
					this.SendPropertyChanging();
					this._DL_Long = value;
					this.SendPropertyChanged("DL_Long");
					this.OnDL_LongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_IsDeleted", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> DL_IsDeleted
		{
			get
			{
				return this._DL_IsDeleted;
			}
			set
			{
				if ((this._DL_IsDeleted != value))
				{
					this.OnDL_IsDeletedChanging(value);
					this.SendPropertyChanging();
					this._DL_IsDeleted = value;
					this.SendPropertyChanged("DL_IsDeleted");
					this.OnDL_IsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_SalePrice", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DL_SalePrice
		{
			get
			{
				return this._DL_SalePrice;
			}
			set
			{
				if ((this._DL_SalePrice != value))
				{
					this.OnDL_SalePriceChanging(value);
					this.SendPropertyChanging();
					this._DL_SalePrice = value;
					this.SendPropertyChanged("DL_SalePrice");
					this.OnDL_SalePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_SaleDiscount", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> DL_SaleDiscount
		{
			get
			{
				return this._DL_SaleDiscount;
			}
			set
			{
				if ((this._DL_SaleDiscount != value))
				{
					this.OnDL_SaleDiscountChanging(value);
					this.SendPropertyChanging();
					this._DL_SaleDiscount = value;
					this.SendPropertyChanged("DL_SaleDiscount");
					this.OnDL_SaleDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_FormulaDiscount", DbType="VarChar(254)", UpdateCheck=UpdateCheck.Never)]
		public string DL_FormulaDiscount
		{
			get
			{
				return this._DL_FormulaDiscount;
			}
			set
			{
				if ((this._DL_FormulaDiscount != value))
				{
					this.OnDL_FormulaDiscountChanging(value);
					this.SendPropertyChanging();
					this._DL_FormulaDiscount = value;
					this.SendPropertyChanged("DL_FormulaDiscount");
					this.OnDL_FormulaDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Dogovor_tbl_DogovorList", Storage="_tbl_Dogovor", ThisKey="DL_DGKEY", OtherKey="DG_Key", IsForeignKey=true)]
		public tbl_Dogovor tbl_Dogovor
		{
			get
			{
				return this._tbl_Dogovor.Entity;
			}
			set
			{
				tbl_Dogovor previousValue = this._tbl_Dogovor.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Dogovor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Dogovor.Entity = null;
						previousValue.tbl_DogovorLists.Remove(this);
					}
					this._tbl_Dogovor.Entity = value;
					if ((value != null))
					{
						value.tbl_DogovorLists.Add(this);
						this._DL_DGKEY = value.DG_Key;
					}
					else
					{
						this._DL_DGKEY = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Dogovor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lanta_RouteCertificateAdmin")]
	public partial class Lanta_RouteCertificateAdmin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RCA_DGKey;
		
		private string _RCA_DGCODE;
		
		private bool _RCA_AllowPrint;
		
		private System.Nullable<int> _RCA_Admin;
		
		private System.Nullable<System.DateTime> _RCA_LastChange;
		
		private EntityRef<tbl_Dogovor> _tbl_Dogovor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRCA_DGKeyChanging(int value);
    partial void OnRCA_DGKeyChanged();
    partial void OnRCA_DGCODEChanging(string value);
    partial void OnRCA_DGCODEChanged();
    partial void OnRCA_AllowPrintChanging(bool value);
    partial void OnRCA_AllowPrintChanged();
    partial void OnRCA_AdminChanging(System.Nullable<int> value);
    partial void OnRCA_AdminChanged();
    partial void OnRCA_LastChangeChanging(System.Nullable<System.DateTime> value);
    partial void OnRCA_LastChangeChanged();
    #endregion
		
		public Lanta_RouteCertificateAdmin()
		{
			this._tbl_Dogovor = default(EntityRef<tbl_Dogovor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCA_DGKey", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RCA_DGKey
		{
			get
			{
				return this._RCA_DGKey;
			}
			set
			{
				if ((this._RCA_DGKey != value))
				{
					if (this._tbl_Dogovor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRCA_DGKeyChanging(value);
					this.SendPropertyChanging();
					this._RCA_DGKey = value;
					this.SendPropertyChanged("RCA_DGKey");
					this.OnRCA_DGKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCA_DGCODE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string RCA_DGCODE
		{
			get
			{
				return this._RCA_DGCODE;
			}
			set
			{
				if ((this._RCA_DGCODE != value))
				{
					this.OnRCA_DGCODEChanging(value);
					this.SendPropertyChanging();
					this._RCA_DGCODE = value;
					this.SendPropertyChanged("RCA_DGCODE");
					this.OnRCA_DGCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCA_AllowPrint", DbType="Bit NOT NULL")]
		public bool RCA_AllowPrint
		{
			get
			{
				return this._RCA_AllowPrint;
			}
			set
			{
				if ((this._RCA_AllowPrint != value))
				{
					this.OnRCA_AllowPrintChanging(value);
					this.SendPropertyChanging();
					this._RCA_AllowPrint = value;
					this.SendPropertyChanged("RCA_AllowPrint");
					this.OnRCA_AllowPrintChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCA_Admin", DbType="Int")]
		public System.Nullable<int> RCA_Admin
		{
			get
			{
				return this._RCA_Admin;
			}
			set
			{
				if ((this._RCA_Admin != value))
				{
					this.OnRCA_AdminChanging(value);
					this.SendPropertyChanging();
					this._RCA_Admin = value;
					this.SendPropertyChanged("RCA_Admin");
					this.OnRCA_AdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCA_LastChange", DbType="DateTime")]
		public System.Nullable<System.DateTime> RCA_LastChange
		{
			get
			{
				return this._RCA_LastChange;
			}
			set
			{
				if ((this._RCA_LastChange != value))
				{
					this.OnRCA_LastChangeChanging(value);
					this.SendPropertyChanging();
					this._RCA_LastChange = value;
					this.SendPropertyChanged("RCA_LastChange");
					this.OnRCA_LastChangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Dogovor_Lanta_RouteCertificateAdmin", Storage="_tbl_Dogovor", ThisKey="RCA_DGKey", OtherKey="DG_Key", IsForeignKey=true)]
		public tbl_Dogovor tbl_Dogovor
		{
			get
			{
				return this._tbl_Dogovor.Entity;
			}
			set
			{
				tbl_Dogovor previousValue = this._tbl_Dogovor.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Dogovor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Dogovor.Entity = null;
						previousValue.Lanta_RouteCertificateAdmins.Remove(this);
					}
					this._tbl_Dogovor.Entity = value;
					if ((value != null))
					{
						value.Lanta_RouteCertificateAdmins.Add(this);
						this._RCA_DGKey = value.DG_Key;
					}
					else
					{
						this._RCA_DGKey = default(int);
					}
					this.SendPropertyChanged("tbl_Dogovor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
